import type { Card, Fame, Sector } from './types'

// ─── O catálogo de cartas ────────────────────────────────────────────
// NÍVEL exibido na carta (o `fame` guia CPU/curadoria e é convertido no label):
// 5 = LENDA (faixa estreita e altíssima)
// 4 = CRAQUE
// 3 e 2 = BOM JOGADOR (2 tem faixa mais LARGA — "o Obina tem dias")
// 1 = FOI PROFISSIONAL (limitado, overall baixo) / também incógnitas geradas
// `promessa: true` = 5º tier PROMESSA (fez auge só como promessa aqui e virou
//   estrela na Europa) — fica ABAIXO de craque, mesmo com fame 3/4 interno.
// O selo 🃏 folclórico é à parte (campo `folk`) — vibe, não nível.

type C = { name: string; club: string; year: number; fame: Fame; lo: number; hi: number; bio?: string; folk?: boolean; promessa?: boolean }

// texto de referência que aparece na carta-lembrança do álbum (só o campeão
// ganha). Mapeado por nome — assim dá pra ir preenchendo aos poucos sem mexer
// no catálogo. Quem não tem bio ainda mostra um texto genérico por categoria.
export const BIOS: Record<string, string> = {
  "Dener": "Gênio do drible dos anos 90 — talento que encantava o país e seria titular da Seleção. Patrimônio eterno, partiu cedo demais.",
  "Adriano Gol Contra": "O zagueirão do Madureira que virou lenda do “Inacreditável Futebol Clube” — o rei do gol contra, folclore puro.",
  "Zagallo": "O Velho Lobo. Ponta bicampeão do mundo (58 e 62) ao lado de Pelé e Garrincha — o maior amuleto do futebol brasileiro.",
  "Hélton": "Goleiro revelado no Vasco de 2000 e ídolo eterno do Porto — mais de uma década de grife europeia.",
  "Igor Catatau": "Puro suco da resenha carioca. O nome já arranca risada na mesa — carta de meme por excelência.",
  "Yago Pikachu": "Pikachu! Lateral-atacante elétrico, virou artilheiro e ídolo no Fortaleza — apelido e gols de resenha.",
  "James Rodríguez": "Craque colombiano, Bola de Ouro da Copa de 2014, que passou pelo São Paulo — passe refinado e grife mundial.",
  "Ruy Cabeção": "O “Cabeção”. Lateral rodado e raçudo — o apelido virou folclore por si só.",
  "Fernando Diniz": "Meia dos anos 2000 que virou o técnico do jogo bonito e das maiores resenhas do país.",
  "Adílio": "O camisa 8 da era de ouro do Flamengo — campeão do mundo em 81 ao lado de Zico. Grife histórica carioca.",
  "Igor Thiago": "Menino ex-Cruzeiro que explodiu na Europa (Brugge, Brentford) — promessa moderna de alto teto.",
  "Suárez": "O Pistoleiro. Craque uruguaio que fez uma temporada absurda no Grêmio em 2023 — grife de elite mundial.",
  "Estêvão": "A joia do Palmeiras que o mundo inteiro quis — drible e faro de craque, rumo à Europa como fenômeno.",
  "Tevez": "O Apache. Craque argentino que carregou o Corinthians ao Brasileirão de 2005 — talento e raça de sobra.",
  "Seedorf": "Tetracampeão da Champions que foi fechar a carreira no Botafogo — pura grife e elegância holandesa.",
  "Depay": "Estrela holandesa (Barça, United) que desembarcou no Corinthians — nome de peso no mercado.",
  "Pablo Marí": "Zagueiro espanhol do Flamengo campeão da Libertadores de 2019 — sólido e vencedor.",
  "Jô": "O enigma. Artilheiro do Corinthians campeão de 2015 e alvo eterno de resenha pela entrega oscilante.",
  "Dimba": "Artilheiro do primeiro Brasileirão de pontos corridos (2003) pelo Goiás — 31 gols de puro folclore.",
  "Josiel": "Artilheiro do Brasileirão de 2007 pelo Paraná — brilhou forte e sumiu depois. Folclore dos pontos corridos.",
  "Dinei": "O trombador folclórico do Corinthians — raça, gols de pivô e resenha garantida.",
  "Michael": "Velocidade e dribles imprevisíveis pelo Flamengo campeão de 2020 — ninguém sabia o que ele ia fazer (às vezes nem ele).",
  "Marta": "A Rainha. Melhor do mundo 6 vezes — o maior nome do futebol brasileiro, sem distinção.",
  "Márcio Araújo": "Volante do “ame ou odeie” — rei do desarme e da polêmica no Flamengo. Resenha garantida.",
  "Hernane Brocador": "O Brocador. 2013 mágico no Flamengo: 36 gols e a Copa do Brasil — todo mundo lembra.",
  "Jorge Henrique": "Corria o campo todo, dava o chute no vácuo e provocava geral — Corinthians campeão de tudo em 2011-12.",
  "Ribamar": "“Hoje tem gol do Ribamar!” — o meme virou hino. Carta disputada a tapa só pela zoeira.",
  "Chay": "O herói do acesso do Botafogo em 2021 que brilhou forte e sumiu rápido — folclore instantâneo.",
  "Lincoln": "O ex-Flamengo da chance perdida na final contra o Liverpool. Piso baixo, emoção alta no leilão.",
  "Negueba": "A alegria nas pernas. Ícone folclórico dos anos 2010 — revelação que virou resenha eterna.",
  "Alex Muralha": "A “Muralha” que virou meme no Flamengo de 2017 — apelido de paredão, falhas de folclore. Carisma involuntário.",
  "Sidão": "Goleiro folclórico do São Paulo — até fez gol, mas as falhas renderam mais resenha que as defesas.",
  "Alecsandro": "O Alecgol. Centroavante rodado e de faro, campeão da Libertadores de 2013 pelo Galo — nome que todo mundo conhece.",
  "Pelé": "O Rei do Futebol. O maior de todos os tempos, topo absoluto do esporte mundial.",
  "Garrincha": "A alegria do povo. Dribles previsíveis, porém imparáveis, que carregaram o Brasil ao bi em 62.",
  "Ronaldo": "O Fenômeno. O maior camisa 9 da história: velocidade bizarra e potência que destruía defesas.",
  "Romário": "O gênio da grande área. Arranque curto mortal e frieza cirúrgica — campeão do mundo em 94.",
  "Neymar": "O maior talento técnico da última geração. O rei dos dribles plásticos.",
  "Zico": "O maior camisa 10 da história do Flamengo e a essência do futebol brasileiro pós-Pelé.",
  "Ronaldinho Gaúcho": "O auge mais plástico e mágico do futebol moderno. Fazia mágica sorrindo.",
  "Rivaldo": "Gênio da Copa de 2002. Passada elegante, finalização cirúrgica, eleito o melhor do mundo.",
  "Sócrates": "O Doutor. Inteligência pura, passes de calcanhar milimétricos e um dos maiores líderes do esporte.",
  "Jairzinho": "O Furacão da Copa. Único a marcar em todas as partidas de um Mundial (1970).",
  "Zizinho": "O grande ídolo de Pelé. Mestre do drible e do passe que dominou o futebol sul-americano.",
  "Leônidas da Silva": "O Diamante Negro. Inventor da bicicleta, artilheiro da Copa de 1938.",
  "Taffarel": "O maior goleiro da história da Seleção. O \"sai que é sua\" virou mantra nacional em 94.",
  "Gilmar": "O goleiro dos dois primeiros títulos mundiais (58 e 62). Sobriedade absoluta sob as traves.",
  "Rogério Ceni": "O goleiro-artilheiro que revolucionou a posição e fechou o gol no Mundial de 2005.",
  "Carlos Alberto Torres": "O Capita eterno do tri, autor do gol mais icônico da história das Copas.",
  "Nílton Santos": "A Enciclopédia do Futebol. Praticamente inventou a função do lateral moderno que ataca.",
  "Cafu": "Fôlego interminável, três finais de Copa seguidas e dono da lateral da Seleção por uma década.",
  "Roberto Carlos": "Transformou potência em arte. O chute de esquerda mais temido do planeta.",
  "Djalma Santos": "Uma rocha na lateral. Primeiro grande bicampeão mundial do Brasil.",
  "Domingos da Guia": "O Divino Mestre. Inventou a saída de bola driblando, na década de 1930.",
  "Lúcio": "O Cavalo de Aço. Desarmava e arrancava com a bola dominada até o ataque. Capitão de 2002.",
  "Hilderaldo Bellini": "O homem que inventou o gesto de erguer a taça. Capitão do primeiro título mundial.",
  "Didi": "O inventor da folha seca. Maestro do primeiro título mundial e melhor jogador da Copa de 58.",
  "Rivelino": "O dono do Maracanã. Chute canhoto violento e o drible da vaca que encantou o mundo.",
  "Vinicius Jr": "O protagonista da nova geração. Velocidade e drible que decidem Champions pelo Real Madrid.",
  "Casemiro": "O cão de guarda mais premiado do futebol. Pilar de um Real Madrid multicampeão da Champions.",
  "Rodrygo": "Iluminado nos momentos de pressão. Técnica e faro de gols decisivos no Real Madrid.",
  "Éder Militão": "Força e velocidade no mano a mano. Pilar defensivo do Real Madrid campeão da Champions.",
  "Marquinhos": "Zagueiro-capitão do PSG e da Seleção. Saída de bola e liderança há mais de uma década na Europa.",
  "Alisson": "Paredão da Seleção e do Liverpool. Posicionamento perfeito e frieza cirúrgica nos pênaltis.",
  "Bruno Guimarães": "Ditador de ritmo. Une a raça inglesa com a ginga e a visão de jogo brasileira no Newcastle.",
  "Lucas Paquetá": "Meia criativo de muita técnica e chegada à área. Do Flamengo pra Europa como craque.",
  "João Gomes": "Volante de pulmão infinito. Marca, recupera e ainda chega na área — revelação do Flamengo.",
  "Gabriel Jesus": "Camisa 9 de muita movimentação e entrega. Do Palmeiras direto pra Premier League.",
  "Richarlison Pombo": "O Pombo. Centroavante de raça, gols de bicicleta e entrega máxima pela Seleção.",
  "Endrick": "A joia de Palmeiras e Real Madrid. Finalização precoce de craque — o futuro do ataque.",
  "Antony": "Ponta canhoto de dribles e chute colocado. Do São Paulo pro Ajax e Manchester United.",
  "Vitor Roque": "O Matador. Centroavante jovem, forte e finalizador — do Athletico ao Barcelona.",
  "Yuri Alberto": "Faro de gol apurado. Artilheiro jovem que virou referência no Corinthians.",
  "Wesley": "Lateral moderno do Flamengo: potência, arrancada e muita chegada ao ataque.",
  "Deyverson": "O guerreiro folclórico. Roubou a bola e fez o gol do título da Libertadores de 2021 pelo Palmeiras.",
  "Marcos": "O São Marcos. Fez milagres na Libertadores de 99 e foi o paredão do penta em 2002.",
  "Emerson Leão": "Goleiro de personalidade e reflexo felino. Um dos maiores do Brasil nos anos 70.",
  "Júlio César": "No auge na Itália, foi eleito o melhor goleiro do mundo. Agilidade e explosão impressionantes.",
  "Cássio": "O gigante do Corinthians. Herói do Mundial de 2012, especialista em pegar pênalti.",
  "Manga": "Lenda dos anos 70. Jogava sem luvas, com os dedos tortos das boladas — puro folclore e raça.",
  "Castilho": "O maior goleiro da história do Fluminense. Elegância e segurança sob as traves.",
  "Dani Alves": "Uma máquina de empilhar taças. Revolucionou a lateral no Barcelona quase como um meia.",
  "Marcelo": "A habilidade de um camisa 10 jogando na lateral-esquerda. Empilhou Champions no Real Madrid.",
  "Júnior Maestro": "O Maestro. Inteligência pura com a bola nos pés no Flamengo de 81 e na Seleção de 82.",
  "Leandro": "Elegância absurda. Cruzava como ninguém no Flamengo dos anos 80.",
  "Filipe Luís": "Um estrategista em campo: leitura tática perfeita e saída de bola impecável.",
  "Aldair": "Frieza e elegância. Posicionamento impecável, pilar do tetra em 94 e ídolo na Roma.",
  "Thiago Silva": "Monstro da leitura tática. Um dos defensores mais perfeitos por antecipação da era moderna.",
  "Luís Pereira": "Técnica tão refinada que saía jogando driblando os atacantes. Ídolo no Palmeiras.",
  "Mauro Ramos": "Capitão do bicampeonato de 62. Elegância pura na zaga do Santos de Pelé.",
  "Falcão": "O Rei de Roma. Ditava o ritmo do jogo com uma elegância que redefiniu a posição de volante.",
  "Gérson Canhotinha de Ouro": "A Canhotinha de Ouro. Lançamentos de 40 metros que caíam no peito dos atacantes no tri de 70.",
  "Kaká": "Arranques verticais avassaladores e elegância pura. Último brasileiro a ganhar a Bola de Ouro.",
  "Raí": "O terror do Barcelona no Mundial de 92. Forte, elegante e decisivo nas grandes finais.",
  "Ademir da Guia": "O Divino. O maestro do Palmeiras, dono do ritmo do jogo com uma classe única.",
  "Neto": "A canhota mais precisa do país no início dos anos 90. Carregou o Corinthians ao primeiro título brasileiro.",
  "D'Alessandro": "O dono de Porto Alegre. Liderança, categoria e idolatria eterna no Internacional.",
  "Paulinho": "O volante que virava atacante. Defendia com raça e aparecia na área pra fazer gols decisivos.",
  "Clodoaldo": "O garoto que limpou o meio em 70 e driblou quatro italianos no gol mais bonito das Copas.",
  "Dunga": "A liderança em forma de homem. Garantiu a solidez mental e defensiva do tetra em 94.",
  "Juninho Pernambucano": "O maior batedor de faltas da história. Rei absoluto na França com sua precisão.",
  "Tostão": "Inteligência pura e raciocínio na velocidade da luz. O parceiro perfeito de Pelé em 70.",
  "Bebeto": "Movimentação e voleios perfeitos. Formou com Romário a dupla mais icônica do tetra.",
  "Careca": "Centroavante técnico, elegante e letal. Fez dupla histórica com Maradona no Napoli.",
  "Reinaldo": "Gênio dos gramados. Se não fossem os joelhos, brigaria com os maiores artilheiros da história.",
  "Robinho": "Pedaladas inesquecíveis que tiraram o Santos da fila. Futebol moleque de muita ousadia.",
  "Adriano": "O Imperador. Força física assustadora e uma patada de esquerda que virou lenda.",
  "Edmundo": "O Animal. Genialidade com a bola e um temperamento explosivo — talento puro.",
  "Roberto Dinamite": "O maior artilheiro da história do Brasileirão e lenda máxima do Vasco.",
  "Hulk": "Potência física e chutes de fora da área que parecem mísseis. Carregou o Galo.",
  "Luís Fabiano": "O Fabuloso. Centroavante completo, forte e de finalização cirúrgica.",
  "Bruno Henrique": "O predestinado do Flamengo. Velocidade e decisão em finais de Libertadores.",
  "Vavá": "O Peito de Aço. Raça e força, decisivo com gols nas finais das Copas de 58 e 62.",
  "Gabigol": "O predestinado. Faro de gol absurdo e poder de decisão gigante em finais de Libertadores.",
  "Evair": "A elegância em forma de camisa 9. Jogava de cabeça erguida e batia pênaltis com frieza.",
  "Fred": "O mestre do primeiro toque. Um dos centroavantes mais letais do futebol nacional.",
  "Obina": "O homem que a torcida jurava ser melhor que o Eto'o. Carisma puro e gols salvadores no Flamengo.",
  "Túlio Maravilha": "O marketing em pessoa. Prometia gols, criava apelidos e perseguiu os mil gols com irreverência.",
  "Renato Gaúcho": "O rei do Rio e de Porto Alegre. Marrento ao extremo, decidia até Mundial.",
  "Petkovic": "Gringo com alma brasileira. Cobranças de falta perfeitas que orquestraram o título de 2009.",
  "Valdivia": "O Mago. Destruía o jogo com dribles plásticos, provocações e genialidade.",
  "Dadá Maravilha": "O homem dos voos rasantes. Dizia que gol feio é não fazer — puro folclore e frases icônicas.",
  "Dida": "Frieza que assustava atacantes. Envergadura absurda e terror dos pênaltis, bicampeão da Champions pelo Milan.",
  "Fábio": "Uma das maiores consistências do país. Reflexo puríssimo que seguiu operando milagres no Cruzeiro.",
  "Jefferson": "Goleiro de defesas de cinema. Passou anos fazendo o impossível parecer normal no Botafogo.",
  "Zetti": "Elegância sob as traves. Esteio do São Paulo bicampeão do mundo no início dos anos 90.",
  "Carlos Germano": "Paredão do Vasco campeão da Libertadores de 98, seguro e decisivo nos mata-matas.",
  "Ronaldo Giovanelli": "Goleiro do Corinthians campeão paulista de 90, reflexos rápidos e boa saída.",
  "Velloso": "Goleiro raçudo do Palmeiras da Parmalat, peça da base vencedora dos anos 90.",
  "Harlei": "Ídolo do Goiás por mais de uma década. Regularidade e identificação total com o clube.",
  "Sérgio": "Goleiro do Palmeiras campeão brasileiro de 93, seguro e experiente.",
  "Wagner Leite": "Goleiro rodado dos anos 90, com passagens marcantes pelo Atlético-MG.",
  "Félix": "O goleiro do tri de 70. Estilo espetaculoso e reflexos felinos na Seleção.",
  "Weverton": "Regularidade assustadora e frieza nos jogos decisivos. Peça da era mais vencedora do Palmeiras.",
  "Victor": "O São Victor do Horto. Entrou pra história com a defesa de pé contra o Tijuana na Libertadores.",
  "Danrlei": "A raça imortal do Grêmio. Fechou o gol tricolor nas conquistas dos anos 90.",
  "Aranha": "Goleiro de bons reflexos do Santos, destaque no vice da Libertadores de 2011.",
  "Fábio Costa": "Capitão e paredão do Santos campeão brasileiro de 2002, decisivo nos mata-matas.",
  "Gatito Fernández": "Segurança pura e pegador de pênaltis nato. O porto seguro do Botafogo.",
  "Branco": "Dono de uma das faltas mais violentas do país. Pilar do apoio no tetra de 94.",
  "Jorginho": "Cruzamentos milimétricos na cabeça dos atacantes. Lateral eficiente e vital no tetra.",
  "Leonardo": "Lateral-esquerdo de muita técnica e chegada. Elegância no São Paulo e na Seleção.",
  "Maicon": "No auge na Itália foi imparável. Potência física avassaladora e gols cruciais pela Inter.",
  "Belletti": "Lateral seguro e vencedor. Marcou o gol do título da Champions pelo Barcelona.",
  "Zé Maria": "Lateral raçudo do Corinthians dos anos 70, marcador firme e capitão respeitado.",
  "Cicinho": "Velocidade e apoio devastadores no São Paulo campeão do mundo de 2005.",
  "Athirson": "Lateral-esquerdo habilidoso do Flamengo, bom cruzamento e chegada ao ataque.",
  "Léo": "O Guerreiro da Vila. Identificação máxima com o Santos, muita intensidade e raça.",
  "Sorín": "Lateral-esquerdo argentino de raça e apoio ofensivo. Brilhou no Cruzeiro e virou capitão da Argentina.",
  "Marcos Rocha": "Um dos maiores vencedores recentes. Excelente no apoio, multicampeão por Atlético e Palmeiras.",
  "Fágner": "Símbolo de regularidade e firmeza. Anos de confiança no Corinthians e na Seleção.",
  "Egídio": "Lateral-esquerdo de bom cruzamento, rodado por Cruzeiro, Palmeiras e Fluminense.",
  "Léo Moura": "Longevidade impressionante e o moicano icônico. Marcou época e resenha eterna no Flamengo.",
  "Rafinha": "Inteligência tática europeia. Anos em alto nível no Bayern, extremamente confiável.",
  "Ceará": "Lateral-esquerdo veloz e raçudo, peça do Fluminense campeão brasileiro de 2012.",
  "Alex Telles": "Especialista em bola parada e cruzamento. Revelou-se no Grêmio antes de brilhar na Europa.",
  "Renê": "Lateral-esquerdo firme do Flamengo, regular na conquista da Libertadores de 2019.",
  "Ayrton Lucas": "Arrancadas potentes de linha de fundo que quebram a marcação. Força pura no Flamengo.",
  "Guga": "Lateral-direito veloz e de bom cruzamento, destaque no Atlético-MG.",
  "Mayke": "Eficiência silenciosa. Multicampeão nacional por Cruzeiro e Palmeiras.",
  "Marcinho": "Lateral-direito veloz, ídolo do Botafogo pela entrega e chegada ao ataque.",
  "Pará": "Lateral-direito rodado, campeão brasileiro pelo Fluminense em 2012.",
  "Zeca": "Lateral-esquerdo raçudo revelado no Santos, muita entrega pelo corredor.",
  "Cortez": "Do estilo zigue-zague no Botafogo até virar campeão da América pelo Grêmio.",
  "Rodinei": "Lateral-direito raçudo e folclórico do Flamengo — corria o jogo todo, campeão querido da torcida.",
  "Isla": "Lateral-direito chileno de muita experiência, veterano vencedor no Flamengo.",
  "Oscar": "Zagueiro clássico e líder da Seleção nos anos 80. Marcação firme e saída limpa.",
  "Ricardo Gomes": "Técnico, elegante e líder nato. Capitão da Seleção e muito respeitado na Europa.",
  "Antônio Carlos": "Zagueiro de raça e bom passe longo. Campeão pelo Palmeiras da Parmalat e pela Roma.",
  "Juan": "Estilo clássico e silencioso. Categoria pra sair jogando e dupla lendária com Lúcio.",
  "Edmílson": "Zagueiro técnico que saía jogando com facilidade. Peça tática crucial na Copa de 2002.",
  "Mauro Galvão": "Venceu a idade com inteligência. Comandou a zaga do Vasco campeão da América aos 36.",
  "Júnior Baiano": "Especialista em sustos e carrinhos voadores. Marcava gols e rendia resenhas impagáveis.",
  "Chicão": "Zagueiro-artilheiro que batia falta e pênalti. Líder da reconstrução do Corinthians.",
  "Gamarra": "Estrangeiro de alma brasileira. Passou a Copa de 98 sem uma falta — desarme em nível artístico.",
  "Odvan": "O criador do estilo zagueiro-zagueiro. Folclore puro da Seleção de 98.",
  "Beto Bacamarte": "Zagueiro raçudo do Grêmio dos anos 70, eleito a Bola de Prata em 1972.",
  "Wilson Piazza": "Classe e liderança. Saía jogando de cabeça erguida no time de 70.",
  "Brito": "Zagueiro central do tri de 70, marcador firme e seguro na Seleção campeã.",
  "Miranda": "Zagueiro perfeito taticamente. Parede intransponível no auge na Espanha.",
  "Dedé": "O Mito. No auge físico, aliava velocidade a desarmes de carrinho perfeitos.",
  "David Luiz": "Cabelo icônico, técnica pra lançamentos e um estilo expansivo que rendeu títulos na Europa.",
  "Lugano": "O uruguaio que virou divindade no Morumbi. Deixava a vida em campo e intimidava no olhar.",
  "Gustavo Gómez": "Zagueiro paraguaio de muita raça e faro de gol. Capitão do Palmeiras multicampeão.",
  "Réver": "O Capitão América do Galo. Presença aérea avassaladora na defesa e no ataque.",
  "Geromel": "O Geromito. Dominou o futebol sul-americano com desarmes precisos e regularidade.",
  "Kannemann": "Estilo carrapato. Joga com raça de final em toda jogada — muralha do Grêmio.",
  "Robson Bambu": "Zagueiro criticado pelo desempenho no Vasco, virou personagem folclórico da torcida.",
  "Rodrigo Caio": "Antecipação e precisão cirúrgicas. O xerife do Flamengo no ano mágico de 2019.",
  "Fábio Luciano": "Capitão à moda antiga, xerife respeitado no grito por Corinthians e Flamengo.",
  "Gil": "Uma parede física. No auge do Corinthians de Tite, quase impossível de vencer no mano a mano.",
  "Léo Ortiz": "Zagueiro construtor de elite. Quebra linhas com passes verticais — do Bragantino ao Flamengo.",
  "Fabrício Bruno": "Zagueiro firme e de bom jogo aéreo, pilar do Flamengo e convocado pra Seleção.",
  "Léo Pereira": "Zagueiro canhoto de boa saída de bola e marcação, titular do Flamengo.",
  "Nino": "Zagueiro-capitão do Fluminense campeão da Libertadores de 2023. Liderança e gols decisivos.",
  "Vitão": "Zagueiro alto e veloz, líder da defesa do Internacional.",
  "Manoel": "Zagueiro seguro e experiente, rodado por Cruzeiro, Corinthians e Fluminense.",
  "Rhodolfo": "Zagueiro de bom jogo aéreo, rodado por Grêmio, Flamengo e Corinthians.",
  "Anderson Martins": "Zagueiro firme e líder, capitão em passagens por Vasco e São Paulo.",
  "Lucas Veríssimo": "Zagueiro veloz e de boa saída revelado no Santos antes de ir pro Benfica.",
  "Cerezo": "Fôlego interminável e técnica refinada. Transição defesa-ataque com naturalidade na Seleção de 82.",
  "Zinho": "Meia-esquerda inteligente e regular. Equilíbrio e qualidade no tetra de 94.",
  "Alex": "O camisa 10 clássico e cerebral. Comandou a Tríplice Coroa do Cruzeiro jogando arte.",
  "Djalminha": "A ousadia em pessoa. Capaz de driblar qualquer um e inventar jogadas geniais.",
  "Marcelinho Carioca": "O Pé de Anjo. O maior batedor de faltas da história do Corinthians.",
  "Edílson": "O Capetinha. As embaixadinhas que pararam o país na final do Paulistão de 99.",
  "Dario Conca": "Jogou as 38 rodadas de 2010 carregando o Fluminense ao título com assistências mágicas.",
  "Paulo Henrique Ganso": "Ritmo lento e genialidade em passes e fintas, com um toque dos anos 70.",
  "Felipe": "Meia habilidoso e polêmico do Vasco, dono de faltas e jogadas geniais nos anos 2000.",
  "PC Caju": "Polivalente e irreverente, craque do futebol brasileiro na virada dos anos 70.",
  "Ramires": "O Queniano. Fôlego inacreditável pra correr o campo, marcar e fazer gols históricos.",
  "Juninho Paulista": "Meia técnico e batedor de faltas, brilhou no Middlesbrough e voltou campeão pelo São Paulo.",
  "Zé Roberto": "Longevidade absurda e taticamente perfeito. Jogava em qualquer posição com a mesma intensidade.",
  "Rincón": "Volante colombiano poderoso, força e liderança no Corinthians campeão do mundo de 2000.",
  "Arrascaeta": "O mago uruguaio do Flamengo. Passes de gênio e gols decisivos nas Libertadores.",
  "Mascherano": "O Jefecito. Volante argentino de marcação impecável, brilhou no Corinthians antes da Europa.",
  "Renato Augusto": "Visão de jogo em câmera lenta. Ditava o ritmo com passes de três dedos no Corinthians.",
  "Diego": "Meia clássico e cerebral. Arrebentou na Alemanha e virou líder e maestro no Flamengo.",
  "Everton Ribeiro": "Dribles curtos e elegantes com a canhota. Craque dos títulos do Flamengo.",
  "Montillo": "O argentino franzino que deitava nas defesas com arrancadas e dribles secos no Cruzeiro.",
  "Vampeta": "O presidente da resenha. Volante campeão do mundo em 2002 e figura folclórica eterna.",
  "Marcelinho Paraíba": "Meia de chute fortíssimo e muita irreverência, artilheiro em vários clubes.",
  "Denílson": "O rei das pedaladas. Já foi o jogador mais caro do mundo pelo drible que ninguém parava.",
  "Biro-Biro": "Ídolo carismático do Corinthians dos anos 80, parte da Democracia Corinthiana.",
  "Beto Cachaça": "Talento no meio-campo, mas eternizado por curtir a noite carioca tanto quanto a bola.",
  "Perdigão": "Figuraça de físico improvável, mas cheio de carisma — campeão da Libertadores pelo Inter em 2006.",
  "Walter Minhoca": "Creditado como o pior camisa 10 da história do Flamengo — puro folclore de 2006.",
  "Hernanes": "O Profeta. Ambidestro que batia falta com as duas pernas e desequilibrava de fora da área.",
  "Thiago Neves": "Autor de um hat-trick na final da Libertadores de 2008. Meia técnico e decisivo.",
  "Nenê": "O vovô garoto. Cobranças de falta magistrais e liderança no Vasco e no Fluminense.",
  "Gerson": "O Coringa. Volante moderno de muita técnica e chegada, campeão pelo Flamengo.",
  "Gustavo Scarpa": "Meia canhoto de bom passe e bola parada, multicampeão pelo Palmeiras.",
  "Raphael Veiga": "Meia goleador do Palmeiras. Frieza nos pênaltis e gols em finais de Libertadores.",
  "Lucas Lima": "No auge na Vila, era o maior garçom do país, quebrando defesas com passes verticais.",
  "Giuliano": "Meia habilidoso e goleador, decisivo no Grêmio campeão da Copa do Brasil de 2016.",
  "Jadson": "O maestro silencioso do Corinthians campeão de 2015. Assistências açucaradas e frieza.",
  "Elias": "Dinâmica pura de área a área. Rompia linhas correndo de trás no Corinthians e na Seleção.",
  "Fernandinho": "Volante completo revelado no Athletico antes de virar peça de Guardiola no Manchester City.",
  "Andreas Pereira": "Meia de bom passe e chute de fora da área, reforço de peso do Flamengo.",
  "Willian Arão": "Volante versátil e regular, chegou a jogar de zagueiro — peça do Flamengo campeão.",
  "Thiago Maia": "Volante de muita pegada e boa saída, campeão pelo Flamengo e pelo Santos.",
  "Zé Rafael": "Volante de origem meia, muita chegada e gols de fora — pilar do Palmeiras.",
  "Patrick": "Meia de boa chegada e finalização, rodado por Internacional, São Paulo e Atlético-MG.",
  "Tinga": "Volante inteligente do Internacional bicampeão da Libertadores, também brilhou no Dortmund.",
  "Guiñazú": "Volante argentino carrapato, líder do meio-campo do Inter campeão da América.",
  "Fábio Rochemback": "Volante de lançamento preciso e chute forte, ídolo do Internacional.",
  "Diego Souza": "Meia-atacante de porte e faro de gol, artilheiro rodado por Sport, Botafogo e Grêmio.",
  "Alex Teixeira": "Meia veloz e goleador revelado no Vasco antes de explodir no Shakhtar.",
  "Lucas Silva": "Volante elegante de boa saída, revelado no Cruzeiro campeão antes do Real Madrid.",
  "Rodriguinho": "Meia de bom passe e chegada, destaque do Corinthians campeão brasileiro de 2017.",
  "Willian": "Ponta canhoto de dribles e chute colocado, revelado no Corinthians antes de Shakhtar e Chelsea.",
  "Aránguiz": "Volante chileno de muita técnica e marcação, craque do Inter e da seleção do Chile.",
  "Otávio": "Meia de boa técnica revelado no Athletico antes de brilhar no Porto.",
  "Camilo": "Meia de bom passe e bola parada, rodado por Botafogo, Corinthians e Vitória.",
  "Amoroso": "Gênio técnico e artilheiro. Brilhou no Guarani, no São Paulo e foi artilheiro da Bundesliga.",
  "Müller": "Ponta veloz e driblador, craque do São Paulo e da Seleção nos anos 80 e 90.",
  "Serginho Chulapa": "Centroavante raçudo e polêmico, maior artilheiro da história do São Paulo.",
  "Washington": "O Coração Valente. Parede na frente e superação que inspirou — artilheiro nato.",
  "Casagrande": "Centroavante técnico e símbolo da Democracia Corinthiana, parceiro de Sócrates.",
  "Viola": "O comemorador nato. Atacante folclórico do Corinthians, herói do título de 90.",
  "Loco Abreu": "O uruguaio da cavadinha. Carisma puro e gols de cobertura no Botafogo.",
  "Dodô": "O artilheiro dos gols bonitos. Finalizava de sem-pulo e cavadinha com maestria.",
  "Baltazar": "O Cabeça de Área. Centroavante artilheiro e oportunista, ídolo do Grêmio e do Corinthians.",
  "Kléber Gladiador": "Atacante raçudo e provocador, ídolo por Palmeiras, Cruzeiro e Portuguesa.",
  "Nunes": "Centroavante artilheiro do Flamengo campeão do mundo de 81, faro de gol nato.",
  "Grafite": "Fez história na Alemanha com um gol de calcanhar antológico humilhando o Bayern.",
  "Pedro": "O pivô clássico de futsal no campo. Domínio, giro rápido e faro de gol no Flamengo.",
  "Guerrero": "Centroavante peruano guerreiro e decisivo, ídolo do Corinthians e do Flamengo.",
  "Germán Cano": "Artilheiro argentino de faro absurdo. Renasceu e virou ídolo no Fluminense.",
  "Asprilla": "O colombiano imprevisível. Velocidade, dribles e loucura no Palmeiras.",
  "Barcos": "O Pirata. Faro de gol e comemoração icônica no Palmeiras.",
  "Miguel Borja": "Centroavante colombiano forte e finalizador, artilheiro pelo Palmeiras.",
  "Diego Tardelli": "Velocidade e inteligência. Recompunha e aparecia pra decidir no Atlético-MG.",
  "Emerson Sheik": "Atacante habilidoso e polêmico, ídolo do Corinthians campeão do mundo de 2012.",
  "Somália": "Atacante veloz e raçudo, artilheiro folclórico rodado pelo futebol carioca.",
  "Ricardo Oliveira": "Longevidade e faro de gol intactos. Técnico saindo da área e finalizador letal.",
  "Flávio Caça-Rato": "Ícone carismático do Santa Cruz. Gols decisivos e dancinhas de comemoração.",
  "Kerlon Foquinha": "O inventor do drible da foca — a firula que parou o Mineirão em 2007.",
  "Deivid": "Grande artilheiro, mas eternizado pelo gol inacreditável perdido sem goleiro em Fla-Vasco.",
  "Souza Caveirão": "O criador do chororô. Centroavante trombador e provocador do Flamengo.",
  "Val Baiano": "Atacante folclórico do Flamengo: badalado, fez só 3 gols em 18 jogos.",
  "Everton Cebolinha": "Ponta canhoto veloz e driblador, craque do Grêmio e da Seleção.",
  "Dudu": "Baixinho, veloz e driblador. Ídolo e multicampeão pelo Palmeiras.",
  "Rony": "O motorzinho tático. Dedicação incansável e gols de bicicleta no Palmeiras.",
  "Keno": "Ponta veloz e driblador, decisivo no Atlético-MG e no Palmeiras.",
  "Amaral": "Volante folclórico e carismático, cheio de causos e resenha. Campeão brasileiro de 98 pelo Corinthians.",
  "Aloísio Boi Bandido": "Boi Bandido! Raça e carisma que apaixonaram o Morumbi — 22 gols em 2013 pelo São Paulo.",
  "Aloísio Chulapa": "O Chulapa dos anos 2000. Centroavante brigador, campeão da Libertadores e do Mundial de 2005 pelo São Paulo.",
  "Walter Gordinho": "O Gordinho. Chegou fora de forma no Goiás e encantou mesmo assim — talento de sobra e o folclore eterno do andarilho da bola.",
  "Jobson": "Chegou como herói do Botafogo contra o rebaixamento em 2009, driblando todo mundo — puro talento e drama que viraram lenda.",
  "Zé Love": "Parceiro de base do Neymar no Santos, virou personagem folclórico do futebol (e até de reality show).",
  "Diego Alves": "Goleiro seguro e pegador de pênaltis. Auge no Valencia e no Flamengo campeão (2019-2022).",
  "Bruno": "Capitão e goleirão do Flamengo campeão de 2009 — auge curto e altíssimo, personagem controverso do futebol.",
  "Arce": "Lateral-direito paraguaio, potente e goleador. Ídolo do Palmeiras campeão da Libertadores de 1999.",
  "Apodi": "Lateral-ala veloz e carismático, rodou o Brasil inteiro — folclore puro do Brasileirão.",
  "Roque Júnior": "Zagueiro campeão da Libertadores pelo Palmeiras e do mundo pela Seleção em 2002.",
  "Deco": "Meia genial. Já veterano no Fluminense, seguia diferenciado — passe e visão de craque mundial.",
  "Elano": "Meia de passe refinado e bola parada mortal. Brilhou no Santos e no Grêmio.",
  "Felipe Melo": "O Pitbull. Volante raçudo e polêmico, líder do Palmeiras — personagem folclórico por excelência.",
  "Paulo Baier": "Meia de enorme longevidade e um dos maiores cobradores de falta e pênalti do país. Mais de 100 gols na Série A.",
  "Thiago Almada": "Meia argentino craque, campeão da Libertadores pelo Botafogo em 2024 — talento rumo à Europa.",
  "Luiz Henrique": "Ponta explosivo, protagonista do Botafogo campeão de 2024.",
  "Madson Cu de Nitro": "Lateral-direito veloz feito foguete — o apelido \"Cu de Nitro\" já é lenda da várzea à Série A.",
  "Léo Pelé": "Zagueiro/lateral do apelido pomposo — rodou Bahia, São Paulo e Vasco.",
  "Paulão": "Zagueirão raçudo e desengonçado que virou meme nacional — folclore puro da zaga.",
  "André Balada": "O Balada. Centroavante boêmio e de faro — passou por meio Brasil deixando história (e resenha).",
  "Henrique Dourado": "O Ceifador. Artilheiro do Brasileirão pelo Fluminense — a comemoração de foice virou marca registrada.",
  "Jael": "O Cruel. Centroavante bruto e decisivo — peça da Libertadores do Grêmio em 2017.",
  "Bill": "Matador silencioso de Série A e B — goleador raiz que fez fama pelo Nordeste e Sul.",
  "Sassá": "Explodiu no Botafogo com golaços — carisma e resenha de sobra.",
  "Sávio": "O Anjo Loiro. Ponta genial do Flamengo dos anos 90 — dribles e assistencias antes de brilhar no Real Madrid.",
  "Philippe Coutinho": "Joia da base do Vasco que foi cedo pra Europa e virou craque no Liverpool — magia canhota e chutes de fora.",
  "Vágner Love": "O Imperador do Amor. Centroavante veloz, técnico e artilheiro — brilhou pelo Palmeiras, Flamengo e Corinthians.",
  "França": "Centroavante matador do São Paulo entre 98 e 02 — artilheiro e goleador que era craque de verdade.",
  "Rayan Oi, Boa Noite": "Joia da base do Vasco vendida por 60 milhoes ao Bournemouth — e o hino da torcida (\"Rayan, oi, boa noite\") virou febre nacional.",
  "Alex Silva Pirulito": "Zagueiro do São Paulo tricampeão brasileiro (2006-08) — folclórico, marcado pelo apelido Pirulito.",
}

const GOL: C[] = [
  { name: "Gilmar", club: "Santos", year: 1962, fame: 5, lo: 93, hi: 97 },
  { name: "Taffarel", club: "Internacional", year: 1989, fame: 5, lo: 88, hi: 93 },
  { name: "Rogério Ceni", club: "São Paulo", year: 2005, fame: 5, lo: 89, hi: 94 },
  { name: "Marcos", club: "Palmeiras", year: 1999, fame: 4, lo: 86, hi: 92 },
  { name: "Dida", club: "Corinthians", year: 2000, fame: 4, lo: 85, hi: 92 },
  { name: "Fábio", club: "Cruzeiro", year: 2013, fame: 4, lo: 84, hi: 92 },
  { name: "Jefferson", club: "Botafogo", year: 2013, fame: 3, lo: 76, hi: 84 },
  { name: "Zetti", club: "São Paulo", year: 1993, fame: 3, lo: 77, hi: 84 },
  { name: "Carlos Germano", club: "Vasco", year: 1997, fame: 3, lo: 74, hi: 83 },
  { name: "Ronaldo Giovanelli", club: "Corinthians", year: 1990, fame: 2, lo: 62, hi: 81 },
  { name: "Velloso", club: "Palmeiras", year: 1994, fame: 1, lo: 61, hi: 78 },
  { name: "Sérgio", club: "Palmeiras", year: 1993, fame: 1, lo: 60, hi: 78 },
  { name: "Emerson Leão", club: "Palmeiras", year: 1974, fame: 4, lo: 87, hi: 93 },
  { name: "Félix", club: "Fluminense", year: 1970, fame: 3, lo: 80, hi: 84 },
  { name: "Júlio César", club: "Flamengo", year: 2003, fame: 3, lo: 78, hi: 84, promessa: true },
  { name: "Cássio", club: "Corinthians", year: 2012, fame: 4, lo: 83, hi: 91 },
  { name: "Weverton", club: "Palmeiras", year: 2019, fame: 3, lo: 78, hi: 84 },
  { name: "Victor", club: "Atlético-MG", year: 2013, fame: 3, lo: 76, hi: 84 },
  { name: "Danrlei", club: "Grêmio", year: 1997, fame: 2, lo: 62, hi: 82 },
  { name: "Aranha", club: "Santos", year: 2011, fame: 2, lo: 60, hi: 80 },
  { name: "Manga", club: "Botafogo", year: 1966, fame: 4, lo: 85, hi: 92, folk: true },
  { name: "Fábio Costa", club: "Santos", year: 2002, fame: 2, lo: 62, hi: 82 },
  { name: "Gatito Fernández", club: "Botafogo", year: 2017, fame: 2, lo: 64, hi: 82 },
  { name: "Alisson", club: "Internacional", year: 2015, fame: 3, lo: 78, hi: 84, promessa: true },
  { name: "Hélton", club: "Vasco", year: 2000, fame: 3, lo: 76, hi: 84 },
  { name: "Alex Muralha", club: "Flamengo", year: 2017, fame: 1, lo: 55, hi: 75 },
  { name: "Sidão", club: "São Paulo", year: 2017, fame: 1, lo: 54, hi: 74 },
  { name: "Diego Alves", club: "Flamengo", year: 2020, fame: 4, lo: 84, hi: 91 },
  { name: "Bruno", club: "Flamengo", year: 2009, fame: 2, lo: 66, hi: 82 },
  { name: "Fernando Prass", club: "Palmeiras", year: 2015, fame: 4, lo: 83, hi: 90 },
  { name: "Heurelho Gomes", club: "Cruzeiro", year: 2003, fame: 4, lo: 82, hi: 90 },
  { name: "Éverson", club: "Atlético-MG", year: 2021, fame: 3, lo: 78, hi: 85 },
  { name: "Vanderlei", club: "Santos", year: 2017, fame: 3, lo: 76, hi: 84 },
  { name: "Muriel", club: "Fluminense", year: 2012, fame: 3, lo: 74, hi: 83 },
  { name: "Sérgio Rochet", club: "Internacional", year: 2025, fame: 3, lo: 77, hi: 84 },
  { name: "Doni", club: "Corinthians", year: 2005, fame: 3, lo: 76, hi: 84 },
  { name: "Rafael Cabral", club: "Santos", year: 2011, fame: 3, lo: 74, hi: 82, promessa: true },
  { name: "Marcelo Lomba", club: "Internacional", year: 2019, fame: 2, lo: 64, hi: 82 },
  { name: "Harlei", club: "Goiás", year: 2005, fame: 2, lo: 62, hi: 82 },
  { name: "Magrão", club: "Sport", year: 2008, fame: 2, lo: 62, hi: 82 },
  { name: "Castilho", club: "Fluminense", year: 1960, fame: 5, lo: 90, hi: 95 },
  { name: "Deola", club: "Palmeiras", year: 2007, fame: 1, lo: 58, hi: 77 },
  { name: "Fernando Henrique", club: "Fluminense", year: 2010, fame: 1, lo: 60, hi: 79 },
  { name: "Vladimir", club: "Coritiba", year: 2011, fame: 1, lo: 58, hi: 77 },
  { name: "Raul Plassmann", club: "Cruzeiro", year: 1976, fame: 4, lo: 84, hi: 90 },
  { name: "Léo Jardim", club: "Vasco", year: 2024, fame: 3, lo: 77, hi: 84 },
  { name: "Hugo Neneca", club: "Corinthians", year: 2025, fame: 3, lo: 76, hi: 84 },
  { name: "Clemer", club: "Internacional", year: 2004, fame: 3, lo: 74, hi: 83 },
]

const LAT: C[] = [
  { name: "Carlos Alberto Torres", club: "Santos", year: 1970, fame: 5, lo: 95, hi: 99 },
  { name: "Nílton Santos", club: "Botafogo", year: 1958, fame: 5, lo: 95, hi: 99 },
  { name: "Cafu", club: "São Paulo", year: 1993, fame: 4, lo: 86, hi: 92 },
  { name: "Roberto Carlos", club: "Palmeiras", year: 1995, fame: 4, lo: 86, hi: 92 },
  { name: "Júnior Maestro", club: "Flamengo", year: 1981, fame: 5, lo: 93, hi: 97 },
  { name: "Leandro", club: "Flamengo", year: 1983, fame: 5, lo: 93, hi: 97 },
  { name: "Branco", club: "Fluminense", year: 1984, fame: 4, lo: 84, hi: 89 },
  { name: "Jorginho", club: "Flamengo", year: 1989, fame: 4, lo: 85, hi: 90 },
  { name: "Leonardo", club: "São Paulo", year: 1992, fame: 3, lo: 80, hi: 84 },
  { name: "Maicon", club: "Cruzeiro", year: 2003, fame: 3, lo: 78, hi: 84 },
  { name: "Belletti", club: "São Paulo", year: 2001, fame: 3, lo: 76, hi: 84 },
  { name: "Zé Maria", club: "Corinthians", year: 1974, fame: 3, lo: 78, hi: 84 },
  { name: "Cicinho", club: "São Paulo", year: 2005, fame: 2, lo: 63, hi: 82 },
  { name: "Athirson", club: "Flamengo", year: 1999, fame: 2, lo: 61, hi: 81 },
  { name: "Léo", club: "Santos", year: 2002, fame: 2, lo: 62, hi: 80 },
  { name: "Sorín", club: "Cruzeiro", year: 2001, fame: 3, lo: 76, hi: 84 },
  { name: "Djalma Santos", club: "Palmeiras", year: 1962, fame: 5, lo: 93, hi: 98 },
  { name: "Dani Alves", club: "São Paulo", year: 2019, fame: 3, lo: 78, hi: 84, promessa: true },
  { name: "Marcelo", club: "Fluminense", year: 2023, fame: 3, lo: 74, hi: 81, promessa: true },
  { name: "Marcos Rocha", club: "Palmeiras", year: 2019, fame: 3, lo: 76, hi: 84 },
  { name: "Fágner", club: "Corinthians", year: 2017, fame: 2, lo: 68, hi: 82 },
  { name: "Egídio", club: "Cruzeiro", year: 2015, fame: 2, lo: 62, hi: 79 },
  { name: "Filipe Luís", club: "Flamengo", year: 2019, fame: 4, lo: 84, hi: 90 },
  { name: "Léo Moura", club: "Flamengo", year: 2009, fame: 3, lo: 74, hi: 84 },
  { name: "Rafinha", club: "Flamengo", year: 2019, fame: 3, lo: 78, hi: 84 },
  { name: "Ceará", club: "Fluminense", year: 2012, fame: 2, lo: 62, hi: 80 },
  { name: "Alex Telles", club: "Grêmio", year: 2015, fame: 3, lo: 76, hi: 84 },
  { name: "Renê", club: "Flamengo", year: 2019, fame: 2, lo: 64, hi: 80 },
  { name: "Ayrton Lucas", club: "Flamengo", year: 2023, fame: 2, lo: 66, hi: 82 },
  { name: "Guga", club: "Atlético-MG", year: 2020, fame: 2, lo: 64, hi: 80 },
  { name: "Pará", club: "Fluminense", year: 2012, fame: 2, lo: 62, hi: 80, folk: true },
  { name: "Cortez", club: "Grêmio", year: 2018, fame: 2, lo: 62, hi: 79 },
  { name: "Rodinei", club: "Flamengo", year: 2019, fame: 2, lo: 62, hi: 80, folk: true },
  { name: "Isla", club: "Flamengo", year: 2020, fame: 2, lo: 66, hi: 82 },
  { name: "Wesley", club: "Flamengo", year: 2023, fame: 2, lo: 68, hi: 82 },
  { name: "Ruy Cabeção", club: "Grêmio", year: 2007, fame: 2, lo: 60, hi: 80, folk: true },
  { name: "Arce", club: "Palmeiras", year: 1999, fame: 4, lo: 85, hi: 91 },
  { name: "Apodi", club: "Fortaleza", year: 2018, fame: 2, lo: 64, hi: 82, folk: true },
  { name: "Madson Cu de Nitro", club: "Athletico-PR", year: 2020, fame: 1, lo: 56, hi: 78, folk: true },
]

const ZAG: C[] = [
  { name: "Domingos da Guia", club: "Flamengo", year: 1944, fame: 5, lo: 93, hi: 98 },
  { name: "Aldair", club: "Flamengo", year: 1987, fame: 3, lo: 78, hi: 84, promessa: true },
  { name: "Lúcio", club: "Internacional", year: 2000, fame: 4, lo: 86, hi: 92 },
  { name: "Thiago Silva", club: "Fluminense", year: 2008, fame: 4, lo: 84, hi: 90 },
  { name: "Luís Pereira", club: "Palmeiras", year: 1972, fame: 4, lo: 86, hi: 92 },
  { name: "Oscar", club: "São Paulo", year: 1980, fame: 3, lo: 80, hi: 84 },
  { name: "Ricardo Gomes", club: "Fluminense", year: 1987, fame: 4, lo: 84, hi: 90 },
  { name: "Antônio Carlos", club: "Palmeiras", year: 1993, fame: 3, lo: 78, hi: 84 },
  { name: "Juan", club: "Flamengo", year: 2000, fame: 4, lo: 82, hi: 90 },
  { name: "Edmílson", club: "São Paulo", year: 2000, fame: 3, lo: 77, hi: 84 },
  { name: "Mauro Galvão", club: "Vasco", year: 1997, fame: 3, lo: 76, hi: 84 },
  { name: "Júnior Baiano", club: "Palmeiras", year: 1996, fame: 2, lo: 60, hi: 84 },
  { name: "Chicão", club: "Corinthians", year: 2009, fame: 2, lo: 61, hi: 82 },
  { name: "Gamarra", club: "Corinthians", year: 1998, fame: 4, lo: 85, hi: 92 },
  { name: "Odvan", club: "Vasco", year: 1997, fame: 3, lo: 74, hi: 83 },
  { name: "Hilderaldo Bellini", club: "Vasco", year: 1958, fame: 5, lo: 87, hi: 92 },
  { name: "Miranda", club: "São Paulo", year: 2010, fame: 4, lo: 84, hi: 90 },
  { name: "Dedé", club: "Cruzeiro", year: 2014, fame: 3, lo: 78, hi: 84 },
  { name: "David Luiz", club: "Flamengo", year: 2021, fame: 3, lo: 76, hi: 84 },
  { name: "Lugano", club: "São Paulo", year: 2006, fame: 3, lo: 80, hi: 84 },
  { name: "Gustavo Gómez", club: "Palmeiras", year: 2021, fame: 3, lo: 78, hi: 84 },
  { name: "Réver", club: "Atlético-MG", year: 2013, fame: 2, lo: 70, hi: 82 },
  { name: "Geromel", club: "Grêmio", year: 2017, fame: 3, lo: 78, hi: 84 },
  { name: "Kannemann", club: "Grêmio", year: 2017, fame: 3, lo: 77, hi: 84 },
  { name: "Robson Bambu", club: "Vasco", year: 2023, fame: 1, lo: 55, hi: 76, folk: true },
  { name: "Pablo Marí", club: "Flamengo", year: 2019, fame: 2, lo: 72, hi: 84 },
  { name: "Adriano Gol Contra", club: "Madureira", year: 2005, fame: 1, lo: 50, hi: 74, folk: true },
  { name: "Rodrigo Caio", club: "Flamengo", year: 2019, fame: 3, lo: 78, hi: 84 },
  { name: "Fábio Luciano", club: "Corinthians", year: 2000, fame: 2, lo: 64, hi: 82 },
  { name: "Gil", club: "Corinthians", year: 2012, fame: 3, lo: 76, hi: 84 },
  { name: "Léo Ortiz", club: "Red Bull Bragantino", year: 2021, fame: 2, lo: 70, hi: 84 },
  { name: "Fabrício Bruno", club: "Flamengo", year: 2023, fame: 2, lo: 70, hi: 84 },
  { name: "Léo Pereira", club: "Flamengo", year: 2021, fame: 2, lo: 68, hi: 83 },
  { name: "Nino", club: "Fluminense", year: 2021, fame: 3, lo: 74, hi: 84 },
  { name: "Vitão", club: "Internacional", year: 2022, fame: 2, lo: 68, hi: 83 },
  { name: "Manoel", club: "Cruzeiro", year: 2017, fame: 2, lo: 66, hi: 82 },
  { name: "Anderson Martins", club: "Vasco", year: 2018, fame: 2, lo: 64, hi: 81 },
  { name: "Lucas Veríssimo", club: "Santos", year: 2020, fame: 2, lo: 68, hi: 83 },
  { name: "Marquinhos", club: "Corinthians", year: 2012, fame: 3, lo: 76, hi: 83, promessa: true },
  { name: "Éder Militão", club: "São Paulo", year: 2018, fame: 3, lo: 76, hi: 82, promessa: true },
  { name: "Roque Júnior", club: "Palmeiras", year: 1999, fame: 4, lo: 84, hi: 90 },
  { name: "Léo Pelé", club: "São Paulo", year: 2023, fame: 1, lo: 56, hi: 77, folk: true },
  { name: "Paulão", club: "Vasco", year: 2011, fame: 1, lo: 55, hi: 77, folk: true },
  { name: "Alex Silva Pirulito", club: "São Paulo", year: 2006, fame: 1, lo: 56, hi: 78, folk: true },
]

const MEI: C[] = [
  { name: "Zico", club: "Flamengo", year: 1981, fame: 5, lo: 95, hi: 99 },
  { name: "Didi", club: "Botafogo", year: 1958, fame: 5, lo: 94, hi: 98 },
  { name: "Rivelino", club: "Corinthians", year: 1972, fame: 5, lo: 93, hi: 97 },
  { name: "Sócrates", club: "Corinthians", year: 1983, fame: 5, lo: 93, hi: 97 },
  { name: "Ronaldinho Gaúcho", club: "Grêmio", year: 1999, fame: 4, lo: 87, hi: 93 },
  { name: "Ademir da Guia", club: "Palmeiras", year: 1972, fame: 4, lo: 87, hi: 93 },
  { name: "Falcão", club: "Internacional", year: 1979, fame: 5, lo: 92, hi: 96 },
  { name: "Gérson Canhotinha de Ouro", club: "Botafogo", year: 1970, fame: 5, lo: 92, hi: 96 },
  { name: "Rivaldo", club: "Palmeiras", year: 1996, fame: 4, lo: 86, hi: 92 },
  { name: "Kaká", club: "São Paulo", year: 2003, fame: 3, lo: 80, hi: 86, promessa: true },
  { name: "Raí", club: "São Paulo", year: 1992, fame: 4, lo: 87, hi: 93 },
  { name: "Cerezo", club: "Atlético-MG", year: 1980, fame: 4, lo: 85, hi: 91 },
  { name: "Dunga", club: "Internacional", year: 1984, fame: 4, lo: 84, hi: 90 },
  { name: "Juninho Pernambucano", club: "Vasco", year: 1997, fame: 4, lo: 86, hi: 92 },
  { name: "Zinho", club: "Palmeiras", year: 1994, fame: 3, lo: 78, hi: 84 },
  { name: "Alex", club: "Cruzeiro", year: 2003, fame: 4, lo: 86, hi: 92 },
  { name: "Djalminha", club: "Palmeiras", year: 1996, fame: 4, lo: 82, hi: 91, folk: true },
  { name: "Marcelinho Carioca", club: "Corinthians", year: 1995, fame: 4, lo: 90, hi: 95, folk: true },
  { name: "Edílson", club: "Corinthians", year: 1998, fame: 2, lo: 62, hi: 84 },
  { name: "Petkovic", club: "Fluminense", year: 2002, fame: 4, lo: 85, hi: 92, folk: true },
  { name: "Dario Conca", club: "Fluminense", year: 2010, fame: 2, lo: 63, hi: 82 },
  { name: "Paulo Henrique Ganso", club: "Santos", year: 2010, fame: 2, lo: 60, hi: 82 },
  { name: "Felipe", club: "Vasco", year: 2000, fame: 2, lo: 61, hi: 81 },
  { name: "PC Caju", club: "Botafogo", year: 1968, fame: 2, lo: 63, hi: 83 },
  { name: "Ramires", club: "Cruzeiro", year: 2008, fame: 2, lo: 60, hi: 79 },
  { name: "Clodoaldo", club: "Santos", year: 1970, fame: 4, lo: 85, hi: 92 },
  { name: "Juninho Paulista", club: "São Paulo", year: 2009, fame: 3, lo: 79, hi: 84 },
  { name: "Zé Roberto", club: "Palmeiras", year: 2010, fame: 3, lo: 82, hi: 84 },
  { name: "Rincón", club: "Corinthians", year: 1998, fame: 4, lo: 84, hi: 91 },
  { name: "Arrascaeta", club: "Flamengo", year: 2022, fame: 4, lo: 84, hi: 91 },
  { name: "Mascherano", club: "Corinthians", year: 2005, fame: 3, lo: 80, hi: 84 },
  { name: "Renato Augusto", club: "Corinthians", year: 2018, fame: 3, lo: 78, hi: 84 },
  { name: "Diego", club: "Flamengo", year: 2019, fame: 3, lo: 78, hi: 84, promessa: true },
  { name: "Everton Ribeiro", club: "Flamengo", year: 2020, fame: 3, lo: 76, hi: 84 },
  { name: "Montillo", club: "Cruzeiro", year: 2012, fame: 2, lo: 70, hi: 84 },
  { name: "Valdivia", club: "Palmeiras", year: 2013, fame: 2, lo: 60, hi: 84, folk: true },
  { name: "Vampeta", club: "Corinthians", year: 1999, fame: 2, lo: 62, hi: 82, folk: true },
  { name: "Marcelinho Paraíba", club: "Corinthians", year: 2002, fame: 2, lo: 62, hi: 83 },
  { name: "Neto", club: "Corinthians", year: 1990, fame: 4, lo: 84, hi: 91 },
  { name: "Denílson", club: "São Paulo", year: 1996, fame: 3, lo: 74, hi: 84 },
  { name: "Biro-Biro", club: "Corinthians", year: 1983, fame: 3, lo: 76, hi: 84, folk: true },
  { name: "Beto Cachaça", club: "Botafogo", year: 1995, fame: 2, lo: 62, hi: 82, folk: true },
  { name: "Perdigão", club: "Internacional", year: 2006, fame: 1, lo: 55, hi: 75, folk: true },
  { name: "Walter Minhoca", club: "Flamengo", year: 2006, fame: 1, lo: 50, hi: 72, folk: true },
  { name: "Paulinho", club: "Corinthians", year: 2012, fame: 4, lo: 82, hi: 90 },
  { name: "Hernanes", club: "São Paulo", year: 2009, fame: 3, lo: 78, hi: 84 },
  { name: "Thiago Neves", club: "Fluminense", year: 2008, fame: 4, lo: 83, hi: 90 },
  { name: "Nenê", club: "Vasco", year: 2018, fame: 3, lo: 76, hi: 84 },
  { name: "Gerson", club: "Flamengo", year: 2019, fame: 3, lo: 78, hi: 84 },
  { name: "Gustavo Scarpa", club: "Palmeiras", year: 2021, fame: 3, lo: 76, hi: 84 },
  { name: "Raphael Veiga", club: "Palmeiras", year: 2021, fame: 3, lo: 76, hi: 84 },
  { name: "Lucas Lima", club: "Santos", year: 2015, fame: 3, lo: 76, hi: 84 },
  { name: "Jadson", club: "Corinthians", year: 2015, fame: 3, lo: 75, hi: 84 },
  { name: "Elias", club: "Corinthians", year: 2010, fame: 3, lo: 74, hi: 84 },
  { name: "Fernandinho", club: "Atlético-PR", year: 2004, fame: 3, lo: 76, hi: 84 },
  { name: "Andreas Pereira", club: "Flamengo", year: 2023, fame: 3, lo: 74, hi: 84 },
  { name: "Willian Arão", club: "Flamengo", year: 2019, fame: 2, lo: 70, hi: 82 },
  { name: "D'Alessandro", club: "Internacional", year: 2010, fame: 4, lo: 84, hi: 91 },
  { name: "Tinga", club: "Internacional", year: 2006, fame: 2, lo: 70, hi: 82 },
  { name: "Guiñazú", club: "Internacional", year: 2010, fame: 2, lo: 70, hi: 82 },
  { name: "Fábio Rochemback", club: "Internacional", year: 2008, fame: 2, lo: 70, hi: 83 },
  { name: "Diego Souza", club: "Sport", year: 2018, fame: 3, lo: 74, hi: 84 },
  { name: "Alex Teixeira", club: "Vasco", year: 2010, fame: 2, lo: 70, hi: 84 },
  { name: "Willian", club: "Corinthians", year: 2006, fame: 3, lo: 76, hi: 84 },
  { name: "Aránguiz", club: "Internacional", year: 2015, fame: 3, lo: 74, hi: 84 },
  { name: "Camilo", club: "Botafogo", year: 2015, fame: 2, lo: 68, hi: 82 },
  { name: "Casemiro", club: "São Paulo", year: 2012, fame: 3, lo: 73, hi: 80, promessa: true },
  { name: "Bruno Guimarães", club: "Athletico-PR", year: 2019, fame: 3, lo: 76, hi: 82, promessa: true },
  { name: "Lucas Paquetá", club: "Flamengo", year: 2018, fame: 3, lo: 78, hi: 84 },
  { name: "João Gomes", club: "Flamengo", year: 2022, fame: 2, lo: 72, hi: 84 },
  { name: "Amaral", club: "Corinthians", year: 1998, fame: 2, lo: 64, hi: 82, folk: true },
  { name: "Márcio Araújo", club: "Flamengo", year: 2015, fame: 2, lo: 66, hi: 82, folk: true },
  { name: "Seedorf", club: "Botafogo", year: 2013, fame: 4, lo: 85, hi: 90 },
  { name: "Adílio", club: "Flamengo", year: 1981, fame: 4, lo: 87, hi: 93 },
  { name: "Fernando Diniz", club: "Fluminense", year: 2001, fame: 2, lo: 64, hi: 82, folk: true },
  { name: "James Rodríguez", club: "São Paulo", year: 2023, fame: 3, lo: 68, hi: 80 },
  { name: "Deco", club: "Fluminense", year: 2011, fame: 4, lo: 82, hi: 90 },
  { name: "Elano", club: "Santos", year: 2009, fame: 4, lo: 84, hi: 91 },
  { name: "Felipe Melo", club: "Palmeiras", year: 2017, fame: 4, lo: 83, hi: 91, folk: true },
  { name: "Paulo Baier", club: "Goiás", year: 2005, fame: 4, lo: 84, hi: 91 },
  { name: "Thiago Almada", club: "Botafogo", year: 2024, fame: 3, lo: 74, hi: 82, promessa: true },
  { name: "Philippe Coutinho", club: "Vasco", year: 2009, fame: 3, lo: 74, hi: 82, promessa: true },
]

const ATA: C[] = [
  { name: "Clodoaldo Matador", club: "Fortaleza", year: 2004, fame: 1, lo: 58, hi: 78, folk: true },
  { name: "Pelé", club: "Santos", year: 1962, fame: 5, lo: 97, hi: 99 },
  { name: "Garrincha", club: "Botafogo", year: 1958, fame: 5, lo: 95, hi: 99 },
  { name: "Romário", club: "Vasco", year: 2000, fame: 5, lo: 94, hi: 98 },
  { name: "Ronaldo", club: "Cruzeiro", year: 1993, fame: 4, lo: 87, hi: 93 },
  { name: "Neymar", club: "Santos", year: 2011, fame: 5, lo: 91, hi: 96 },
  { name: "Tostão", club: "Cruzeiro", year: 1970, fame: 4, lo: 89, hi: 95 },
  { name: "Jairzinho", club: "Botafogo", year: 1970, fame: 5, lo: 93, hi: 97 },
  { name: "Bebeto", club: "Vasco", year: 1989, fame: 4, lo: 87, hi: 93 },
  { name: "Careca", club: "São Paulo", year: 1986, fame: 4, lo: 86, hi: 92 },
  { name: "Reinaldo", club: "Atlético-MG", year: 1977, fame: 4, lo: 87, hi: 93 },
  { name: "Robinho", club: "Santos", year: 2002, fame: 4, lo: 85, hi: 92 },
  { name: "Adriano", club: "Flamengo", year: 2009, fame: 4, lo: 85, hi: 92 },
  { name: "Edmundo", club: "Vasco", year: 1997, fame: 4, lo: 80, hi: 91, folk: true },
  { name: "Evair", club: "Palmeiras", year: 1993, fame: 3, lo: 79, hi: 84 },
  { name: "Amoroso", club: "Guarani", year: 1994, fame: 3, lo: 78, hi: 84 },
  { name: "Müller", club: "São Paulo", year: 1991, fame: 3, lo: 79, hi: 84 },
  { name: "Serginho Chulapa", club: "São Paulo", year: 1982, fame: 3, lo: 78, hi: 84 },
  { name: "Fred", club: "Fluminense", year: 2012, fame: 4, lo: 85, hi: 91 },
  { name: "Washington", club: "Atlético-PR", year: 2004, fame: 3, lo: 76, hi: 84 },
  { name: "Casagrande", club: "Corinthians", year: 1982, fame: 3, lo: 77, hi: 84 },
  { name: "Túlio Maravilha", club: "Botafogo", year: 1995, fame: 4, lo: 85, hi: 91, folk: true },
  { name: "Viola", club: "Corinthians", year: 1990, fame: 2, lo: 60, hi: 83, folk: true },
  { name: "Obina", club: "Flamengo", year: 2005, fame: 2, lo: 55, hi: 82, folk: true },
  { name: "Loco Abreu", club: "Botafogo", year: 2010, fame: 2, lo: 60, hi: 82, folk: true },
  { name: "Dadá Maravilha", club: "Atlético-MG", year: 1971, fame: 2, lo: 60, hi: 84, folk: true },
  { name: "Dodô", club: "São Paulo", year: 1997, fame: 2, lo: 61, hi: 82 },
  { name: "Kléber Gladiador", club: "Palmeiras", year: 2010, fame: 2, lo: 57, hi: 79 },
  { name: "Zizinho", club: "Flamengo", year: 1950, fame: 5, lo: 92, hi: 97 },
  { name: "Leônidas da Silva", club: "Flamengo", year: 1938, fame: 5, lo: 92, hi: 97 },
  { name: "Vavá", club: "Vasco", year: 1958, fame: 4, lo: 86, hi: 93 },
  { name: "Roberto Dinamite", club: "Vasco", year: 1980, fame: 4, lo: 86, hi: 93 },
  { name: "Nunes", club: "Flamengo", year: 1981, fame: 3, lo: 76, hi: 84 },
  { name: "Renato Gaúcho", club: "Grêmio", year: 1983, fame: 4, lo: 84, hi: 92, folk: true },
  { name: "Hulk", club: "Atlético-MG", year: 2021, fame: 4, lo: 84, hi: 91 },
  { name: "Luís Fabiano", club: "São Paulo", year: 2008, fame: 4, lo: 86, hi: 92 },
  { name: "Grafite", club: "São Paulo", year: 2008, fame: 3, lo: 78, hi: 84 },
  { name: "Gabigol", club: "Flamengo", year: 2019, fame: 4, lo: 86, hi: 92 },
  { name: "Pedro", club: "Flamengo", year: 2022, fame: 3, lo: 78, hi: 84 },
  { name: "Guerrero", club: "Corinthians", year: 2013, fame: 3, lo: 80, hi: 84 },
  { name: "Germán Cano", club: "Fluminense", year: 2022, fame: 3, lo: 78, hi: 84 },
  { name: "Asprilla", club: "Palmeiras", year: 2001, fame: 2, lo: 68, hi: 84 },
  { name: "Barcos", club: "Palmeiras", year: 2012, fame: 2, lo: 70, hi: 84 },
  { name: "Miguel Borja", club: "Palmeiras", year: 2017, fame: 2, lo: 66, hi: 83 },
  { name: "Diego Tardelli", club: "Atlético-MG", year: 2014, fame: 2, lo: 70, hi: 84 },
  { name: "Emerson Sheik", club: "Corinthians", year: 2012, fame: 2, lo: 65, hi: 83 },
  { name: "Deyverson", club: "Palmeiras", year: 2018, fame: 2, lo: 55, hi: 83, folk: true },
  { name: "Somália", club: "Botafogo", year: 2016, fame: 1, lo: 55, hi: 78, folk: true },
  { name: "Ricardo Oliveira", club: "Santos", year: 2015, fame: 3, lo: 77, hi: 84 },
  { name: "Flávio Caça-Rato", club: "Santa Cruz", year: 2013, fame: 2, lo: 58, hi: 80, folk: true },
  { name: "Kerlon Foquinha", club: "Cruzeiro", year: 2007, fame: 2, lo: 55, hi: 82, folk: true },
  { name: "Deivid", club: "Flamengo", year: 2012, fame: 1, lo: 55, hi: 78, folk: true },
  { name: "Souza Caveirão", club: "Flamengo", year: 2007, fame: 1, lo: 54, hi: 78, folk: true },
  { name: "Val Baiano", club: "Flamengo", year: 2010, fame: 1, lo: 52, hi: 76, folk: true },
  { name: "Bruno Henrique", club: "Flamengo", year: 2019, fame: 4, lo: 86, hi: 91 },
  { name: "Everton Cebolinha", club: "Grêmio", year: 2019, fame: 3, lo: 78, hi: 84 },
  { name: "Dudu", club: "Palmeiras", year: 2018, fame: 3, lo: 76, hi: 84 },
  { name: "Rony", club: "Palmeiras", year: 2021, fame: 2, lo: 70, hi: 83 },
  { name: "Keno", club: "Atlético-MG", year: 2021, fame: 2, lo: 70, hi: 83 },
  { name: "Vinicius Jr", club: "Flamengo", year: 2018, fame: 3, lo: 76, hi: 82, promessa: true },
  { name: "Rodrygo", club: "Santos", year: 2018, fame: 3, lo: 72, hi: 80, promessa: true },
  { name: "Gabriel Jesus", club: "Palmeiras", year: 2016, fame: 3, lo: 74, hi: 81, promessa: true },
  { name: "Richarlison Pombo", club: "Fluminense", year: 2016, fame: 3, lo: 76, hi: 83, promessa: true },
  { name: "Endrick", club: "Palmeiras", year: 2023, fame: 3, lo: 70, hi: 79, promessa: true },
  { name: "Antony", club: "São Paulo", year: 2020, fame: 2, lo: 70, hi: 80 },
  { name: "Vitor Roque", club: "Athletico-PR", year: 2023, fame: 2, lo: 70, hi: 81 },
  { name: "Yuri Alberto", club: "Corinthians", year: 2023, fame: 2, lo: 70, hi: 82 },
  { name: "Alecsandro", club: "Atlético-MG", year: 2013, fame: 3, lo: 73, hi: 84, folk: true },
  { name: "Marta", club: "Santos", year: 2010, fame: 4, lo: 84, hi: 89 },
  { name: "Hernane Brocador", club: "Flamengo", year: 2013, fame: 2, lo: 62, hi: 81, folk: true },
  { name: "Jorge Henrique", club: "Corinthians", year: 2011, fame: 2, lo: 66, hi: 82, folk: true },
  { name: "Ribamar", club: "Botafogo", year: 2016, fame: 1, lo: 50, hi: 76, folk: true },
  { name: "Chay", club: "Botafogo", year: 2021, fame: 1, lo: 52, hi: 76, folk: true },
  { name: "Lincoln", club: "Flamengo", year: 2019, fame: 1, lo: 40, hi: 72, folk: true },
  { name: "Negueba", club: "Flamengo", year: 2012, fame: 1, lo: 50, hi: 76, folk: true },
  { name: "Michael", club: "Flamengo", year: 2020, fame: 2, lo: 70, hi: 84 },
  { name: "Estêvão", club: "Palmeiras", year: 2024, fame: 3, lo: 72, hi: 80, promessa: true },
  { name: "Tevez", club: "Corinthians", year: 2005, fame: 4, lo: 87, hi: 93 },
  { name: "Depay", club: "Corinthians", year: 2024, fame: 3, lo: 74, hi: 82 },
  { name: "Jô", club: "Corinthians", year: 2015, fame: 3, lo: 74, hi: 84, folk: true },
  { name: "Dimba", club: "Goiás", year: 2003, fame: 2, lo: 60, hi: 82, folk: true },
  { name: "Josiel", club: "Paraná", year: 2007, fame: 2, lo: 58, hi: 80, folk: true },
  { name: "Dinei", club: "Corinthians", year: 1999, fame: 2, lo: 58, hi: 80, folk: true },
  { name: "Suárez", club: "Grêmio", year: 2023, fame: 4, lo: 82, hi: 88 },
  { name: "Igor Thiago", club: "Cruzeiro", year: 2020, fame: 3, lo: 74, hi: 84 },
  { name: "Yago Pikachu", club: "Fortaleza", year: 2021, fame: 2, lo: 66, hi: 83, folk: true },
  { name: "Zagallo", club: "Botafogo", year: 1962, fame: 5, lo: 92, hi: 97 },
  { name: "Igor Catatau", club: "Vasco", year: 2020, fame: 1, lo: 52, hi: 75, folk: true },
  { name: "Dener", club: "Vasco", year: 1991, fame: 4, lo: 86, hi: 94 },
  { name: "Aloísio Boi Bandido", club: "São Paulo", year: 2013, fame: 2, lo: 66, hi: 83, folk: true },
  { name: "Aloísio Chulapa", club: "São Paulo", year: 2005, fame: 2, lo: 68, hi: 84, folk: true },
  { name: "Walter Gordinho", club: "Goiás", year: 2012, fame: 1, lo: 55, hi: 78, folk: true },
  { name: "Jobson", club: "Botafogo", year: 2009, fame: 1, lo: 55, hi: 78, folk: true },
  { name: "Zé Love", club: "Santos", year: 2010, fame: 1, lo: 52, hi: 78, folk: true },
  { name: "Luiz Henrique", club: "Botafogo", year: 2024, fame: 3, lo: 76, hi: 83, promessa: true },
  { name: "André Balada", club: "Santos", year: 2010, fame: 1, lo: 58, hi: 78, folk: true },
  { name: "Henrique Dourado", club: "Fluminense", year: 2017, fame: 1, lo: 58, hi: 78, folk: true },
  { name: "Jael", club: "Grêmio", year: 2017, fame: 1, lo: 56, hi: 77, folk: true },
  { name: "Bill", club: "Ceará", year: 2018, fame: 1, lo: 54, hi: 76, folk: true },
  { name: "Sassá", club: "Botafogo", year: 2016, fame: 1, lo: 56, hi: 77, folk: true },
  { name: "Sávio", club: "Flamengo", year: 1997, fame: 4, lo: 83, hi: 90 },
  { name: "Vágner Love", club: "Palmeiras", year: 2004, fame: 4, lo: 85, hi: 91 },
  { name: "França", club: "São Paulo", year: 2000, fame: 4, lo: 84, hi: 90 },
  { name: "Rayan Oi, Boa Noite", club: "Vasco", year: 2025, fame: 3, lo: 77, hi: 84, promessa: true },
]

export const CATALOG: Record<Sector, C[]> = { GOL, LAT, ZAG, MEI, ATA }

// nomes marcados como PROMESSA (5º tier) — usado no álbum quando o flag não vem no dado
export const PROMESSA_SET = new Set(Object.values(CATALOG).flat().filter(c => c.promessa).map(c => c.name))

// ─── Incógnitas: SÓ como último recurso, quando o catálogo real de uma
// posição se esgota (salas online gigantes, com muitos bots preenchendo
// a tabela, precisam de mais gente do que os jogadores reais que temos).
// Nunca aparecem no leilão dos humanos — o baralho do leilão é montado
// primeiro, então pega os reais antes dos bots. Algumas escondem joias.
const INC_FIRST = ['Valdir', 'Josimar', 'Cleiton', 'Ednaldo', 'Wanderson', 'Gonçalves', 'Íris', 'Baltemar', 'Osmarino', 'Delei', 'Nivaldo', 'Juraci', 'Aloísio', 'Ademilson', 'Zé Roberto', 'Toninho', 'Gersinho', 'Maurício', 'Índio', 'Fumagalli']
const INC_NICK = ['da Ilha', 'Perna Torta', 'Bola Sete', 'do Sertão', 'Trovoada', 'Canela Fina', 'Pé de Ferro', 'Maestro', 'Furacão', 'da Baixada', 'Gaúcho', 'Paraíba', 'Matuto', 'Serrano', 'do Brejo', 'Cigano', 'Foguete', 'Peixe Frito', 'da Várzea', 'Bicudo']
const INC_CLUBS = ['Operário', 'Treze', 'Caldense', 'Ypiranga', 'Ferroviário', 'Uberlândia', 'Anapolina', 'Itabaiana', 'River-PI', 'Sergipe', 'Central-PE', 'Mixto', 'Rio Branco', 'Olaria', 'Bangu', 'Portuguesa', 'Inter de Limeira', 'União São João', 'Tuna Luso', 'XV de Piracicaba']

export function makeIncognita(pos: Sector, idx: number, gem: boolean, rng: () => number): Card {
  const lo = gem ? 72 + Math.floor(rng() * 6) : 46 + Math.floor(rng() * 12)
  const width = 12 + Math.floor(rng() * 7)
  const hi = Math.min(93, lo + width)
  const name = `${INC_FIRST[Math.floor(rng() * INC_FIRST.length)]} ${INC_NICK[Math.floor(rng() * INC_NICK.length)]}`
  const club = INC_CLUBS[Math.floor(rng() * INC_CLUBS.length)]
  const year = 1968 + Math.floor(rng() * 40)
  return { id: `inc-${pos}-${idx}`, name, club, year, pos, fame: 1, lo, hi }
}

// ─── Nomes de técnicos CPU e times ───────────────────────────────────
export const CPU_MANAGERS = [
  { name: 'Tonhão', team: 'Tonhão FC' },
  { name: 'PC Magrão', team: 'Magrão EC' },
  { name: 'Biriba', team: 'Biriba United' },
  { name: 'Dona Cida', team: 'Cida Futebol' },
  { name: 'Serjão', team: 'Serjão SAF' },
  { name: 'Marcão Pelado', team: 'Pelado FR' },
  { name: 'Régis da Vila', team: 'Vila Régis' },
  { name: 'Neguinho do Apito', team: 'Apito Final' },
  { name: 'Zé do Caixote', team: 'Caixote EC' },
  { name: 'Dedé Bigode', team: 'Bigode FC' },
  { name: 'Adãozinho', team: 'Adão Esporte' },
  { name: 'Cabeção da Vila', team: 'Cabeção FR' },
  { name: 'Duda Fortuna', team: 'Fortuna SAF' },
  { name: 'Miúdo do Gol', team: 'Miúdo EC' },
  { name: 'Painitto', team: 'Painitto FC' },
  { name: 'Robertão', team: 'Robertão United' },
  { name: 'Sinhozinho', team: 'Sinhô Futebol' },
  { name: 'Tico do Bar', team: 'Tico do Bar FR' },
  { name: 'Xandão da Bola', team: 'Xandão EC' },
  { name: 'Zequinha Ferro', team: 'Zequinha SAF' },
  { name: 'Waguinho Pipa', team: 'Pipa FC' },
]

// ─── Clubes clássicos que completam a liga de 20 ─────────────────────
export const CLASSIC_CLUBS: { name: string; atk: number; def: number }[] = [
  { name: 'Ferroviária do Vale', atk: 78, def: 76 },
  { name: 'Athletico do Porto', atk: 76, def: 78 },
  { name: 'Nacional da Serra', atk: 75, def: 73 },
  { name: 'Esporte do Cerrado', atk: 73, def: 75 },
  { name: 'União da Baixada', atk: 72, def: 71 },
  { name: 'Marítimo do Recôncavo', atk: 70, def: 72 },
  { name: 'Guarani do Agreste', atk: 70, def: 68 },
  { name: 'Comercial das Gerais', atk: 68, def: 70 },
  { name: 'Ipiranga da Fronteira', atk: 67, def: 66 },
  { name: 'Estrela do Pantanal', atk: 65, def: 67 },
  { name: 'Operário das Docas', atk: 64, def: 65 },
  { name: 'Botafogo da Colônia', atk: 63, def: 62 },
  { name: 'Fluminense de Caicó', atk: 61, def: 63 },
  { name: 'Atlético Seringueiro', atk: 60, def: 60 },
  { name: 'Real Tabuleiro', atk: 58, def: 59 },
  { name: 'Íbis da Mata', atk: 55, def: 54 },
]
