// 🏀 BARALHO DO BIDLEGENDS (NBA) — Lote 1 + Lote HOF (Hall da Fama)
//
// Espelha o baralho do futebol (`data.ts`), mas cada carta já nasce BILÍNGUE
// (bioPt + bioEn) porque o basquete é internacional. Mesma régua de nível:
//   fame 5 = 👑 LENDA · 4 = ⭐ CRAQUE · 3/2 = 🎯 BOM · 1 = 🪵 FOI PROFISSIONAL
//   promessa:true = 💎 PROMESSA (auge ainda de promessa) · folk:true = 🃏 (vibe)
// `lo/hi` = faixa de overall (baixo/alto) no dia — igual ao futebol.
//
// Nível = auge NAQUELE ano/franquia (Jordan Bulls 1996 lenda; Wade Heat 2006).
// Arquivo self-contained (sem imports) pra facilitar prévia/teste antes do motor.
//
// 5 posições mapeiam 1:1 nos 5 setores do leilão:
//   PG armador · SG ala-armador · SF ala · PF ala-pivô · C pivô.

export type BPos = 'PG' | 'SG' | 'SF' | 'PF' | 'C'
export type BFame = 1 | 2 | 3 | 4 | 5

export type BC = {
  name: string; club: string; year: number
  fame: BFame; lo: number; hi: number
  bioPt: string; bioEn: string
  folk?: boolean; promessa?: boolean
}

// nome cheio de cada posição (título da rodada de pregão) — bilíngue. O código
// curto (PG/SG/SF/PF/C) é padrão NBA e serve nas duas línguas, vai direto na carta.
export const BPOS_LABEL: Record<BPos, { pt: string; en: string }> = {
  PG: { pt: 'Armador', en: 'Point Guard' },
  SG: { pt: 'Ala-armador', en: 'Shooting Guard' },
  SF: { pt: 'Ala', en: 'Small Forward' },
  PF: { pt: 'Ala-pivô', en: 'Power Forward' },
  C: { pt: 'Pivô', en: 'Center' },
}

// ─── PG · ARMADOR ────────────────────────────────────────────────────
const PG: BC[] = [
  { name: 'Magic Johnson', club: 'Lakers', year: 1987, fame: 5, lo: 90, hi: 97, bioPt: 'Showtime em pessoa: 2,06m de armador que enxergava o passe antes de todo mundo. 5 anéis.', bioEn: 'Showtime in the flesh: a 6\'9" point guard who saw the pass before anyone. 5 rings.' },
  { name: 'Stephen Curry', club: 'Warriors', year: 2016, fame: 5, lo: 90, hi: 97, bioPt: 'Quebrou a NBA de três. MVP unânime e mira de outro planeta lá do meio da quadra.', bioEn: 'Broke the NBA from deep. Unanimous MVP with logo-range aim from another planet.' },
  { name: 'Isiah Thomas', club: 'Pistons', year: 1989, fame: 5, lo: 88, hi: 94, bioPt: 'O baixinho durão dos Bad Boys. Sorriso de anjo, jogo de bandido. Bicampeão.', bioEn: 'The tough little floor general of the Bad Boys. Angel smile, villain game. Back-to-back champ.' },
  { name: 'Allen Iverson', club: 'Sixers', year: 2001, fame: 4, lo: 86, hi: 93, bioPt: '1,83m que atravessava gigantes. "We talking about practice?" MVP de puro coração.', bioEn: 'Six-foot flat, crossing over giants. "We talking about practice?" An MVP of pure heart.' },
  { name: 'Steve Nash', club: 'Suns', year: 2005, fame: 4, lo: 85, hi: 92, bioPt: 'Cabelo no rosto, passe nas costas. Dois MVPs correndo o "sete segundos ou menos".', bioEn: 'Hair in the face, no-look dimes. Two MVPs running seven-seconds-or-less.' },
  { name: 'John Stockton', club: 'Jazz', year: 1990, fame: 4, lo: 84, hi: 91, bioPt: 'Rei eterno das assistências e dos roubos. Shortinho curto e sacanagem no pick-and-roll.', bioEn: 'All-time king of assists and steals — forever. Tiny shorts, deadly pick-and-roll.' },
  { name: 'Damian Lillard', club: 'Blazers', year: 2019, fame: 4, lo: 84, hi: 91, bioPt: 'Dame Time. Acenou tchau pro OKC do meio da quadra e foi embora de boa.', bioEn: 'Dame Time. Waved goodbye to OKC from the logo and strolled off.' },
  { name: 'Chris Paul', club: 'Hornets', year: 2008, fame: 4, lo: 84, hi: 90, bioPt: 'O Point God. Controla o jogo no relógio e reclama com o árbitro em dobro.', bioEn: 'The Point God. Runs the game on a clock and argues with refs twice as hard.' },
  { name: 'Kyrie Irving', club: 'Cavaliers', year: 2016, fame: 4, lo: 84, hi: 91, bioPt: 'Drible de outra dimensão e a bola de 3 que calou os Warriors em 2016.', bioEn: 'Handles from another dimension and the 2016 dagger three that silenced the Warriors.' },
  { name: 'Ja Morant', club: 'Grizzlies', year: 2022, fame: 3, lo: 78, hi: 88, promessa: true, bioPt: 'Voa mais alto do que armador tem direito. Pura eletricidade vinda de Memphis.', bioEn: 'Flies higher than a guard has any right to. Pure Memphis electricity.' },
  { name: 'Jeremy Lin', club: 'Knicks', year: 2012, fame: 2, lo: 66, hi: 83, folk: true, bioPt: 'LINSANITY. Duas semanas em que o mundo inteiro virou torcedor dos Knicks.', bioEn: 'LINSANITY. Two weeks when the whole world became Knicks fans.' },
  // ── Lote 2 ──
  { name: 'Russell Westbrook', club: 'Thunder', year: 2017, fame: 4, lo: 86, hi: 93, bioPt: 'Máquina de triple-double e MVP. "Why not?" e a roupa mais doida do vestiário.', bioEn: 'A triple-double machine and MVP. "Why not?" and the wildest outfits in the locker room.' },
  { name: 'Derrick Rose', club: 'Bulls', year: 2011, fame: 4, lo: 85, hi: 92, bioPt: 'O MVP mais jovem da história. O joelho traiu o sonho, mas Chicago nunca esqueceu.', bioEn: 'The youngest MVP ever. His knee betrayed the dream, but Chicago never forgot.' },
  { name: 'Tony Parker', club: 'Spurs', year: 2007, fame: 4, lo: 84, hi: 90, bioPt: 'Francês veloz, floater no garrafão e MVP de final. O motorzinho dos Spurs campeões.', bioEn: 'A speedy Frenchman, floaters in the paint and a Finals MVP. The engine of the champion Spurs.' },
  { name: 'Jason Williams (White Chocolate)', club: 'Kings', year: 2002, fame: 3, lo: 78, hi: 86, folk: true, bioPt: 'Passe de cotovelo, elastic pass, o playground na NBA. Mais firula que troféu.', bioEn: 'Elbow passes, the elastic pass, the playground in the NBA. More flash than trophies.' },
  { name: 'Muggsy Bogues', club: 'Hornets', year: 1994, fame: 2, lo: 64, hi: 82, folk: true, bioPt: '1,60m — o menor da história — roubando a bola dos gigantes. Tamanho não é tudo.', bioEn: 'Five-foot-three — the shortest ever — stealing the ball from giants. Size isn\'t everything.' },
  { name: 'Marcelinho Huertas', club: 'Lakers', year: 2016, fame: 1, lo: 58, hi: 77, folk: true, bioPt: 'Brasileiro de passe mágico que jogou na NBA e nunca para de jogar. Eterno cérebro. 🇧🇷', bioEn: 'A Brazilian magician who made the NBA and just never stops playing. An eternal floor general. 🇧🇷' },
  // -- Lote 3 --
  { name: "Luka Dončić", club: "Mavericks", year: 2024, fame: 4, lo: 88, hi: 94, bioPt: "Esloveno que já nasceu veterano. Step-back, olhão pro árbitro e triple-double dormindo.", bioEn: "A Slovenian born a veteran. Step-backs, puppy eyes to the ref and triple-doubles in his sleep." },
  { name: "Gary Payton (The Glove)", club: "Sonics", year: 1996, fame: 4, lo: 84, hi: 91, bioPt: "The Glove — a luva que sufocava o marcador e a boca que não calava nunca. Melhor defensor entre os armadores.", bioEn: "The Glove — a hand that smothered his man and a mouth that never stopped. The premier defensive guard." },
  { name: "Penny Hardaway", club: "Magic", year: 1996, fame: 3, lo: 82, hi: 89, bioPt: "Lil Penny e o boneco da propaganda. Talento de MVP até o joelho estragar a festa.", bioEn: "Lil Penny and the puppet in the ads. MVP talent until the knee crashed the party." },
  { name: "Kyle Lowry", club: "Raptors", year: 2019, fame: 3, lo: 79, hi: 87, folk: true, bioPt: "Baixinho parrudo que tomava carga pra ganhar falta. Campeão e maior herói de Toronto.", bioEn: "A stocky little bulldog who took charges for a living. A champion and Toronto's biggest hero." },
  { name: "Rajon Rondo", club: "Celtics", year: 2010, fame: 3, lo: 78, hi: 87, folk: true, bioPt: "Rei do triple-double e do QI de jogo. Arremesso? Melhor nem falar. Mão de gênio, mira de pedreiro.", bioEn: "King of the triple-double and basketball IQ. Jump shot? Let's not talk about it. Genius hands, bricklayer aim." },
  { name: "Baron Davis", club: "Warriors", year: 2007, fame: 3, lo: 78, hi: 87, bioPt: "Barba, força e a enterrada na cara do Kirilenko que derrubou o nº1. 'We Believe'.", bioEn: "Beard, power and the poster over Kirilenko that toppled the No.1 seed. 'We Believe'." },
  { name: "Stephon Marbury", club: "Knicks", year: 2004, fame: 3, lo: 78, hi: 86, folk: true, bioPt: "Starbury. Fez a própria linha de tênis baratinha e virou IMPERADOR na China. História doida.", bioEn: "Starbury. Made his own cheap sneaker line and became an EMPEROR in China. A wild story." },
  { name: "De'Aaron Fox", club: "Kings", year: 2023, fame: 3, lo: 79, hi: 87, bioPt: "O mais rápido da liga de ponta a ponta. Sangue-frio no fim de jogo — apelido Swipa.", bioEn: "The fastest end-to-end player in the league. Ice in crunch time — they call him Swipa." },
  // -- Lote 4 --
  { name: "Jason Kidd", club: "Nets", year: 2002, fame: 4, lo: 84, hi: 91, bioPt: "Rei do triple-double e do alley-oop. Levou dois Nets fracos à final. Depois, anel em Dallas.", bioEn: "King of the triple-double and the alley-oop. Dragged mediocre Nets to the Finals. Later, a ring in Dallas." },
  { name: "Tim Hardaway", club: "Warriors", year: 1993, fame: 4, lo: 83, hi: 90, bioPt: "O killer crossover (UTEP two-step) que deixava o marcador no chão. Run TMC puro veneno.", bioEn: "The killer crossover (UTEP two-step) that left defenders on the floor. Run TMC, pure venom." },
  { name: "Mark Price", club: "Cavaliers", year: 1993, fame: 3, lo: 79, hi: 87, bioPt: "Um dos melhores da linha de lance da história e bomba de 3. O cérebro do Cleveland dos anos 90.", bioEn: "One of the best free-throw shooters ever and a deep bomber. The brain of 90s Cleveland." },
  { name: "Sam Cassell", club: "Timberwolves", year: 2004, fame: 3, lo: 79, hi: 87, folk: true, bioPt: "Cara de ET e a dança dos balls of steel depois de bola importante. Três anéis e mó zoeira.", bioEn: "An alien face and the big-balls dance after every clutch shot. Three rings and endless comedy." },
  { name: "Kemba Walker", club: "Hornets", year: 2019, fame: 3, lo: 79, hi: 87, bioPt: "Cardíaco de Nova York — o crossover que fez faculdade inteira cair. Baixinho de coração gigante.", bioEn: "A New York bucket-getter — the crossover that made a whole college fall. Small guy, giant heart." },
  { name: "Trae Young", club: "Hawks", year: 2022, fame: 3, lo: 80, hi: 88, bioPt: "Ice Trae. Calou o Madison Square Garden sozinho e manda de 3 lá do logo. Amado de odiar.", bioEn: "Ice Trae. Silenced Madison Square Garden by himself and bombs from the logo. Easy to love to hate." },
  { name: "Ricky Rubio", club: "Timberwolves", year: 2017, fame: 2, lo: 70, hi: 83, folk: true, bioPt: "Mágico espanhol do passe — e do arremesso que só Deus explica. Herói da Espanha campeã do mundo.", bioEn: "A Spanish passing wizard — and a jumper only God can explain. Hero of world-champion Spain." },
  { name: "Nate Archibald", club: "Kings", year: 1973, fame: 4, lo: 83, hi: 90, folk: true, bioPt: "Tiny. 1,85m que liderou pontos E assistências na MESMA temporada — feito único na história.", bioEn: "Tiny. A six-foot-one guard who led the league in points AND assists the SAME season — a one-of-a-kind feat." },
  // ── Lote HOF (lendas do Hall da Fama) ──
  { name: "Oscar Robertson", club: "Royals", year: 1962, fame: 5, lo: 90, hi: 97, bioPt: "O Big O. Tirou média de triple-double numa temporada INTEIRA em 1962 — ninguém mais fez por 55 anos.", bioEn: "The Big O. Averaged a triple-double for a WHOLE season in 1962 — nobody did it again for 55 years." },
  { name: "Bob Cousy", club: "Celtics", year: 1957, fame: 5, lo: 87, hi: 94, bioPt: "O Houdini das quadras. Inventou o passe de fantasia e ganhou 6 anéis armando o jogo em Boston.", bioEn: "The Houdini of the Hardwood. Invented flashy passing and won 6 rings running the show in Boston." },
  { name: "Walt Frazier", club: "Knicks", year: 1970, fame: 5, lo: 87, hi: 94, bioPt: "Clyde. Estiloso dentro e fora da quadra, sufocou o rival e comandou o Knicks campeão de 1970.", bioEn: "Clyde. Ice-cool on and off the floor, he smothered his man and led the 1970 champion Knicks." },
  { name: "Lenny Wilkens", club: "SuperSonics", year: 1968, fame: 4, lo: 82, hi: 90, bioPt: "Armador All-Star que virou um dos maiores técnicos da história. Hall da Fama como jogador E treinador.", bioEn: "An All-Star guard who became one of the greatest coaches ever. Hall of Fame as a player AND a coach." },
  { name: "Dennis Johnson", club: "Celtics", year: 1986, fame: 4, lo: 82, hi: 89, bioPt: "DJ. Defensor durão e Finals MVP em 1979. O parceiro do Bird no roubo de bola mais famoso de Boston.", bioEn: "DJ. A tough defender and 1979 Finals MVP. Birds partner on Bostons most famous steal-and-dish." },
  { name: "Chauncey Billups", club: "Pistons", year: 2004, fame: 4, lo: 83, hi: 90, bioPt: "Mr. Big Shot. Finals MVP no Detroit operário que derrubou os Lakers galáticos em 2004.", bioEn: "Mr. Big Shot. Finals MVP for the blue-collar Pistons who toppled the star-studded Lakers in 2004." },
  { name: "Gail Goodrich", club: "Lakers", year: 1972, fame: 3, lo: 80, hi: 88, bioPt: "Cestinha do Lakers de 1972, dono da série recorde de 33 vitórias seguidas. Canhoto de mão quente.", bioEn: "Top scorer of the 1972 Lakers and their record 33-game win streak. A hot-handed lefty." },
  { name: "Maurice Cheeks", club: "Sixers", year: 1983, fame: 3, lo: 79, hi: 87, bioPt: "O maestro discreto do Sixers campeão de 1983. Rei do roubo de bola e das assistências sem barulho.", bioEn: "The quiet maestro of the 1983 champion Sixers. A king of steals and no-fuss assists." },
  { name: "Calvin Murphy", club: "Rockets", year: 1978, fame: 3, lo: 79, hi: 87, bioPt: "1,75m de pura pólvora. Recordista de lances livres e prova viva de que tamanho não é documento.", bioEn: "Five-foot-nine of pure gunpowder. A free-throw record holder and living proof size means nothing." },
  // ── Lote HOF 2 (variedade: posições + categorias) ──
  { name: "Dave Bing", club: "Pistons", year: 1968, fame: 4, lo: 83, hi: 90, bioPt: "Armador cestinha de Detroit e depois prefeito da cidade. Elegância no jogo, respeito na vida.", bioEn: "A scoring point guard in Detroit who later became the citys mayor. Elegance on the court, respect in life." },
  { name: "Jalen Brunson", club: "Knicks", year: 2024, fame: 4, lo: 83, hi: 90, bioPt: "O baixinho durão que fez o Madison Square Garden acreditar de novo. Poste no garrafão como armador nenhum.", bioEn: "The tough little guard who made Madison Square Garden believe again. Posts up like no other point guard." },
  { name: "Jo Jo White", club: "Celtics", year: 1976, fame: 3, lo: 80, hi: 88, bioPt: "Motor incansável do Celtics campeão de 76 e MVP daquela final épica de tripla prorrogação.", bioEn: "The tireless engine of the 76 champion Celtics and MVP of that epic triple-overtime Finals." },
  { name: "Tyrese Haliburton", club: "Pacers", year: 2024, fame: 3, lo: 78, hi: 89, promessa: true, bioPt: "Passador nato que ressuscitou o Indiana. Assistência com sorriso e três na cara do relógio.", bioEn: "A natural passer who revived Indiana. Dimes with a smile and threes in the clock's face." },
  { name: "LaMelo Ball", club: "Hornets", year: 2022, fame: 3, lo: 77, hi: 87, folk: true, bioPt: "Circo ambulante de dribles e passes malucos. O filho do LaVar que virou All-Star jovem.", bioEn: "A traveling circus of handles and crazy passes. LaVars son who became a young All-Star." },
  { name: "Fred VanVleet", club: "Raptors", year: 2019, fame: 3, lo: 79, hi: 87, folk: true, bioPt: "Bet on yourself. Não foi draftado e terminou campeão da NBA. Coração maior que a ficha.", bioEn: "Bet on yourself. Went undrafted and ended up an NBA champion. Heart bigger than the scouting report." },
  { name: "Nick Van Exel", club: "Lakers", year: 1998, fame: 3, lo: 78, hi: 86, folk: true, bioPt: "Nick the Quick. Canhota gelada, três de longe e atitude de bairro. Pura resenha dos anos 90.", bioEn: "Nick the Quick. Ice-cold lefty, deep threes and neighborhood attitude. Pure 90s swagger." },
  { name: "Isaiah Thomas", club: "Celtics", year: 2017, fame: 3, lo: 78, hi: 86, folk: true, bioPt: "1,75m e 28,9 pontos por jogo jogando pelo irmão. O pequeno gigante de Boston (não confunda com o Isiah!).", bioEn: "Five-foot-nine and 28.9 a night playing for his sister. Bostons little giant (dont confuse him with Isiah!)." },
  { name: "Steve Francis", club: "Rockets", year: 2004, fame: 3, lo: 79, hi: 87, folk: true, bioPt: "Stevie Franchise. Explosão pura e enterradas impossíveis pra um armador de 1,91m.", bioEn: "Stevie Franchise. Pure explosion and impossible dunks for a six-foot-three guard." },
  { name: "Raul Neto", club: "Jazz", year: 2016, fame: 1, lo: 62, hi: 80, folk: true, bioPt: "Brasiliense raçudo que segurou vaga na NBA no peito. Orgulho verde-amarelo no garrafão gringo.", bioEn: "A gritty guard from Brasília who earned his NBA spot on grit. Green-and-yellow pride in the foreign paint." },
  // ── Lote 4 (modernos + variedade) ──
  { name: "Tyrese Maxey", club: "Sixers", year: 2024, fame: 3, lo: 79, hi: 87, bioPt: "Velocidade pura e três de longe, sempre sorrindo. O motor jovem da Filadélfia.", bioEn: "Blazing speed and deep threes, always smiling. Philadelphias young engine." },
  { name: "Mike Conley", club: "Grizzlies", year: 2016, fame: 3, lo: 79, hi: 86, bioPt: "O armador mais subestimado de uma geração. Comando silencioso, defesa e caráter.", bioEn: "The most underrated point guard of a generation. Quiet control, defense and character." },
  { name: "Dennis Schröder", club: "Hawks", year: 2023, fame: 2, lo: 74, hi: 84, folk: true, bioPt: "Alemão veloz e destemido — herói do ouro mundial de 2023. Fala pouco, corre muito.", bioEn: "A fast, fearless German — hero of the 2023 World Cup gold. Talks little, runs a lot." },
]

// ─── SG · ALA-ARMADOR ────────────────────────────────────────────────
const SG: BC[] = [
  { name: 'Michael Jordan', club: 'Bulls', year: 1996, fame: 5, lo: 93, hi: 99, bioPt: 'O melhor de todos. 6 finais, 6 anéis, 6 MVPs de final. Fim de papo.', bioEn: 'The greatest of all time. 6 Finals, 6 rings, 6 Finals MVPs. End of debate.' },
  { name: 'Kobe Bryant', club: 'Lakers', year: 2008, fame: 5, lo: 91, hi: 97, bioPt: 'Mamba Mentality. 81 pontos num jogo, 5 anéis e obsessão total por vencer. Eterno.', bioEn: 'Mamba Mentality. 81 in a game, 5 rings and a total obsession with winning. Forever.' },
  { name: 'Dwyane Wade', club: 'Heat', year: 2006, fame: 5, lo: 88, hi: 95, bioPt: 'Flash. Carregou o Heat ao anel de 2006 quase sozinho. Máquina de pôster.', bioEn: 'Flash. Dragged the Heat to the 2006 ring almost by himself. A poster machine.' },
  { name: 'James Harden', club: 'Rockets', year: 2018, fame: 4, lo: 86, hi: 93, bioPt: 'A barba, o step-back e o eurostep pra linha de lance. MVP de dar nó no marcador.', bioEn: 'The beard, the step-back and the euro to the line. An MVP who ties defenders in knots.' },
  { name: 'Ray Allen', club: 'Celtics', year: 2013, fame: 4, lo: 85, hi: 91, bioPt: 'A bola de 3 mais bonita da história — pergunta pros Spurs sobre 2013.', bioEn: 'The purest three-point stroke ever — ask the Spurs about 2013.' },
  { name: 'Vince Carter', club: 'Raptors', year: 2000, fame: 4, lo: 85, hi: 92, bioPt: 'Half Man, Half Amazing. Pulou POR CIMA de um pivô de 2,18m nas Olimpíadas.', bioEn: 'Half Man, Half Amazing. Jumped clean OVER a 7\'2" center at the Olympics.' },
  { name: 'Tracy McGrady', club: 'Magic', year: 2003, fame: 4, lo: 85, hi: 92, bioPt: '13 pontos em 33 segundos. Talento de anel com azar de playoffs.', bioEn: '13 points in 33 seconds. Ring-level talent with playoff-level bad luck.' },
  { name: 'Manu Ginóbili', club: 'Spurs', year: 2005, fame: 4, lo: 84, hi: 91, bioPt: 'Levou o eurostep pro mundo. Canhoto argentino que ganhava tudo saindo do banco.', bioEn: 'Brought the Eurostep to the world. An Argentine lefty who won it all off the bench.' },
  { name: 'Reggie Miller', club: 'Pacers', year: 1995, fame: 4, lo: 84, hi: 91, folk: true, bioPt: '8 pontos em 9 segundos e o sinal de "choke" pro Spike Lee. Vilão amado de Nova York.', bioEn: '8 points in 9 seconds and the choke sign to Spike Lee. New York\'s beloved villain.' },
  { name: 'Anthony Edwards', club: 'Wolves', year: 2024, fame: 3, lo: 79, hi: 88, promessa: true, bioPt: 'Sorriso, gargalhada e enterrada na sua cara. O futuro chegou e é divertido.', bioEn: 'Smile, laugh and a dunk in your face. The future is here and it\'s fun.' },
  { name: 'JR Smith', club: 'Cavaliers', year: 2018, fame: 2, lo: 66, hi: 82, folk: true, bioPt: 'Pegou o rebote na final de 2018 e... esqueceu o placar. Meme eterno.', bioEn: 'Grabbed the 2018 Finals rebound and... forgot the score. Eternal meme.' },
  // ── Lote 2 ──
  { name: 'Klay Thompson', club: 'Warriors', year: 2016, fame: 4, lo: 85, hi: 92, bioPt: 'Splash Brother nº2. 37 pontos num quarto só. Chega quieto e te afoga de 3.', bioEn: 'Splash Brother No.2. 37 points in a single quarter. Shows up quiet and drowns you in threes.' },
  { name: 'Nick Young (Swaggy P)', club: 'Lakers', year: 2014, fame: 2, lo: 64, hi: 82, folk: true, bioPt: 'Comemorou uma bola de 3 que NÃO entrou. O meme mais honesto da NBA.', bioEn: 'Celebrated a three that DIDN\'T go in. The most honest meme in the NBA.' },
  { name: 'Nate Robinson', club: 'Knicks', year: 2010, fame: 2, lo: 62, hi: 81, folk: true, bioPt: '1,75m e TRÊS títulos de enterrada. Pulou por cima do Yao no concurso. Depois levou nocaute no boxe 😅.', bioEn: 'Five-foot-nine and THREE dunk titles. Leapt over Yao in the contest. Later got knocked out boxing 😅.' },
  { name: 'Leandrinho', club: 'Suns', year: 2007, fame: 2, lo: 66, hi: 83, folk: true, bioPt: 'O Borrão Brasileiro. Sexto Homem do Ano, velocidade pura e anel em 2007. 🇧🇷', bioEn: 'The Brazilian Blur. Sixth Man of the Year, pure speed and a 2007 ring. 🇧🇷' },
  { name: 'Brian Scalabrine (White Mamba)', club: 'Celtics', year: 2008, fame: 1, lo: 52, hi: 72, folk: true, bioPt: 'O herói do banco. A torcida gritava o nome dele nos 2 minutos finais. Anel em 2008 sem suar.', bioEn: 'The bench hero. The crowd chanted his name in garbage time. A 2008 ring without breaking a sweat.' },
  { name: 'Adam Morrison', club: 'Lakers', year: 2008, fame: 1, lo: 50, hi: 70, folk: true, bioPt: 'Bigode, cabelão e DOIS anéis... aquecendo o banco. O bust mais estiloso da história.', bioEn: 'Mustache, long hair and TWO rings... warming the bench. The most stylish bust ever.' },
  // -- Lote 3 --
  { name: "George Gervin (The Iceman)", club: "Spurs", year: 1978, fame: 4, lo: 85, hi: 92, bioPt: "The Iceman. O finger roll mais suave da história e quatro cestas de pontos. Frieza de geladeira.", bioEn: "The Iceman. The smoothest finger roll ever and four scoring titles. Cool as a freezer." },
  { name: "Pete Maravich (Pistol Pete)", club: "Jazz", year: 1977, fame: 4, lo: 84, hi: 91, folk: true, bioPt: "Pistol Pete. Meião caído e dribles de circo décadas à frente. Show antes de show existir.", bioEn: "Pistol Pete. Floppy socks and circus handles decades ahead of his time. A show before shows existed." },
  { name: "Devin Booker", club: "Suns", year: 2022, fame: 4, lo: 84, hi: 91, bioPt: "70 pontos num jogo com 20 aninhos. Arremesso puro e cara de poucos amigos.", bioEn: "70 points in a game at just 20. A pure jumper and a permanent scowl." },
  { name: "Jimmy Butler", club: "Heat", year: 2020, fame: 4, lo: 85, hi: 91, bioPt: "Playoff Jimmy. Vira outro cara no mata-mata — e ainda vende café no vestiário. Raiz pura.", bioEn: "Playoff Jimmy. Turns into a different beast in the postseason — and sells coffee in the locker room. Pure grit." },
  { name: "Paul George", club: "Clippers", year: 2019, fame: 4, lo: 84, hi: 90, bioPt: "PG-13. Pontos, defesa e um lugar cativo nos memes de playoff ('Playoff P'). Talento gigante.", bioEn: "PG-13. Scoring, defense and a permanent spot in the playoff meme hall ('Playoff P'). Huge talent." },
  { name: "Gilbert Arenas (Agent Zero)", club: "Wizards", year: 2007, fame: 3, lo: 80, hi: 88, folk: true, bioPt: "Agent Zero. Arremesso do meio da quadra e as histórias mais doidas da NBA (não pesquisa o armário 😅).", bioEn: "Agent Zero. Logo threes and the wildest stories in NBA history (don't google the locker room 😅)." },
  { name: "Donovan Mitchell", club: "Cavaliers", year: 2023, fame: 3, lo: 81, hi: 88, bioPt: "Spida. Baixinho pra ala-armador que explode de 40 pontos quando menos se espera.", bioEn: "Spida. Undersized for a two-guard who erupts for 40 out of nowhere." },
  { name: "Michael Redd", club: "Bucks", year: 2006, fame: 2, lo: 72, hi: 84, bioPt: "Canhoto de arremesso lindo — dava 25 por noite quieto em Milwaukee. Ouro olímpico no Redeem Team.", bioEn: "A lefty with a gorgeous stroke — quietly dropped 25 a night in Milwaukee. Olympic gold with the Redeem Team." },
  // -- Lote 4 --
  { name: "Joe Dumars", club: "Pistons", year: 1990, fame: 4, lo: 83, hi: 90, bioPt: "O cavalheiro dos Bad Boys — classe fora, punhal dentro. MVP de final e bicampeão. Depois montou o campeão de 2004.", bioEn: "The gentleman of the Bad Boys — class outside, dagger inside. Finals MVP and two-time champ. Later built the 2004 title team." },
  { name: "Rip Hamilton", club: "Pistons", year: 2004, fame: 3, lo: 80, hi: 88, folk: true, bioPt: "A máscara mais famosa da NBA. Corria a quadra inteira sem a bola até o marcador desmaiar. Campeão 2004.", bioEn: "The most famous mask in the NBA. Ran all game without the ball until his man fainted. 2004 champ." },
  { name: "Latrell Sprewell", club: "Warriors", year: 1994, fame: 3, lo: 79, hi: 87, folk: true, bioPt: "Talento enorme e a treta com o técnico que virou história. Tenho família pra alimentar.", bioEn: "Huge talent and the coach fight that made history. I have a family to feed." },
  { name: "Zach LaVine", club: "Bulls", year: 2021, fame: 3, lo: 80, hi: 88, bioPt: "Rei do concurso de enterradas — a da linha de lance de olho fechado. Mola nos pés.", bioEn: "King of the dunk contest — the free-throw-line jam with eyes closed. Springs in his feet." },
  { name: "Jamal Murray", club: "Nuggets", year: 2023, fame: 3, lo: 81, hi: 88, bioPt: "Blue Arrow. A bolha de 2020 e o parceiro perfeito do Jokić rumo ao anel de 2023.", bioEn: "Blue Arrow. The 2020 bubble and Jokić's perfect partner on the way to the 2023 ring." },
  { name: "Bradley Beal", club: "Wizards", year: 2021, fame: 3, lo: 80, hi: 87, bioPt: "Arremesso puro que dava 30 por noite num time que nunca ganhava. Talento preso em DC.", bioEn: "A pure shooter dropping 30 a night on a team that never won. Talent stuck in DC." },
  { name: "Dan Majerle", club: "Suns", year: 1993, fame: 2, lo: 74, hi: 84, folk: true, bioPt: "Thunder Dan. Bombas de 3 e defesa raçuda no Phoenix de finais. O xodó que o Barkley amava.", bioEn: "Thunder Dan. Three-point bombs and gritty defense on the Finals Suns. The fan favorite Barkley loved." },
  { name: "J.J. Redick", club: "Clippers", year: 2016, fame: 2, lo: 74, hi: 84, folk: true, bioPt: "Vilão da faculdade que virou sniper de 3 na NBA — e hoje um dos maiores podcasters do basquete.", bioEn: "A college villain turned NBA three-point sniper — and now one of basketball's biggest podcasters." },
  // ── Lote HOF (lendas do Hall da Fama) ──
  { name: "Jerry West", club: "Lakers", year: 1969, fame: 5, lo: 89, hi: 96, bioPt: "O Logo da NBA. Mr. Clutch: único Finals MVP de um time DERROTADO. Frieza e cesta na hora H.", bioEn: "The NBA Logo. Mr. Clutch: the only Finals MVP from a LOSING team. Ice water and buckets when it mattered." },
  { name: "Clyde Drexler", club: "Blazers", year: 1992, fame: 5, lo: 87, hi: 94, bioPt: "The Glide. Planava pra enterrar como se a gravidade fosse opcional. Anel com o Hakeem em 95.", bioEn: "The Glide. Soared to dunk like gravity was optional. Won the ring alongside Hakeem in 95." },
  { name: "Sam Jones", club: "Celtics", year: 1965, fame: 4, lo: 84, hi: 91, bioPt: "Mr. Clutch de Boston antes do apelido existir. Bandeja na tabela e DEZ anéis na estante.", bioEn: "Bostons Mr. Clutch before the nickname existed. Bank shots off the glass and TEN rings on the shelf." },
  { name: "Hal Greer", club: "Sixers", year: 1967, fame: 4, lo: 83, hi: 90, bioPt: "Jumper de meia distância cirúrgico e motor do Sixers campeão de 1967, um dos melhores times de todos os tempos.", bioEn: "A surgical mid-range jumper and engine of the 1967 champion Sixers, one of the greatest teams ever." },
  { name: "Earl Monroe (The Pearl)", club: "Bullets", year: 1971, fame: 4, lo: 84, hi: 91, bioPt: "The Pearl. Black Jesus do playground: rodava, fintava e inventava lances que ninguém tinha visto.", bioEn: "The Pearl. Playground Black Jesus: spun, faked and invented moves nobody had ever seen." },
  { name: "Mitch Richmond", club: "Kings", year: 1996, fame: 4, lo: 83, hi: 90, bioPt: "The Rock. Anos preso num Sacramento fraco marcando sem parar. Enfim o anel de tabela em 2002.", bioEn: "The Rock. Years stuck on weak Sacramento teams scoring at will. Finally a bench ring in 2002." },
  { name: "Michael Cooper", club: "Lakers", year: 1987, fame: 3, lo: 78, hi: 86, bioPt: "Coop-a-Loop. Alley-oop com o Magic e o cão de guarda que travava o Bird. Defensor do Ano de 1987.", bioEn: "Coop-a-Loop. Alley-oops with Magic and the watchdog who locked up Bird. 1987 Defensive Player of the Year." },
  // ── Lote HOF 2 (variedade: posições + categorias) ──
  { name: "Dražen Petrović", club: "Nets", year: 1993, fame: 4, lo: 84, hi: 91, bioPt: "O Mozart dos arremessos. Gênio europeu que conquistou a NBA e partiu cedo demais, aos 28. Eterno.", bioEn: "The Mozart of shooting. A European genius who conquered the NBA and left far too soon at 28. Eternal." },
  { name: "Bill Sharman", club: "Celtics", year: 1958, fame: 4, lo: 83, hi: 90, bioPt: "Mira cirúrgica dos primeiros Celtics campeões e recordista de lances livres. Depois, técnico revolucionário.", bioEn: "Surgical aim on the first champion Celtics and a free-throw record holder. Later, a revolutionary coach." },
  { name: "Paul Arizin", club: "Warriors", year: 1957, fame: 4, lo: 82, hi: 90, bioPt: "Pop-a-shot. Popularizou o jump shot moderno e foi cestinha antes de o mundo ligar pra isso.", bioEn: "Pop-a-shot. Popularized the modern jumper and led the league in scoring before anyone cared." },
  { name: "Shai Gilgeous-Alexander", club: "Thunder", year: 2024, fame: 4, lo: 84, hi: 91, bioPt: "SGA. Meia distância letal em câmera lenta e passada longa impossível de conter. MVP em Oklahoma.", bioEn: "SGA. Lethal slow-motion mid-range and an unguardable long stride. An MVP in Oklahoma." },
  { name: "Vinnie Johnson (The Microwave)", club: "Pistons", year: 1990, fame: 3, lo: 79, hi: 87, folk: true, bioPt: "The Microwave. Entrava do banco e esquentava na hora — a cesta do título de 90 saiu da mão dele.", bioEn: "The Microwave. Came off the bench and heated up instantly — the 90 title-winning bucket came off his hand." },
  { name: "Jrue Holiday", club: "Bucks", year: 2021, fame: 3, lo: 80, hi: 87, bioPt: "O cão de guarda dos armadores rivais. Defesa que ganha anel (Milwaukee 2021) e caráter fora da quadra.", bioEn: "The watchdog of rival guards. Ring-winning defense (Milwaukee 2021) and character off the floor." },
  { name: "CJ McCollum", club: "Blazers", year: 2016, fame: 3, lo: 79, hi: 87, bioPt: "Parceiro de backcourt do Dame com meia distância de manual e um dos caras mais articulados da liga.", bioEn: "Dame's backcourt partner with a textbook mid-range and one of the most articulate voices in the league." },
  { name: "Lou Williams", club: "Clippers", year: 2018, fame: 2, lo: 74, hi: 85, folk: true, bioPt: "Lord of the Fourth Quarter. Melhor sexto homem da história — chegava do banco e detonava o jogo.", bioEn: "Lord of the Fourth Quarter. The best sixth man ever — came off the bench and torched the game." },
  // ── Lote 4 (modernos + variedade) ──
  { name: "Sidney Moncrief", club: "Bucks", year: 1983, fame: 4, lo: 83, hi: 90, bioPt: "Sir Sid. Duas vezes Defensor do Ano — travava o melhor do rival e ainda pontuava. HOF discreto.", bioEn: "Sir Sid. Two-time Defensive Player of the Year — locked up the rivals best and still scored. A quiet HOFer." },
  { name: "World B. Free", club: "Clippers", year: 1980, fame: 3, lo: 79, hi: 86, folk: true, bioPt: "All-World. Trocou o nome pra 'Mundo' e jogava como o nome — 30 por jogo de puro estilo.", bioEn: "All-World. Legally changed his name and played like it — 30 a night of pure style." },
  { name: "Anfernee Simons", club: "Blazers", year: 2023, fame: 2, lo: 76, hi: 85, folk: true, bioPt: "Salto de mola e três em série — o herdeiro do backcourt de Portland.", bioEn: "Springy hops and threes in bunches — heir to Portlands backcourt." },
]

// ─── SF · ALA ────────────────────────────────────────────────────────
const SF: BC[] = [
  { name: 'LeBron James', club: 'Cavaliers', year: 2016, fame: 5, lo: 92, hi: 98, bioPt: 'O Rei. Trouxe o anel pra Cleveland com o bloqueio da vida. Um caminhão de talento.', bioEn: 'The King. Brought Cleveland a ring with The Block. A freight truck of talent.' },
  { name: 'Larry Bird', club: 'Celtics', year: 1986, fame: 5, lo: 91, hi: 97, bioPt: 'Trash-talk lendário e mão gelada do canto. Avisava o placar antes de acertar.', bioEn: 'Legendary trash talk and an ice-cold corner three. Called the shot before draining it.' },
  { name: 'Kevin Durant', club: 'Warriors', year: 2017, fame: 5, lo: 90, hi: 97, bioPt: '2,08m com mira de armador. Impossível de marcar, fácil de xingar no Twitter.', bioEn: 'Seven feet with a guard\'s touch. Impossible to guard, easy to roast on Twitter.' },
  { name: 'Kawhi Leonard', club: 'Raptors', year: 2019, fame: 4, lo: 87, hi: 93, bioPt: 'The Board Man. Mãos gigantes, cara de paisagem e a bola que quicou 4x contra o Philly.', bioEn: 'The Board Man. Giant hands, no expression and the four-bounce dagger over Philly.' },
  { name: 'Scottie Pippen', club: 'Bulls', year: 1994, fame: 4, lo: 85, hi: 91, bioPt: 'O melhor braço-direito da história. Defesa sufocante e o eterno "e se fosse titular?".', bioEn: 'The greatest sidekick ever. Suffocating defense and an eternal "what if he\'d led a team?".' },
  { name: 'Carmelo Anthony', club: 'Nuggets', year: 2013, fame: 4, lo: 84, hi: 91, bioPt: 'Melô. Jab step, subiu e converteu — o arremesso mais bonito da geração.', bioEn: 'Melo. Jab step, rise and bucket — the prettiest jumper of his generation.' },
  { name: 'Paul Pierce', club: 'Celtics', year: 2008, fame: 4, lo: 84, hi: 91, folk: true, bioPt: 'The Truth. Saiu de cadeira de rodas na final e voltou andando 🤔. Anel em 2008.', bioEn: 'The Truth. Left the Finals in a wheelchair and walked right back 🤔. Ring in 2008.' },
  { name: 'Jayson Tatum', club: 'Celtics', year: 2024, fame: 4, lo: 85, hi: 92, bioPt: 'Aluno do Kobe com anel em 2024. Sobe fácil e marca de todo jeito.', bioEn: 'Kobe\'s student with a 2024 ring. Rises easy and scores every which way.' },
  { name: 'Grant Hill', club: 'Pistons', year: 1997, fame: 3, lo: 80, hi: 88, bioPt: 'Era o "próximo Jordan" até o tornozelo trair. Elegância pura antes das lesões.', bioEn: 'Was the "next Jordan" until his ankle betrayed him. Pure elegance before the injuries.' },
  { name: 'Metta World Peace', club: 'Lakers', year: 2010, fame: 3, lo: 78, hi: 87, folk: true, bioPt: 'Agradeceu o psiquiatra na TV depois do anel. Defesa insana, mente livre.', bioEn: 'Thanked his psychiatrist on live TV after the ring. Insane defense, free mind.' },
  // ── Lote 2 ──
  { name: 'Anderson Varejão', club: 'Cavaliers', year: 2010, fame: 2, lo: 66, hi: 83, folk: true, bioPt: 'O cabelo, os flops teatrais e a energia infinita ao lado do LeBron. Xodó do Brasil na NBA. 🇧🇷', bioEn: 'The hair, the theatrical flops and endless energy next to LeBron. Brazil\'s NBA darling. 🇧🇷' },
  { name: 'Bruno Caboclo', club: 'Raptors', year: 2014, fame: 1, lo: 50, hi: 72, folk: true, bioPt: '"Está a dois anos de estar a dois anos de distância." A frase de scout que virou lenda. 🇧🇷', bioEn: '"Two years away from being two years away." The scouting line that became legend. 🇧🇷' },
  { name: 'Andrei Kirilenko (AK-47)', club: 'Jazz', year: 2004, fame: 3, lo: 80, hi: 88, bioPt: 'Russo que enchia a súmula: pontos, tocos, roubos, tudo. O canivete suíço do Jazz.', bioEn: 'A Russian who stuffed the box score: points, blocks, steals, everything. The Jazz\'s Swiss army knife.' },
  { name: 'Robert Horry (Big Shot Bob)', club: 'Lakers', year: 2002, fame: 3, lo: 76, hi: 86, folk: true, bioPt: 'Coadjuvante com SETE anéis. Sumia o jogo todo e acertava a bola que ganhava a série.', bioEn: 'A role player with SEVEN rings. Vanished all game then hit the shot that won the series.' },
  // -- Lote 3 --
  { name: "Julius Erving (Dr. J)", club: "Sixers", year: 1983, fame: 5, lo: 89, hi: 96, bioPt: "Dr. J. O homem que fez a enterrada virar arte e o afro virar bandeira. Voou antes do Jordan.", bioEn: "Dr. J. The man who turned the dunk into art and the afro into a flag. Flew before Jordan." },
  { name: "Dominique Wilkins", club: "Hawks", year: 1988, fame: 4, lo: 85, hi: 91, bioPt: "The Human Highlight Film. Windmills de tirar o fôlego e o duelo eterno de enterradas com o Jordan.", bioEn: "The Human Highlight Film. Breathtaking windmills and an eternal dunk duel with Jordan." },
  { name: "Shawn Marion", club: "Suns", year: 2007, fame: 3, lo: 80, hi: 88, folk: true, bioPt: "The Matrix. O arremesso mais feio da NBA que... entrava sempre. Enchia a súmula em tudo.", bioEn: "The Matrix. The ugliest shot in the NBA that... always went in. Stuffed every stat line." },
  { name: "Rasheed Wallace", club: "Pistons", year: 2004, fame: 3, lo: 80, hi: 88, folk: true, bioPt: "'BALL DON'T LIE!' Rei das técnicas e peça-chave do Detroit campeão de 2004. Gênio e barraco.", bioEn: "'BALL DON'T LIE!' King of the technical foul and a key piece of the 2004 champion Pistons. Genius and chaos." },
  { name: "Andre Iguodala", club: "Warriors", year: 2015, fame: 3, lo: 79, hi: 87, bioPt: "Iggy. Saiu do banco e virou MVP das Finais segurando o LeBron. O especialista.", bioEn: "Iggy. Came off the bench and won Finals MVP guarding LeBron. The specialist." },
  { name: "Jamal Crawford", club: "Clippers", year: 2014, fame: 3, lo: 78, hi: 87, folk: true, bioPt: "Rei do sexto-homem e das cruzadas que quebravam tornozelo. 3x melhor reserva da liga.", bioEn: "King of the sixth man and ankle-breaking crossovers. 3x Sixth Man of the Year." },
  { name: "Michael Finley", club: "Mavericks", year: 2001, fame: 2, lo: 74, hi: 84, bioPt: "Ala matador do Dallas antes do Dirk brilhar sozinho. Depois, anel com os Spurs.", bioEn: "A scoring wing in Dallas before Dirk took over. Later, a ring with the Spurs." },
  { name: "Danny Granger", club: "Pacers", year: 2009, fame: 2, lo: 74, hi: 84, bioPt: "Foi a estrela de Indiana em ascensão — até o Paul George e as lesões chegarem.", bioEn: "Was Indiana's rising star — until Paul George and injuries arrived." },
  // -- Lote 4 --
  { name: "James Worthy", club: "Lakers", year: 1988, fame: 4, lo: 84, hi: 91, bioPt: "Big Game James. Aparecia nas finais e a bandeja no contra-ataque era arte. Tricampeão do Showtime.", bioEn: "Big Game James. Showed up in the Finals and turned the fast-break layup into art. Three-time Showtime champ." },
  { name: "Rick Barry", club: "Warriors", year: 1975, fame: 4, lo: 83, hi: 90, folk: true, bioPt: "O único astro a bater lance livre por baixo (vovó) — e acertava quase tudo. MVP de final e boca solta.", bioEn: "The only star to shoot free throws granny-style underhand — and hit almost everything. Finals MVP and loose lips." },
  { name: "Peja Stojaković", club: "Kings", year: 2004, fame: 3, lo: 80, hi: 88, bioPt: "Sérvio com uma das melhores bolas de 3 da história. Bicampeão do concurso e anel em Dallas.", bioEn: "A Serbian with one of the sweetest threes ever. Two-time three-point contest champ and a ring in Dallas." },
  { name: "Glen Rice", club: "Hornets", year: 1997, fame: 3, lo: 80, hi: 87, bioPt: "Arremesso quente que pegava fogo — recordista de pontos no All-Star. Anel com o Lakers.", bioEn: "A hot stroke that caught fire — an All-Star Game scoring record holder. A ring with the Lakers." },
  { name: "Detlef Schrempf", club: "Sonics", year: 1995, fame: 3, lo: 78, hi: 86, folk: true, bioPt: "Alemão versátil, 2x melhor sexto homem — e depois eternizado numa ponta em Parks and Rec.", bioEn: "A versatile German, 2x Sixth Man of the Year — later immortalized in a Parks and Rec cameo." },
  { name: "Josh Smith", club: "Hawks", year: 2010, fame: 2, lo: 76, hi: 85, folk: true, bioPt: "J-Smoove. Toco monstro e enterrada de tirar o fôlego... e a insistência teimosa na bola de 3.", bioEn: "J-Smoove. Monster blocks and breathtaking dunks... and a stubborn love for the three he could not make." },
  { name: "Jaylen Brown", club: "Celtics", year: 2024, fame: 3, lo: 81, hi: 88, bioPt: "Explosão atlética e MVP das Finais de 2024. Inteligente dentro e fora da quadra.", bioEn: "Athletic explosion and 2024 Finals MVP. Smart on and off the court." },
  { name: "Gordon Hayward", club: "Jazz", year: 2017, fame: 2, lo: 76, hi: 85, folk: true, bioPt: "Era All-Star em ascensão até a perna quebrar em 5 minutos de Boston. O maior e se? recente.", bioEn: "A rising All-Star until his leg snapped five minutes into his Boston debut. A recent great what-if." },
  // ── Lote HOF (lendas do Hall da Fama) ──
  { name: "Elgin Baylor", club: "Lakers", year: 1962, fame: 5, lo: 88, hi: 95, bioPt: "O pai do basquete aéreo. 38 pontos por jogo em 1962 e voava antes de voar virar moda. Azar: nunca o anel.", bioEn: "The father of hang-time. 38 points a game in 1962, flying before flying was cool. Cursed to never win the ring." },
  { name: "John Havlicek", club: "Celtics", year: 1974, fame: 5, lo: 87, hi: 94, bioPt: "Hondo. Motor que não cansava nunca e autor do roubo mais narrado da história: HAVLICEK STOLE THE BALL!", bioEn: "Hondo. A motor that never tired and author of the most famous steal ever called: HAVLICEK STOLE THE BALL!" },
  { name: "Alex English", club: "Nuggets", year: 1983, fame: 4, lo: 83, hi: 90, bioPt: "Poeta silencioso do garrafão. Cestinha da década de 80 com o jumper mais suave das montanhas de Denver.", bioEn: "The quiet poet of the paint. Top scorer of the 1980s with the smoothest jumper in the Denver mountains." },
  { name: "Adrian Dantley", club: "Jazz", year: 1984, fame: 4, lo: 83, hi: 90, bioPt: "Baixinho e troncudo que humilhava alas maiores no poste. Dois títulos de cestinha na base do footwork.", bioEn: "Short and stocky, he bullied bigger wings on the block. Two scoring titles built on filthy footwork." },
  { name: "Bernard King", club: "Knicks", year: 1984, fame: 4, lo: 83, hi: 90, bioPt: "Máquina de pontuar de Nova York. Cravou 50 em jogos seguidos até o joelho estourar no auge.", bioEn: "New Yorks scoring machine. Dropped 50 on back-to-back nights until his knee blew at his peak." },
  { name: "Chris Mullin", club: "Warriors", year: 1991, fame: 4, lo: 83, hi: 90, bioPt: "Canhoto de manual e alma do Run TMC. Sniper trabalhador que virou lenda em Golden State.", bioEn: "A textbook lefty and soul of Run TMC. A hard-working sniper who became a Golden State legend." },
  { name: "Billy Cunningham", club: "Sixers", year: 1969, fame: 4, lo: 82, hi: 89, bioPt: "The Kangaroo Kid. Ala saltador do Sixers, campeão como jogador em 67 e como técnico em 83.", bioEn: "The Kangaroo Kid. A springy Sixers forward, champion as a player in 67 and as a coach in 83." },
  // ── Lote HOF 2 (variedade: posições + categorias) ──
  { name: "Connie Hawkins (The Hawk)", club: "Suns", year: 1970, fame: 4, lo: 83, hi: 90, bioPt: "The Hawk. Lenda de Rucker Park de mãos gigantes que planava antes do Dr. J. Playground virou arte.", bioEn: "The Hawk. A Rucker Park legend with giant hands who soared before Dr. J. Playground turned to art." },
  { name: "Bobby Dandridge", club: "Bucks", year: 1974, fame: 3, lo: 80, hi: 87, bioPt: "O terceiro homem silencioso de dois campeões. Defensor de elite e jumper confiável quando pesava.", bioEn: "The quiet third man on two champions. Elite defender and a reliable jumper when it mattered." },
  { name: "Toni Kukoč", club: "Bulls", year: 1996, fame: 3, lo: 80, hi: 88, bioPt: "O Waldo croata. Sexto homem mágico do terceiro título do Bulls — armava de 2,08m.", bioEn: "The Croatian Waldo. Magical sixth man on the Bulls third title — a 6-foot-10 playmaker." },
  { name: "Khris Middleton", club: "Bucks", year: 2021, fame: 3, lo: 80, hi: 87, bioPt: "O sócio silencioso do Giannis. Meia distância de sangue-frio que fechou o título de 2021.", bioEn: "Giannis quiet partner. A cold-blooded mid-range that closed out the 2021 title." },
  { name: "Brandon Ingram", club: "Pelicans", year: 2020, fame: 3, lo: 79, hi: 87, bioPt: "Braços de 2,20m e jumper macio de manual. Elegância pura vinda de New Orleans.", bioEn: "A seven-foot-three wingspan and a silky textbook jumper. Pure elegance out of New Orleans." },
  { name: "Andrew Wiggins", club: "Warriors", year: 2022, fame: 3, lo: 79, hi: 87, folk: true, bioPt: "De suposto bust a peça-chave do título de 2022, travando o Tatum. Renasceu em Golden State.", bioEn: "From supposed bust to key piece of the 2022 title, locking up Tatum. Reborn in Golden State." },
  { name: "Mikal Bridges", club: "Suns", year: 2022, fame: 3, lo: 78, hi: 86, bioPt: "Ferro de marcação e motor que nunca para — jogou todos os jogos da carreira por anos a fio.", bioEn: "A lockdown defender and a motor that never stops — played every game of his career for years straight." },
  { name: "Franz Wagner", club: "Magic", year: 2024, fame: 3, lo: 77, hi: 87, promessa: true, bioPt: "Alemão alto e habilidoso que faz de tudo. O futuro do Orlando construído na base da inteligência.", bioEn: "A tall, skilled German who does a bit of everything. Orlandos future built on pure basketball IQ." },
  { name: "Ben Simmons", club: "Sixers", year: 2018, fame: 2, lo: 74, hi: 86, folk: true, bioPt: "Point-forward que defende as 5 posições — e o maior meme da liga por não querer arremessar.", bioEn: "A point-forward who guards all five spots — and the leagues biggest meme for refusing to shoot." },
  // ── Lote 4 (modernos + variedade) ──
  { name: "Marques Johnson", club: "Bucks", year: 1979, fame: 3, lo: 80, hi: 87, bioPt: "Point-forward antes do termo existir. Elegância e versatilidade em Milwaukee.", bioEn: "A point-forward before the term existed. Elegance and versatility in Milwaukee." },
  { name: "Scottie Barnes", club: "Raptors", year: 2024, fame: 3, lo: 77, hi: 88, promessa: true, bioPt: "Gigante-canivete que arma, defende e sorri. O futuro do Toronto.", bioEn: "A Swiss-army giant who playmakes, defends and smiles. Torontos future." },
  { name: "Jalen Williams", club: "Thunder", year: 2024, fame: 3, lo: 77, hi: 87, promessa: true, bioPt: "J-Dub. Ala completo e peça de título do OKC jovem. Cresceu rápido demais.", bioEn: "J-Dub. A complete wing and title piece of the young Thunder. Grew up too fast." },
  { name: "Cedric Ceballos", club: "Suns", year: 1993, fame: 2, lo: 74, hi: 84, folk: true, bioPt: "Ganhou o concurso de enterradas DE OLHOS VENDADOS. Pontuava e curtia a vida.", bioEn: "Won the dunk contest BLINDFOLDED. Scored buckets and enjoyed life." },
]

// ─── PF · ALA-PIVÔ ───────────────────────────────────────────────────
const PF: BC[] = [
  { name: 'Tim Duncan', club: 'Spurs', year: 2003, fame: 5, lo: 91, hi: 97, bioPt: 'O Big Fundamental. Bola na tabela, cara de tédio e 5 anéis. Chato de tão bom.', bioEn: 'The Big Fundamental. Bank shot, bored face and 5 rings. So good it\'s boring.' },
  { name: 'Dirk Nowitzki', club: 'Mavericks', year: 2011, fame: 5, lo: 90, hi: 96, bioPt: 'O arremesso numa perna só, impossível de bloquear. O alemão que humilhou o Heat.', bioEn: 'The one-legged fadeaway, impossible to block. The German who humbled the Heat.' },
  { name: 'Giannis Antetokounmpo', club: 'Bucks', year: 2021, fame: 5, lo: 90, hi: 96, bioPt: 'Greek Freak. Do nada pra MVP e anel. Atravessa a quadra toda em 3 passos.', bioEn: 'Greek Freak. From nowhere to MVP and a ring. Crosses the whole floor in three steps.' },
  { name: 'Charles Barkley', club: 'Suns', year: 1993, fame: 4, lo: 86, hi: 93, bioPt: 'Round Mound of Rebound. 1,98m brigando com pivôs — e ganhando. MVP e boca solta.', bioEn: 'Round Mound of Rebound. 6\'6" fighting centers — and winning. MVP and loose lips.' },
  { name: 'Kevin Garnett', club: 'Timberwolves', year: 2004, fame: 4, lo: 86, hi: 92, bioPt: '"ANYTHING IS POSSIBLE!" Intensidade beirando a loucura e defesa que engolia todo mundo.', bioEn: '"ANYTHING IS POSSIBLE!" Intensity bordering on madness and defense that swallowed everyone.' },
  { name: 'Karl Malone', club: 'Jazz', year: 1997, fame: 4, lo: 86, hi: 92, bioPt: 'The Mailman — sempre entregava. Pick-and-roll eterno com o Stockton, só faltou o anel.', bioEn: 'The Mailman — always delivered. Eternal pick-and-roll with Stockton, just missing the ring.' },
  { name: 'Anthony Davis', club: 'Lakers', year: 2020, fame: 4, lo: 86, hi: 92, bioPt: 'The Brow. Toca o teto do garrafão, tapa tudo e a monocelha vira marca registrada.', bioEn: 'The Brow. Touches the top of the paint, blocks everything, unibrow and all.' },
  { name: 'Pau Gasol', club: 'Lakers', year: 2010, fame: 4, lo: 84, hi: 90, bioPt: 'Espanhol de mão macia — parceiro de anel do Kobe. Passe de pivô, técnica de armador.', bioEn: 'A soft-handed Spaniard — Kobe\'s ring partner. Big-man passing, guard\'s touch.' },
  { name: 'Zion Williamson', club: 'Pelicans', year: 2023, fame: 3, lo: 79, hi: 88, promessa: true, bioPt: '129 quilos que voam. A força da natureza que faz o aro tremer.', bioEn: '285 pounds that fly. A force of nature that makes the rim shake.' },
  { name: 'Dennis Rodman', club: 'Bulls', year: 1996, fame: 4, lo: 82, hi: 90, folk: true, bioPt: 'The Worm. Cabelo colorido, rebote insano e vestido de noiva no lançamento do livro.', bioEn: 'The Worm. Rainbow hair, insane rebounding and a wedding dress at his book launch.' },
  // ── Lote 2 ──
  { name: 'Draymond Green', club: 'Warriors', year: 2017, fame: 4, lo: 82, hi: 89, folk: true, bioPt: 'O cérebro e o barraco dos Warriors. Marca as 5 posições e distribui chute e soco.', bioEn: 'The brain and the drama of the Warriors. Guards all five spots and hands out kicks and punches.' },
  { name: 'Blake Griffin', club: 'Clippers', year: 2014, fame: 4, lo: 84, hi: 90, bioPt: 'Lob City. Enterrou POR CIMA de um carro no concurso. Pôster ambulante da geração.', bioEn: 'Lob City. Dunked OVER a car in the contest. The walking poster of his generation.' },
  { name: 'Kwame Brown', club: 'Wizards', year: 2003, fame: 1, lo: 50, hi: 70, folk: true, bioPt: '1ª escolha geral que o Jordan escolheu... e se arrependeu. O bust nº1 do manual.', bioEn: 'A No.1 overall pick Jordan himself chose... and regretted. The textbook bust.' },
  { name: 'Darko Miličić', club: 'Pistons', year: 2004, fame: 1, lo: 52, hi: 72, folk: true, bioPt: 'Escolhido na FRENTE de Melô, Wade E Bosh. O "e se?" mais caro da NBA.', bioEn: 'Drafted AHEAD of Melo, Wade AND Bosh. The most expensive "what if?" in the NBA.' },
  { name: 'Tiago Splitter', club: 'Spurs', year: 2014, fame: 2, lo: 70, hi: 84, folk: true, bioPt: 'Pivô brasileiro dos Spurs campeões de 2014. Sólido, discreto e com anel no dedo. 🇧🇷', bioEn: 'A Brazilian big on the 2014 champion Spurs. Solid, quiet and with a ring on his finger. 🇧🇷' },
  // -- Lote 3 --
  { name: "Chris Webber", club: "Kings", year: 2002, fame: 4, lo: 84, hi: 90, folk: true, bioPt: "C-Webb. Passe de pivô, enterrada furiosa e o timeout que não existia na final da faculdade 😬.", bioEn: "C-Webb. Big-man passing, furious dunks and the timeout that didn't exist in the college final 😬." },
  { name: "Kevin McHale", club: "Celtics", year: 1987, fame: 4, lo: 85, hi: 91, bioPt: "As melhores fintas de garrafão da história — braços de polvo. Bicampeão ao lado do Bird.", bioEn: "The greatest post moves ever — octopus arms. Two-time champ next to Bird." },
  { name: "Amar'e Stoudemire", club: "Suns", year: 2007, fame: 4, lo: 84, hi: 90, bioPt: "STAT (Standing Tall And Talented). Enterrada de martelo no alley-oop do Nash. Pura explosão.", bioEn: "STAT (Standing Tall And Talented). Hammer dunks off Nash lobs. Pure explosion." },
  { name: "Chris Bosh", club: "Heat", year: 2013, fame: 4, lo: 83, hi: 90, bioPt: "O terceiro do Big Three do Heat — bicampeão. Virou meme de foto, mas ganhou tudo.", bioEn: "The third of the Heat's Big Three — two-time champ. Became a photobomb meme, but won it all." },
  { name: "Zach Randolph", club: "Grizzlies", year: 2011, fame: 3, lo: 79, hi: 87, folk: true, bioPt: "Z-Bo. Grit and Grind de Memphis. Rebote no tapa e briga com quem aparecer.", bioEn: "Z-Bo. Memphis Grit and Grind. Rebounds by force and scraps with anyone." },
  { name: "Lamar Odom", club: "Lakers", year: 2010, fame: 3, lo: 79, hi: 87, folk: true, bioPt: "Canhoto versátil, bicampeão e melhor sexto homem. Vivia com um saco de balas no bolso 🍬.", bioEn: "A versatile lefty, two-time champ and Sixth Man of the Year. Always with a bag of candy in his pocket 🍬." },
  { name: "Elton Brand", club: "Clippers", year: 2006, fame: 3, lo: 79, hi: 87, bioPt: "Duplo-duplo garantido numa época que os Clippers eram piada. Sólido como concreto.", bioEn: "A double-double lock back when the Clippers were a punchline. Solid as concrete." },
  { name: "Antawn Jamison", club: "Wizards", year: 2008, fame: 2, lo: 76, hi: 85, bioPt: "Bandejas malucas e faro de rebote. 20 e 10 quietinho por anos a fio.", bioEn: "Wild scoop layups and a nose for the ball. A quiet 20-and-10 for years." },
  // -- Lote 4 --
  { name: "Shawn Kemp", club: "Sonics", year: 1996, fame: 4, lo: 83, hi: 90, folk: true, bioPt: "Reign Man. Enterradas de destruir tabela ao lado do Payton — e mais filhos do que dá pra contar 😅.", bioEn: "Reign Man. Backboard-shattering dunks next to Payton — and more kids than anyone can count 😅." },
  { name: "Larry Johnson (Grandmama)", club: "Hornets", year: 1993, fame: 3, lo: 80, hi: 88, folk: true, bioPt: "Grandmama — o comercial da vovó enterrando. O 4-point play que matou os Pacers. Puro carisma.", bioEn: "Grandmama — the grandma-dunking commercial. The four-point play that killed the Pacers. Pure charisma." },
  { name: "Antoine Walker", club: "Celtics", year: 2002, fame: 3, lo: 79, hi: 87, folk: true, bioPt: "O shimmy depois da bola de 3 (que ele adorava chutar). Ganhou fortuna, gastou tudo. Folclore puro.", bioEn: "The shimmy after every three (which he loved to chuck). Made a fortune, spent it all. Pure folklore." },
  { name: "Horace Grant", club: "Bulls", year: 1993, fame: 3, lo: 79, hi: 87, folk: true, bioPt: "Os óculos de proteção mais famosos da NBA. Trabalho sujo dos Bulls tricampeões e mais um anel no Lakers.", bioEn: "The most famous goggles in the NBA. Did the dirty work for the three-peat Bulls and grabbed another ring with the Lakers." },
  { name: "Chris Andersen (Birdman)", club: "Nuggets", year: 2009, fame: 2, lo: 74, hi: 84, folk: true, bioPt: "Birdman. Tatuagem da cabeça aos pés, moicano e tocos elétricos que levantavam a arena.", bioEn: "Birdman. Tattoos head to toe, a mohawk and electric blocks that shook the arena." },
  { name: "Kevin Love", club: "Cavaliers", year: 2016, fame: 3, lo: 80, hi: 88, bioPt: "O passe-outlet de 30 metros e o rebote garantido. O terceiro do Cleveland campeão de 2016.", bioEn: "The full-court outlet pass and the guaranteed rebound. The third man of the 2016 champion Cavs." },
  { name: "Al Horford", club: "Celtics", year: 2024, fame: 3, lo: 79, hi: 87, bioPt: "Big Al. 17 anos esperando — e enfim o anel em 2024. Sólido, silencioso e sempre no lugar certo.", bioEn: "Big Al. Seventeen years of waiting — and finally the ring in 2024. Solid, quiet, always in the right spot." },
  { name: "Rashard Lewis", club: "Magic", year: 2009, fame: 3, lo: 78, hi: 86, bioPt: "Ala-pivô que abriu a quadra de 3 antes de virar moda. Levou o Magic à final de 2009.", bioEn: "A stretch four who spaced the floor with threes before it was cool. Took the Magic to the 2009 Finals." },
  // ── Lote HOF (lendas do Hall da Fama) ──
  { name: "Bob Pettit", club: "Hawks", year: 1958, fame: 5, lo: 87, hi: 94, bioPt: "O primeiro MVP da história da NBA. Cravou 50 na final de 58 pra tirar o ÚNICO anel do Celtics do Russell.", bioEn: "The first MVP in NBA history. Dropped 50 in the 58 Finals to steal the ONE title from Russells Celtics." },
  { name: "Elvin Hayes", club: "Bullets", year: 1978, fame: 5, lo: 86, hi: 93, bioPt: "The Big E. Turnaround jumper indefensável e o pilar do Washington campeão de 1978. Nunca tirava um minuto.", bioEn: "The Big E. An unblockable turnaround jumper and anchor of the 1978 champion Bullets. Never took a minute off." },
  { name: "Dave DeBusschere", club: "Knicks", year: 1970, fame: 4, lo: 82, hi: 89, bioPt: "Músculo e defesa do Knicks campeão. Marcava o melhor ala do rival e ainda foi jogador E técnico ao mesmo tempo.", bioEn: "The muscle and defense of the champion Knicks. Guarded the rivals best wing — and once was player AND coach at once." },
  { name: "Jerry Lucas", club: "Royals", year: 1965, fame: 4, lo: 82, hi: 89, bioPt: "Reboteiro fenomenal e cabeça de outro mundo — decorava listas telefônicas por diversão. Anel com o Knicks em 73.", bioEn: "A phenomenal rebounder with a freak mind — memorized phone books for fun. Ring with the Knicks in 73." },
  { name: "Dan Issel", club: "Nuggets", year: 1977, fame: 4, lo: 82, hi: 89, bioPt: "The Horse. Nunca perdeu um jogo por lesão e despejava pontos em Denver, da ABA à NBA.", bioEn: "The Horse. Never missed a game to injury and poured in points in Denver, from the ABA to the NBA." },
  { name: "Spencer Haywood", club: "SuperSonics", year: 1973, fame: 4, lo: 82, hi: 89, bioPt: "O cara que processou a NBA e ABRIU a porta pros jovens entrarem cedo. Fera em Seattle e campeão com o Lakers em 80.", bioEn: "The man who sued the NBA and OPENED the door for young players. A beast in Seattle and a Lakers champ in 80." },
  // ── Lote HOF 2 (variedade: posições + categorias) ──
  { name: "Dolph Schayes", club: "Nationals", year: 1958, fame: 4, lo: 83, hi: 90, bioPt: "Pioneiro de dois tempos: reboteiro raçudo e um dos primeiros grandes arremessadores. Ícone de Syracuse.", bioEn: "A two-way pioneer: a gritty rebounder and one of the first great shooting big men. A Syracuse icon." },
  { name: "Bailey Howell", club: "Celtics", year: 1968, fame: 3, lo: 80, hi: 87, bioPt: "Ala-pivô durão e eficiente que somou anéis nos Celtics dos anos 60. Trabalho sujo com classe.", bioEn: "A tough, efficient forward who piled up rings on the 60s Celtics. Dirty work with class." },
  { name: "Derrick Coleman", club: "Nets", year: 1994, fame: 3, lo: 79, hi: 87, folk: true, bioPt: "DC. Talento pra ser top-5 histórico — e o 'whoop-dee-damn-doo' que virou lenda do talento desperdiçado.", bioEn: "DC. Talent to be an all-time top-5 — and the whoop-dee-damn-doo that became the anthem of wasted potential." },
  { name: "Julius Randle", club: "Knicks", year: 2021, fame: 3, lo: 79, hi: 87, bioPt: "Locomotiva canhota que empurra o garrafão inteiro. Ressurgiu e levou o Knicks de volta aos playoffs.", bioEn: "A lefty locomotive who bulldozes the whole paint. Resurfaced and dragged the Knicks back to the playoffs." },
  { name: "Pascal Siakam", club: "Raptors", year: 2019, fame: 3, lo: 80, hi: 88, bioPt: "Spicy P. De caçula desconhecido do Camarões a peça de título em Toronto (2019). Puro crescimento.", bioEn: "Spicy P. From unknown Cameroonian kid to title piece in Toronto (2019). Pure development." },
  { name: "Aaron Gordon", club: "Nuggets", year: 2023, fame: 2, lo: 76, hi: 86, folk: true, bioPt: "A vítima do maior roubo da história do concurso de enterradas — e enfim campeão com o Jokić em 2023.", bioEn: "The victim of the greatest dunk-contest robbery ever — and finally a champion with Jokić in 2023." },
  { name: "Paolo Banchero", club: "Magic", year: 2024, fame: 3, lo: 77, hi: 88, promessa: true, bioPt: "Grandão que dribla, passa e pontua como ala. A esperança nº1 de Orlando pro futuro.", bioEn: "A big man who dribbles, passes and scores like a wing. Orlandos number-one hope for the future." },
  { name: "Kurt Rambis", club: "Lakers", year: 1985, fame: 2, lo: 72, hi: 83, folk: true, bioPt: "Óculos, bigode e faxina no garrafão do Showtime. O operário que a galera amava (e o Kevin McHale odiava).", bioEn: "Glasses, mustache and garbage work in the Showtime paint. The blue-collar guy fans loved (and McHale clotheslined)." },
  { name: "Anthony Bennett", club: "Cavaliers", year: 2013, fame: 1, lo: 55, hi: 80, folk: true, bioPt: "O nº1 do draft que virou sinônimo de fracasso. Saiu da NBA em 3 anos. O maior bust da história recente.", bioEn: "The number-one pick who became a synonym for failure. Out of the NBA in three years. The biggest recent bust." },
  // ── Lote 4 (modernos + variedade) ──
  { name: "Evan Mobley", club: "Cavaliers", year: 2024, fame: 3, lo: 78, hi: 87, promessa: true, bioPt: "Braços infinitos, toco em tudo e toque macio — Defensor do Ano em construção.", bioEn: "Endless arms, blocks everything, soft touch — a Defensive Player of the Year in the making." },
  { name: "Terry Cummings", club: "Bucks", year: 1985, fame: 3, lo: 80, hi: 87, bioPt: "Força bruta e motor no garrafão — Novato do Ano e reboteiro implacável.", bioEn: "Brute force and motor in the paint — Rookie of the Year and a relentless rebounder." },
  { name: "Larry Nance", club: "Suns", year: 1984, fame: 3, lo: 79, hi: 86, folk: true, bioPt: "O PRIMEIRO campeão do concurso de enterradas (1984). Voava e dava toco de sobra.", bioEn: "The FIRST-ever dunk contest champion (1984). Flew and swatted with ease." },
  { name: "Marvin Bagley III", club: "Kings", year: 2019, fame: 1, lo: 58, hi: 80, folk: true, bioPt: "Draftado na frente do Doncic e do Trae. As lesões escreveram o resto. Que se?", bioEn: "Drafted ahead of Doncic and Trae. Injuries wrote the rest. What a what-if." },
]

// ─── C · PIVÔ ────────────────────────────────────────────────────────
const C: BC[] = [
  { name: "Shaquille O'Neal", club: 'Lakers', year: 2000, fame: 5, lo: 92, hi: 98, bioPt: 'The Diesel. Quebrava tabela e tanque de guerra. Imparável por dentro, péssimo no lance livre.', bioEn: 'The Diesel. Broke backboards and tanks. Unstoppable inside, hopeless at the line.' },
  { name: 'Kareem Abdul-Jabbar', club: 'Lakers', year: 1980, fame: 5, lo: 92, hi: 98, bioPt: 'O gancho-céu que ninguém nunca bloqueou. Maior pontuador da liga por 39 anos.', bioEn: 'The sky-hook nobody ever blocked. All-time scoring king for 39 years.' },
  { name: 'Hakeem Olajuwon', club: 'Rockets', year: 1994, fame: 5, lo: 91, hi: 97, bioPt: 'The Dream. O Dream Shake deixava pivôs no chão. Bicampeão e xerife da área.', bioEn: 'The Dream. A Dream Shake that left centers on the floor. Two rings and paint sheriff.' },
  { name: 'Nikola Jokić', club: 'Nuggets', year: 2023, fame: 5, lo: 90, hi: 96, bioPt: 'The Joker. Parece que nem corre, mas é MVP e passa como armador de 2,11m.', bioEn: 'The Joker. Looks like he never runs, yet he\'s an MVP passing like a 6\'11" point guard.' },
  { name: 'Wilt Chamberlain', club: 'Warriors', year: 1962, fame: 5, lo: 90, hi: 97, bioPt: '100 pontos NUM jogo. 50 de média numa temporada. Números de videogame com bug.', bioEn: '100 points in ONE game. 50 a night for a season. Glitched-videogame numbers.' },
  { name: 'Bill Russell', club: 'Celtics', year: 1965, fame: 5, lo: 89, hi: 96, bioPt: '11 anéis. ONZE. Ganhou mais que qualquer um e nunca deixou esquecer a defesa.', bioEn: '11 rings. ELEVEN. Won more than anyone and never let you forget the defense.' },
  { name: 'David Robinson', club: 'Spurs', year: 1995, fame: 4, lo: 87, hi: 93, bioPt: 'The Admiral. Militar, MVP e tampão. Passou o bastão pro Duncan e faturou os anéis.', bioEn: 'The Admiral. Navy man, MVP and shot-blocker. Passed the torch to Duncan and got his rings.' },
  { name: 'Patrick Ewing', club: 'Knicks', year: 1994, fame: 4, lo: 85, hi: 92, bioPt: 'O suadão que carregou Nova York nas costas. Faltou só o anel — culpa do Jordan.', bioEn: 'The sweaty giant who carried New York. Just missing a ring — blame Jordan.' },
  { name: 'Yao Ming', club: 'Rockets', year: 2007, fame: 4, lo: 84, hi: 91, bioPt: '2,29m que abriram a NBA pra China inteira. Gigante gentil com toque macio.', bioEn: 'Seven-foot-six that opened the NBA to all of China. A gentle giant with a soft touch.' },
  { name: 'Dikembe Mutombo', club: 'Nuggets', year: 1995, fame: 3, lo: 80, hi: 88, folk: true, bioPt: 'Não. NÃO. O dedo mais famoso da NBA depois de cada toco no adversário.', bioEn: 'No. NO. The most famous finger wag in the NBA after every block.' },
  { name: 'Victor Wembanyama', club: 'Spurs', year: 2024, fame: 3, lo: 80, hi: 90, promessa: true, bioPt: 'O alienígena. 2,24m que enterra, crava toco e acerta de três. O futuro chegou cedo.', bioEn: 'The alien. 7-foot-4 that dunks, swats and drains threes. The future came early.' },
  { name: 'Boban Marjanović', club: 'Clippers', year: 2019, fame: 1, lo: 58, hi: 78, folk: true, bioPt: 'Mãos do tamanho da sua cara. Faz a bola de basquete parecer bolinha de tênis.', bioEn: 'Hands the size of your face. Makes a basketball look like a tennis ball.' },
  // ── Lote 2 ──
  { name: 'Nenê', club: 'Nuggets', year: 2011, fame: 3, lo: 78, hi: 86, folk: true, bioPt: 'O primeiro brasileiro escolhido no top 10 do draft. Força, técnica e 18 anos de NBA. 🇧🇷', bioEn: 'The first Brazilian picked in the draft top 10. Strength, skill and 18 NBA seasons. 🇧🇷' },
  { name: 'Rudy Gobert', club: 'Jazz', year: 2021, fame: 3, lo: 80, hi: 88, folk: true, bioPt: 'Melhor defensor 4x. Ficou famoso por tocar TODOS os microfones bem no começo da pandemia 😷.', bioEn: '4x Defensive Player of the Year. Got famous for touching EVERY mic right as the pandemic hit 😷.' },
  { name: 'DeAndre Jordan', club: 'Clippers', year: 2015, fame: 3, lo: 78, hi: 86, bioPt: 'Lob City no ar, pesadelo no lance livre. Rei do alley-oop do Chris Paul.', bioEn: 'Lob City in the air, a nightmare at the line. King of the Chris Paul alley-oop.' },
  { name: 'Bill Laimbeer', club: 'Pistons', year: 1990, fame: 3, lo: 76, hi: 85, folk: true, bioPt: 'O vilão dos Bad Boys que todo mundo adorava odiar. Cotovelada com sorriso. Bicampeão.', bioEn: 'The Bad Boys villain everyone loved to hate. An elbow with a smile. Two-time champ.' },
  { name: 'Manute Bol', club: 'Bullets', year: 1986, fame: 1, lo: 54, hi: 74, folk: true, bioPt: '2,31m, o mais alto da história. Tocava tudo e ainda arriscava bola de 3. Folclore vivo.', bioEn: 'Seven-foot-seven, the tallest ever. Blocked everything and still chucked threes. Living folklore.' },
  { name: 'Shawn Bradley', club: 'Mavericks', year: 1998, fame: 1, lo: 54, hi: 74, folk: true, bioPt: '2,29m que virou o pôster favorito de todo mundo — levou enterrada de meio mundo.', bioEn: 'Seven-foot-six who became everyone\'s favorite poster — got dunked on by half the league.' },
  { name: 'Greg Oden', club: 'Blazers', year: 2009, fame: 1, lo: 56, hi: 78, folk: true, bioPt: 'Escolhido na frente do Durant. Os joelhos roubaram a carreira antes de começar. O maior "e se?".', bioEn: 'Picked ahead of Durant. His knees stole the career before it began. The great "what if?".' },
  // -- Lote 3 --
  { name: "Moses Malone", club: "Sixers", year: 1983, fame: 5, lo: 88, hi: 94, bioPt: "'Fo', Fo', Fo'.' Rei do rebote de ataque e MVP que carregou o Sixers ao anel. Trabalhador incansável.", bioEn: "'Fo', Fo', Fo'.' King of the offensive board and an MVP who carried the Sixers to a ring. A tireless worker." },
  { name: "Alonzo Mourning", club: "Heat", year: 2000, fame: 4, lo: 84, hi: 90, bioPt: "Zo. Cara de bravo, toco atrás de toco e uma volta por cima após transplante de rim. Guerreiro.", bioEn: "Zo. An angry face, block after block and a comeback after a kidney transplant. A warrior." },
  { name: "Ben Wallace (Big Ben)", club: "Pistons", year: 2004, fame: 4, lo: 82, hi: 89, folk: true, bioPt: "Big Ben. Não-draftado que virou 4x melhor defensor. O afro e a muralha do Detroit campeão.", bioEn: "Big Ben. An undrafted center who became 4x Defensive Player of the Year. The afro and the wall of champion Detroit." },
  { name: "Dwight Howard", club: "Magic", year: 2009, fame: 4, lo: 84, hi: 90, folk: true, bioPt: "Superman. Voou de capa no concurso e dominou o garrafão. Melhor defensor 3x — e mil risadas.", bioEn: "Superman. Flew in with a cape at the contest and owned the paint. 3x Defensive Player of the Year — and a thousand laughs." },
  { name: "Joel Embiid", club: "Sixers", year: 2023, fame: 4, lo: 85, hi: 92, bioPt: "The Process. MVP camaronês que digita meme no Twitter e domina o garrafão. Confia no processo.", bioEn: "The Process. A Cameroonian MVP who tweets memes and rules the paint. Trust the process." },
  { name: "Marc Gasol", club: "Grizzlies", year: 2013, fame: 3, lo: 80, hi: 88, bioPt: "O irmão espanhol que virou melhor defensor e campeão. Passe de armador num corpo de pivô.", bioEn: "The Spanish brother who became Defensive Player of the Year and a champion. Point-guard passing in a center's body." },
  { name: "Robert Parish (The Chief)", club: "Celtics", year: 1986, fame: 4, lo: 83, hi: 90, bioPt: "The Chief. O pivô mais durão e longevo — recordista de jogos. Tricampeão calado ao lado de Bird e McHale.", bioEn: "The Chief. The toughest, most durable big — the all-time games leader. A quiet three-time champ beside Bird and McHale." },
  { name: "Bill Walton", club: "Blazers", year: 1977, fame: 4, lo: 83, hi: 90, folk: true, bioPt: "Gênio do passe de pivô e MVP campeão — quando os pés deixavam. Depois, o narrador mais doido da TV.", bioEn: "A genius passing big and an MVP champion — when his feet allowed. Later, the wildest broadcaster on TV." },
  // -- Lote 4 --
  { name: "Willis Reed", club: "Knicks", year: 1970, fame: 4, lo: 83, hi: 90, folk: true, bioPt: "Mancando, entrou em quadra no Jogo 7 e eletrizou o Garden. O momento mais heroico dos Knicks.", bioEn: "Limping, he walked out for Game 7 and electrified the Garden. The most heroic moment in Knicks history." },
  { name: "Wes Unseld", club: "Bullets", year: 1978, fame: 4, lo: 82, hi: 89, bioPt: "Parede de tijolos com o melhor passe-outlet da história. MVP de novato E de final. Rebote e osso.", bioEn: "A brick wall with the best outlet pass ever. Rookie MVP AND Finals MVP. Rebounds and bone." },
  { name: "Vlade Divac", club: "Kings", year: 2002, fame: 3, lo: 79, hi: 87, folk: true, bioPt: "Pioneiro do flop e do passe de pivô sérvio. Charuto, carisma e o coração dos Kings queridinhos.", bioEn: "Pioneer of the flop and the Serbian passing big. Cigars, charisma and the heart of the beloved Kings." },
  { name: "Arvydas Sabonis", club: "Blazers", year: 1996, fame: 3, lo: 80, hi: 88, folk: true, bioPt: "Gênio lituano que chegou VELHO e machucado à NBA — e ainda era genial. Imagina o Sabonis inteiro.", bioEn: "A Lithuanian genius who reached the NBA old and injured — and was still brilliant. Imagine a healthy Sabonis." },
  { name: "Andrew Bynum", club: "Lakers", year: 2011, fame: 2, lo: 74, hi: 85, folk: true, bioPt: "Bicampeão jovem com talento de titular da liga... e joelhos e cabeça que jogaram tudo fora. O e se? preguiçoso.", bioEn: "A young two-time champ with All-NBA talent... and knees and a mind that threw it all away. The lazy what-if." },
  { name: "Rik Smits", club: "Pacers", year: 1998, fame: 3, lo: 78, hi: 86, folk: true, bioPt: "The Dunking Dutchman. 2,24m que decidia jogos de gancho ao lado do Reggie Miller.", bioEn: "The Dunking Dutchman. Seven-foot-four deciding games with hooks next to Reggie Miller." },
  { name: "Marcin Gortat", club: "Wizards", year: 2015, fame: 2, lo: 74, hi: 84, folk: true, bioPt: "The Polish Hammer. Pick-and-roll martelado e tuítes engraçados. Faz o trabalho pesado sorrindo.", bioEn: "The Polish Hammer. Hammering pick-and-rolls and funny tweets. Does the dirty work with a grin." },
  { name: "Bam Adebayo", club: "Heat", year: 2020, fame: 3, lo: 80, hi: 88, bioPt: "O toco no LeBron na bolha que virou pôster ao contrário. Defende as 5 posições com raça de Miami.", bioEn: "The block on LeBron in the bubble that became a reverse poster. Guards all five spots with Miami grit." },
  // ── Lote HOF (lendas do Hall da Fama) ──
  { name: "George Mikan", club: "Lakers", year: 1950, fame: 5, lo: 86, hi: 94, bioPt: "O PRIMEIRO superastro do basquete. Tão dominante que mudaram as regras por causa dele. 5 títulos em Minneapolis.", bioEn: "Basketballs FIRST superstar. So dominant they changed the rules because of him. 5 titles in Minneapolis." },
  { name: "Nate Thurmond", club: "Warriors", year: 1967, fame: 4, lo: 84, hi: 91, bioPt: "Nate the Great. Defensor e reboteiro monstro — autor do primeiro quádruplo-duplo oficial da NBA.", bioEn: "Nate the Great. A monster defender and rebounder — author of the NBAs first official quadruple-double." },
  { name: "Dave Cowens", club: "Celtics", year: 1973, fame: 4, lo: 84, hi: 91, bioPt: "Pivô ruivo de raça infinita e MVP em 1973. Corria como armador e brigava embaixo como se fosse 2,20m.", bioEn: "A red-headed center of infinite hustle and 1973 MVP. Ran like a guard and battled inside like a seven-footer." },
  { name: "Bob McAdoo", club: "Braves", year: 1975, fame: 4, lo: 84, hi: 91, bioPt: "Pivô com mira de armador. MVP e tricampeão de cestinha em Buffalo antes de faturar anéis com o Showtime.", bioEn: "A center with a guards jumper. MVP and three-time scoring champ in Buffalo before winning rings with Showtime." },
  { name: "Artis Gilmore", club: "Bulls", year: 1982, fame: 4, lo: 83, hi: 90, bioPt: "The A-Train. Gigante barbudo com o maior aproveitamento de arremesso da história. Dominou a ABA e a NBA.", bioEn: "The A-Train. A bearded giant with the best field-goal percentage in history. Dominated the ABA and the NBA." },
  { name: "Bob Lanier", club: "Pistons", year: 1974, fame: 4, lo: 83, hi: 90, bioPt: "Canhoto gigante de jogo macio e o pé mais famoso da NBA. Poste refinado em Detroit e Milwaukee.", bioEn: "A giant lefty with a soft touch and the most famous shoe size in the NBA. A refined post threat in Detroit and Milwaukee." },
  { name: "Ralph Sampson", club: "Rockets", year: 1985, fame: 3, lo: 80, hi: 88, bioPt: "2,24m de talento raro nas Twin Towers com o Hakeem. Os joelhos roubaram o que podia ter sido lendário.", bioEn: "Seven-foot-four of rare talent in the Twin Towers with Hakeem. His knees stole what could have been legendary." },
  // ── Lote HOF 2 (variedade: posições + categorias) ──
  { name: "Domantas Sabonis", club: "Kings", year: 2023, fame: 3, lo: 80, hi: 88, bioPt: "Filho do Arvydas, virou duplo-duplo garantido e cotovelo de armador. Ressuscitou Sacramento.", bioEn: "Arvydas son, a walking double-double with a passing big man's elbow. Revived Sacramento." },
  { name: "Jaren Jackson Jr", club: "Grizzlies", year: 2023, fame: 3, lo: 79, hi: 87, bioPt: "Block Panther. Defensor do Ano que carimba tudo e ainda acerta de três. O muro de Memphis.", bioEn: "Block Panther. A Defensive Player of the Year who swats everything and drains threes. Memphis wall." },
  { name: "Chet Holmgren", club: "Thunder", year: 2024, fame: 3, lo: 77, hi: 88, promessa: true, bioPt: "Espantalho de 2,13m que enterra, dá toco e acerta de fora. Frágil na aparência, gigante no jogo.", bioEn: "A seven-foot scarecrow who dunks, blocks and shoots from deep. Frail-looking, giant in the game." },
  { name: "Bill Cartwright", club: "Bulls", year: 1991, fame: 3, lo: 78, hi: 86, folk: true, bioPt: "Mr. Bill. O pivô veterano e cotoveludo que deu a estrutura pro primeiro tri do Bulls do Jordan.", bioEn: "Mr. Bill. The elbowy veteran center who gave structure to the first Jordan-era Bulls three-peat." },
  { name: "Sam Bowie", club: "Blazers", year: 1985, fame: 1, lo: 58, hi: 82, folk: true, bioPt: "O cara que o Portland draftou na frente do Michael Jordan. As pernas de vidro escreveram o resto.", bioEn: "The man Portland drafted ahead of Michael Jordan. His glass legs wrote the rest of the story." },
  { name: "Michael Olowokandi", club: "Clippers", year: 2002, fame: 1, lo: 56, hi: 80, folk: true, bioPt: "The Kandi Man. Nº1 do draft de 98 na frente de craques. Virou aula de como NÃO escolher no draft.", bioEn: "The Kandi Man. Number-one pick of 98 ahead of stars. Became a lesson in how NOT to draft." },
  { name: "Hasheem Thabeet", club: "Grizzlies", year: 2010, fame: 1, lo: 55, hi: 79, folk: true, bioPt: "2,21m escolhido em 2º lugar que mal jogou. Foi rebaixado pra liga de desenvolvimento sendo top pick.", bioEn: "Seven-foot-three, picked second, barely played. Got demoted to the D-League as a top pick." },
  { name: "Tacko Fall", club: "Celtics", year: 2020, fame: 1, lo: 60, hi: 80, folk: true, bioPt: "2,26m de fofura senegalesa. Não precisava pular pra tocar o aro. Xodó absoluto da torcida.", bioEn: "Seven-foot-six of Senegalese sweetness. Didn't need to jump to touch the rim. An absolute fan favorite." },
  // ── Lote 4 (modernos + variedade) ──
  { name: "Alperen Sengun", club: "Rockets", year: 2024, fame: 3, lo: 78, hi: 87, promessa: true, bioPt: "Baby Jokic. Cotovelo de armador num pivô turco — passe mágico e faro de cesta.", bioEn: "Baby Jokic. A point guards elbow on a Turkish center — magic passing and a nose for the bucket." },
  { name: "Jack Sikma", club: "SuperSonics", year: 1982, fame: 3, lo: 80, hi: 87, bioPt: "Cabelo enrolado e o step-back de pivô que virou aula. Campeão e HOF em Seattle.", bioEn: "Curly hair and the big-man step-back that became a teaching tool. Champion and HOFer in Seattle." },
  { name: "Brook Lopez", club: "Bucks", year: 2021, fame: 3, lo: 79, hi: 86, bioPt: "Splash Mountain. Pivô que virou muralha de três e toco — âncora do título de 2021.", bioEn: "Splash Mountain. A center turned three-point wall and shot-blocker — anchor of the 2021 title." },
  { name: "Timofey Mozgov", club: "Lakers", year: 2017, fame: 1, lo: 60, hi: 80, folk: true, bioPt: "O russo que ficou famoso pelo CONTRATO de 64 milhões — e por um pôster do Blake Griffin.", bioEn: "The Russian famous for his 64-million-dollar CONTRACT — and a Blake Griffin poster." },
]

// catálogo por posição — mesma forma do futebol (Record<posição, cartas[]>)
export const CATALOG_NBA: Record<BPos, BC[]> = { PG, SG, SF, PF, C }

// conjunto de nomes que são PROMESSA (pro tier 💎) — igual ao PROMESSA_SET do futebol
export const PROMESSA_SET_NBA = new Set(
  Object.values(CATALOG_NBA).flat().filter(c => c.promessa).map(c => c.name),
)

// total colecionável do Lote 1 (cada nome|franquia|ano conta uma vez)
export const NBA_TOTAL = new Set(
  Object.values(CATALOG_NBA).flat().map(c => `${c.name}|${c.club}|${c.year}`),
).size
