// ─── 📢 NOVIDADES DO JOGO — a lista ÚNICA (Diego 16/08) ──────────────────
//
// Regras que o Diego deu, em ordem de importância:
//
// 1. **TODA novidade do jogo entra aqui, sozinha.** Ligou uma coisa nova pro
//    pessoal? A mesma entrega que liga escreve a linha aqui. Não existe
//    "depois eu aviso" — o que não está aqui, ninguém fica sabendo.
// 2. **BUG NUNCA ENTRA.** *"Menos bugs q nunca lance"*. Conserto não é
//    novidade: quem joga não quer ler que alguma coisa estava quebrada. Se a
//    entrega é só conserto, ela NÃO ganha linha aqui — vai pro
//    `docs/pendencias.md` e pro commit, que é onde isso mora.
// 3. **Novidade não fica pra sempre.** A tela mostra só o que é RECENTE e some
//    sozinho com o tempo (ver `novidadesDaVez` embaixo). Antes eram 17 avisos
//    empilhados, alguns de meses atrás — virou um paredão que ninguém lia.
//
// Como escrever a linha: o QUE mudou pra quem joga, em uma frase, com o modo
// entre parênteses. Sem tecniquês, sem nome de arquivo, sem "implementamos".
export interface Novidade {
  /** dia em que ISSO ficou disponível pra galera (YYYY-MM-DD) — é o que faz a lista encolher sozinha */
  data: string
  emoji: string
  titulo: string
  /** uma frase. Se não couber numa frase, provavelmente são duas novidades. */
  texto: string
  /** 🌐 a MESMA novidade em inglês (12/09: o jogo é BR/EN). Toda linha nova nasce com `en`;
   *  se faltar, a tela em EN mostra o PT — não quebra, só fica em português. */
  en?: { titulo: string; texto: string }
}
// 🌐 o que a tela lê, no idioma da vez (PT é o padrão e sempre existe)
export const novTitulo = (n: Novidade): string => (getLang() === 'en' && n.en ? n.en.titulo : n.titulo)
export const novTexto = (n: Novidade): string => (getLang() === 'en' && n.en ? n.en.texto : n.texto)

import { getLang } from './lang'

// ⚠️ SEMPRE em ordem: a mais NOVA em cima.
export const NOVIDADES: Novidade[] = [
  { data: '2026-09-12', emoji: '⚡', titulo: 'O pênalti decisivo ficou de verdade', texto: 'Aquele pênalti no fim do jogo agora acontece num estádio de verdade: você escolhe o canto, trava a força na barra e vê o goleiro voar. Antes era só o resultado na tela. (Carreira)', en: { titulo: 'The decisive penalty got real', texto: 'That late penalty now happens in a real stadium: you pick the corner, lock the power on the bar and watch the keeper dive. Before it was just the result on screen. (Career)' } },
  { data: '2026-09-12', emoji: '📲', titulo: 'As imagens de compartilhar ficaram iguais ao jogo', texto: 'A figura do jornal O Martelo e a do seu elenco agora saem com a cara que o jogo tem hoje: escudo, manto, mascote e os rostos das lendas. E saem no idioma que você escolheu. (Carreira)', en: { titulo: 'The share images now look like the game', texto: 'The O Martelo newspaper image and your squad image now come out with the look the game has today: crest, kit, mascot and the legends\' faces. And they come out in the language you picked. (Career)' } },
  { data: '2026-09-11', emoji: '🌍', titulo: 'A Copa do Mundo é do clube principal', texto: 'Quem tem um segundo clube comprado: agora só o seu clube principal disputa a Copa do Mundo — é ele que conta no ranking global, e é ele que vai. O segundo clube segue normal em tudo o mais: liga, copas, mercado e patrimônio. (Carreira)', en: { titulo: 'The World Cup belongs to your main club', texto: 'If you bought a second club: now only your main club plays the World Cup — it\'s the one that counts in the global ranking, and it\'s the one that goes. The second club carries on as usual in everything else: league, cups, market and assets. (Career)' } },
  { data: '2026-09-10', emoji: '⚽', titulo: 'As lendas ganharam rosto', texto: 'Avatares das lendas no campinho, nas cartas e na revelação do leilão, junto do novo visual da carreira: patrocínios, estádio, placares, ligas, copas e jornal. (Carreira, Rápido e Minhas Ligas)', en: { titulo: 'The legends got a face', texto: 'Legend avatars on the pitch, on the cards and at the auction reveal, together with the new career look: sponsorships, stadium, scoreboards, leagues, cups and newspaper. (Career, Quick and My Leagues)' } },
  { data: '2026-09-10', emoji: '🐮', titulo: 'Nasceu o Leite de Verdade FC', texto: 'Mais um clube batizado por apoiador: o Leite de Verdade FC chega na Série A, com escudo do curral, manto creme e preto malhado com dourado e mascote própria — a Mimosa, a vaca de chapéu de palha que carimba a tela quando o time faz gol. O Barcenite FC segue no jogo, agora na Série B. (Carreira e Rápido)', en: { titulo: 'Leite de Verdade FC is born', texto: 'One more club named by a supporter: Leite de Verdade FC arrives in Série A, with a barnyard crest, a cream and black spotted kit with gold and its own mascot — Mimosa, the straw-hat cow that stamps the screen when the team scores. Barcenite FC stays in the game, now in Série B. (Career and Quick)' } },
  { data: '2026-09-09', emoji: '🐍', titulo: 'Tricolor do Arruda FC de cara nova', texto: 'O Tricolor do Arruda FC, clube batizado por apoiador, está de cara nova: o estádio do Arruda no escudo, manto tricolor com as cores medidas na camisa e a Cobra Coral de punhos fechados, que carimba a tela quando o time faz gol. (Carreira e Rápido)', en: { titulo: 'Tricolor do Arruda FC has a new look', texto: 'Tricolor do Arruda FC, a club named by a supporter, has a new look: the Arruda stadium on the crest, a tricolor kit with the colors measured on the shirt and the Coral Snake with clenched fists, which stamps the screen when the team scores. (Career and Quick)' } },
  { data: '2026-09-09', emoji: '🟢', titulo: 'Xurupitas FC de cara nova', texto: 'O Xurupitas FC, clube batizado por apoiador, está de cara nova: escudo novo, manto verde-escuro e creme com a gosma escorrendo e mascote própria — o Xurupita, a gosma verde de sorriso maroto, que carimba a tela quando o time faz gol. (Carreira e Rápido)', en: { titulo: 'Xurupitas FC has a new look', texto: 'Xurupitas FC, a club named by a supporter, has a new look: new crest, dark green and cream kit with dripping slime and its own mascot — Xurupita, the green slime with a cheeky grin, which stamps the screen when the team scores. (Career and Quick)' } },
  { data: '2026-09-09', emoji: '🐛', titulo: 'Bicho da Seda de cara nova', texto: 'O Bicho da Seda, clube batizado por apoiador, está de cara nova: escudo novo, manto alvinegro com os fios de seda e mascote própria — o Bicho da Seda de óculos escuros, que carimba a tela quando o time faz gol. (Carreira e Rápido)', en: { titulo: 'Bicho da Seda has a new look', texto: 'Bicho da Seda, a club named by a supporter, has a new look: new crest, black-and-white kit with silk threads and its own mascot — the Silkworm in sunglasses, which stamps the screen when the team scores. (Career and Quick)' } },
  { data: '2026-09-09', emoji: '🐟', titulo: 'Nasceu o Bagres de Wall Street FC', texto: 'Mais um clube batizado por apoiador: o Bagres de Wall Street FC chega na Série A, com escudo de bolsa de valores, manto preto e dourado com listras brancas e mascote própria — o Bagre Investidor, de terno, coroa e charuto, que carimba a tela quando o time faz gol. O Manfré FC segue no jogo, agora na Série B. (Carreira e Rápido)', en: { titulo: 'Bagres de Wall Street FC is born', texto: 'One more club named by a supporter: Bagres de Wall Street FC arrives in Série A, with a stock-exchange crest, a black and gold kit with white stripes and its own mascot — the Investor Catfish, in suit, crown and cigar, which stamps the screen when the team scores. Manfré FC stays in the game, now in Série B. (Career and Quick)' } },
  { data: '2026-09-08', emoji: '🏆', titulo: 'Acompanhe a sala inteira', texto: 'Placares animados, Jogos + Tabela juntos e Copas organizadas por fase, com gols dos outros jogos e pênaltis compactos, no celular e no computador. (Online)', en: { titulo: 'Follow the whole room', texto: 'Animated scoreboards, Matches + Table together and Cups organized by stage, with goals from the other matches and compact penalties, on phone and computer. (Online)' } },
  { data: '2026-09-09', emoji: '🙏', titulo: 'Nasceu o Só Deus Sabe FC', texto: 'Mais um clube batizado por apoiador: o Só Deus Sabe FC chega na Série A, com escudo das mãos em prece, manto preto e dourado com nuvens brancas e mascote própria — o Anjo, que cai de joelhos no gramado e carimba a tela quando o time faz gol. O Nightfull FC segue no jogo, agora na Série B. (Carreira e Rápido)', en: { titulo: 'Só Deus Sabe FC is born', texto: 'One more club named by a supporter: Só Deus Sabe FC arrives in Série A, with a praying-hands crest, a black and gold kit with white clouds and its own mascot — the Angel, who drops to his knees on the pitch and stamps the screen when the team scores. Nightfull FC stays in the game, now in Série B. (Career and Quick)' } },
  { data: '2026-09-09', emoji: '🎙️', titulo: 'Nasceu o Fala D10', texto: 'Mais um clube batizado por apoiador: o Fala D10 chega na Série A, com escudo preto e dourado, manto preto com detalhes dourados e mascote própria — o D10, de megafone na mão, que carimba a tela quando o time faz gol. O Skyy FC segue no jogo, agora na Série D. (Carreira e Rápido)', en: { titulo: 'Fala D10 is born', texto: 'One more club named by a supporter: Fala D10 arrives in Série A, with a black and gold crest, a black kit with gold details and its own mascot — D10, megaphone in hand, who stamps the screen when the team scores. Skyy FC stays in the game, now in Série D. (Career and Quick)' } },
  { data: '2026-09-09', emoji: '🔊', titulo: 'Nasceu o Bonança SSFC', texto: 'Mais um clube batizado por apoiador: o Bonança SSFC chega na Série C, com escudo do paredão de caixas de som, manto preto e amarelo com listra vermelha e mascote própria — o Selecta, o paredão de camisa 10 que carimba a tela quando o time faz gol. (Carreira e Rápido)', en: { titulo: 'Bonança SSFC is born', texto: 'One more club named by a supporter: Bonança SSFC arrives in Série C, with a speaker-wall crest, a black and yellow kit with a red stripe and its own mascot — Selecta, the speaker wall in the number 10 shirt that stamps the screen when the team scores. (Career and Quick)' } },
  { data: '2026-09-08', emoji: '🐓', titulo: 'Nasceu o Briga de Galo FC', texto: 'Mais um clube batizado por apoiador: o Briga de Galo FC chega na Série A, com escudo dos dois galos, manto preto e branco listrado com dourado e mascote própria — o Galo de punhos fechados, que carimba a tela quando o time faz gol. O Vasco da Grana segue no jogo, agora na Série D. (Carreira e Rápido)', en: { titulo: 'Briga de Galo FC is born', texto: 'One more club named by a supporter: Briga de Galo FC arrives in Série A, with a two-roosters crest, a black and white striped kit with gold and its own mascot — the Rooster with clenched fists, who stamps the screen when the team scores. Vasco da Grana stays in the game, now in Série D. (Career and Quick)' } },
  { data: '2026-09-08', emoji: '🎁', titulo: 'Dono de batismo leva o escudo pra qualquer nome', texto: 'Quem tem clube batizado agora carrega escudo, mascote e manto no time que estiver usando, mesmo que troque o nome. É pelo e-mail do dono — o clube batizado continua no baralho com o nome fixo de sempre. (Carreira, Rápido e Online)', en: { titulo: 'Club founders keep their crest under any name', texto: 'Whoever owns a named club now carries crest, mascot and kit on whatever team they are using, even after renaming it. It follows the owner\'s e-mail — the named club stays in the deck with its usual fixed name. (Career, Quick and Online)' } },
  { data: '2026-09-08', emoji: '⏱️', titulo: 'Convocação da Copa do Mundo: 80 segundos', texto: 'Na Copa do Mundo online (sala de Copa, Liga + Mundo e ligas), o tempo pra convocar os 11 da seleção passou a ser 80 segundos — antes eram 135. Continua avançando na hora em que todo mundo fecha o time; o relógio é só o teto pra quem dorme. (Online)', en: { titulo: 'World Cup call-up: 80 seconds', texto: 'In the online World Cup (Cup room, League + World and leagues), the time to call up the national team\'s 11 is now 80 seconds — it used to be 135. It still moves on the moment everyone closes their team; the clock is just the ceiling for whoever dozes off. (Online)' } },
  { data: '2026-09-07', emoji: '📰', titulo: 'O online de cara nova', texto: 'Salas ilustradas, O Martelo com as notas da redação e um novo visual para o pacote do campeão e a decisão da próxima partida, no celular e no computador. (Online)' },
  { data: '2026-09-07', emoji: '🎮', titulo: 'Nasceu o Sistematizados FC', texto: 'Mais um clube batizado por apoiador: o Sistematizados FC entra na Série D no lugar do Coliseu United, com escudo roxo e prata, manto preto e roxo e mascote próprio — o Sistematizado, o streamer de headset que carimba a tela quando o time faz gol. Quem já tinha carreira com o Coliseu United continua no mesmo time, só com a cara nova. (Carreira e Rápido)' },
  { data: '2026-09-07', emoji: '🌑', titulo: 'Nasceu o Nova Eclipse FC', texto: 'Mais um clube batizado por apoiador: o Nova Eclipse FC entra na Série C no lugar do Zequinha SAF, com escudo prata, manto preto com pinceladas brancas e mascote próprio — o Eclipse, um jogador encapuzado que carimba a tela quando o time faz gol. Quem já tinha carreira com o Zequinha SAF continua no mesmo time, só com a cara nova. (Carreira e Rápido)' },
  { data: '2026-09-07', emoji: '🕵️', titulo: 'Chegou o OLHEIRO: sondar jogador voltou', texto: 'Na janela antes do leilão, a aba 🕵️ Sondar agora deixa marcar um JOGADOR de outro clube além do técnico — o sondado vai pro pregão e você briga por ele (1 jogador e 1 técnico por leilão, só quem está sem contrato). Todo mundo sonda foi profissional, bom jogador e promessa; com o Olheiro ⭐ Craque você sonda os craques (e vê o nível deles no elenco), e o 👑 Lenda sonda tudo, lenda inclusive. E o grupo VIP do WhatsApp abriu pro Craque também. (Carreira)' },
  { data: '2026-09-04', emoji: '📰', titulo: 'O Martelo agora sai no jogo rápido offline', texto: 'Quando o torneio contra a máquina acaba, sai a edição do jornal O Martelo — manchete do campeão, os donos do torneio, o artilheiro e uma nota de redação pros cinco primeiros, pra você e pro lanterna. Dá pra mandar a capa no grupo. Antes isso só existia nas salas online. (Jogo Rápido)' },
  { data: '2026-09-06', emoji: '🐟', titulo: 'Nasceu o Bagres 1993', texto: 'Mais um clube batizado por apoiador: o Bagres 1993 entra direto na Série A. Escudo, manto verde e branco e mascote próprios — o Bagre, um bagre de boné que carimba a tela quando o time faz gol. (Carreira e Rápido)' },
  { data: '2026-09-05', emoji: '🪟', titulo: 'Nasceu o Vidraceiro FC', texto: 'Mais um clube batizado por apoiador: o Vidraceiro FC entra direto na Série A. Escudo, manto azul-vidro e preto e mascote próprios — o Cristal, uma chapa de vidro que carimba a tela quando o time faz gol. (Carreira e Rápido)' },
  { data: '2026-09-05', emoji: '🐂', titulo: 'Nasceu o Final Boss FC', texto: 'Mais um clube batizado por apoiador: o Final Boss FC entra na Série C no lugar do Ponte Branca, com escudo, manto branco com faixa vermelha e preta e mascote próprio — o Boss, um touro que carimba a tela quando o time faz gol. Quem já tinha carreira com o Ponte Branca continua no mesmo time, só com a cara nova. (Carreira e Rápido)' },
  { data: '2026-09-04', emoji: '⚡', titulo: 'Nasceu o Stocco FC', texto: 'Mais um clube batizado por apoiador: o Stocco FC entra na Série C no lugar do Semervilha, com escudo, manto roxo e preto e mascote próprios — o Relâmpago, um lobo que carimba a tela quando o time faz gol. Quem já tinha carreira com o Semervilha continua no mesmo time, só com a cara nova. (Carreira e Rápido)' },
  { data: '2026-09-03', emoji: '🐉', titulo: 'Nasceu a Corporação Capsule FC', texto: 'Mais um clube batizado por apoiador: a Corporação Capsule FC entra na Série B no lugar do Real Tabuleiro, com escudo, manto preto e azul e mascote próprios — o DragonBola, um dragão que carimba a tela quando o time faz gol. Quem já tinha carreira com o Real Tabuleiro continua no mesmo time, só com a cara nova. (Carreira e Rápido)' },
  { data: '2026-09-03', emoji: '🇫🇷', titulo: 'O Zidane agora é o da Juventus', texto: 'No baralho do mundo, a carta do Zinedine Zidane deixou de ser a do Real Madrid de 2002 e passou a ser a da Juventus de 1998 — o ano da Bola de Ouro dele. Mesmo nível de lenda, mesmo preço no pregão: muda o clube e o ano na carta. Quem já tem a carta velha guardada no álbum ou no elenco continua com ela do jeito que estava. (Todos os modos)' },
  { data: '2026-09-02', emoji: '⏱️', titulo: 'Mais tempo pra convocar, Monte mais ágil', texto: 'Na Copa do Mundo online depois da liga, a convocação dos 11 agora tem 135 segundos (eram 65) — e segue avançando na hora em que todo mundo fecha o time. E no Monte das sobras do online cada vez passou de 45 pra 30 segundos, pra sala não ficar esperando. (Rápido online)' },
  { data: '2026-09-02', emoji: '🧦', titulo: 'Nasceu o Jurubeba FC', texto: 'Mais um clube batizado por apoiador: o Jurubeba FC entra na Série B no lugar do Ferroviário do Sul, com escudo, manto amarelo e verde-petróleo e mascote próprios — a Meia na Canela, uma meia de óculos escuros que carimba a tela quando o time faz gol. Quem já tinha carreira com o Ferroviário do Sul continua no mesmo time, só com a cara nova. (Carreira e Rápido)' },
  { data: '2026-09-01', emoji: '🌐', titulo: 'LIGA + COPA DO MUNDO na mesma noite', texto: 'Ao criar a sala tem uma opção nova em "depois da liga": 🌐 Liga + Mundo. A liga roda igual sempre e, quando ela acaba, os 20 times viram seleções e rola a Copa do Mundo — com mais 4 seleções da máquina pra fechar 24. Quem terminou a liga em 1º escolhe a seleção primeiro, o 2º escolhe depois, e assim por diante; os bots ficam com as sobras. Campeão do mundo leva título no Rank, a carta do campeão e o troféu na estante da sala. (Online)' },
  { data: '2026-08-31', emoji: '🌍', titulo: 'COPA DO MUNDO com a sua turma', texto: 'Modo novo ao criar sala: cada um pega UMA seleção e convoca 11 jogadores do país — sem leilão. Aí rola a Copa inteira na tela de todo mundo ao mesmo tempo: 4 grupos, mata-mata ida e volta e final única. Campeão do mundo leva título no Rank, a carta do campeão e o troféu na estante da sala. (Online)' },
  { data: '2026-08-31', emoji: '👑', titulo: 'A elite do jogo agora se chama SÉRIE A', texto: 'Os clubes batizados que jogam o rápido online e são os rivais da carreira estavam numa divisão chamada Série D — e era justamente a mais forte e a mais cara. Trocamos a letra: essa turma agora é a SÉRIE A, e os clubes que estavam na A passam pra D. Quem já tem carreira em andamento não muda NADA: seu time, sua divisão e sua tabela continuam exatamente como você deixou — a troca só vale pra carreira nova. (Carreira e Rápido)' },
  { data: '2026-08-30', emoji: '🐦‍⬛', titulo: 'O Manfré FC ganhou cara nova', texto: 'O dono mandou a arte dele e o clube trocou de pele: escudo, mascote e manto novos — a Gralha agora carimba a tela quando o time faz gol, e o manto virou vermelho e azul. Mesma vaga, mesmo elenco, mesmo tudo: quem já tinha carreira com o Manfré FC (ou com o antigo Livre-pool) continua no mesmo time, só com a cara nova.' },
  { data: '2026-08-29', emoji: '⚖️', titulo: 'O Rank agora é por pontos', texto: 'Na barrinha de troféus da sala (Rápido e Minhas Ligas), a aba 🏆 Rank passou a somar pontos em vez de comparar títulos: título da liga vale +30, a copa vale +20 e cair pra zona de rebaixamento tira 10 — mas ninguém fica negativo, o pior caso é zero. Artilheiro continua ganhando troféu na Estante, só não conta ponto. As regras ficam escritas ali embaixo do Rank, e na sua liga o dono pode mudar tudo isso em ⚙️ Ajustes.' },
  { data: '2026-08-29', emoji: '🔨', titulo: 'Criar sala ficou simples', texto: 'A tela de criar sala foi refeita: agora começa perguntando UMA coisa — o que vocês vão jogar — em cartões grandes que explicam cada modo. Escolheu, as configurações daquele modo abrem embaixo já no ponto, e o botão de criar fica no fim. Nenhuma opção sumiu: baralho, formação, duplas, chat, tempo do leilão e o resto continuam lá, só na ordem certa.' },
  { data: '2026-08-29', emoji: '🏆', titulo: 'MINHAS LIGAS — a sala da sua turma que NÃO acaba', texto: 'Sala rápida some quando a galera sai. A Liga não: é sempre a MESMA sala, com dia e hora combinados, e a estante guardando campeão, artilheiro e rebaixado temporada após temporada — com o ranking somando tudo pela regra que o dono escolher. Ela é só da sua turma: entra com o código + a senha, e não aparece em lista nenhuma. Criar é benefício do 👑 Lenda (até 5 ligas); pra JOGAR não precisa de nada — é só alguém te passar o código.' },
  { data: '2026-08-28', emoji: '🧢', titulo: 'CHEGARAM OS TÉCNICOS!', texto: 'No Modo Carreira agora seu clube tem TÉCNICO: 105 comandantes com categoria igual à das cartas (👑 Lenda a 🤎 Foi profissional), cada um com o nível dele — que soma no time em toda partida da liga — e com os esquemas que ele usa de verdade. Pra contratar: na janela antes do leilão, aba 🕵️ SONDAR, você marca o técnico que quer e briga por ele no pregão, no envelope, igual jogador. Contrato de 5 temporadas, com salário na folha.' },
  { data: '2026-08-28', emoji: '🎽', titulo: '15 formações — mas quem abre elas é o técnico', texto: 'O jogo passou de 5 pra 15 esquemas (4-2-4, 5-4-1, losango, árvore de Natal, 3-5-2 com alas, líbero e mais) e o campinho ficou maior, com goleiro, zaga e ataque sempre no mesmo lugar. Atenção, que é a parte nova: SEM técnico o time só joga o esquema que ele já treina — quem abre as outras formações é o técnico que você contratar, e quanto maior a categoria dele, mais esquemas ele traz (👑 Lenda traz 5).' },
  { data: '2026-08-27', emoji: '📰', titulo: 'O MARTELO agora sai no Rápido Online', texto: 'Quando a liga (e a Copa) acabam numa sala online, o jornal do jogo fecha a noite: manchete com quem levou a liga e quem levou a Copa, os donos da noite, e uma linha escrita pra CADA técnico da sala — do campeão ao lanterna, passando por quem ficou a uma posição de se classificar. Tem botão pra mandar a capa no grupo como imagem.' },
  { data: '2026-08-27', emoji: '🎁', titulo: 'O pacote do campeão espera você', texto: 'No Rápido, o pacote de carta do campeão não abre mais sozinho quando o tempo acaba: ele fica lacrado até você tocar, pra ninguém perder a hora de ver qual carta saiu. A carta continua sendo sua de qualquer jeito, mesmo se você fechar a tela.' },
  { data: '2026-08-24', emoji: '🅰️', titulo: 'Gols e assistências também no Rápido', texto: 'No Rápido (online e contra a CPU): o campinho do seu time agora mostra os selos de ⚽ gols e 🅰️ assistências em cada jogador — antes o campinho vinha sem número nenhum — e do lado da artilharia nasceu a lista dos 🅰️ Garçons, com quem mais dá passe pro gol na liga.' },
  { data: '2026-08-24', emoji: '🔁', titulo: 'Dá pra trocar os jogadores de lado', texto: 'No Modo Carreira, no campinho do Elenco: toque em dois titulares da mesma posição e eles trocam de lugar — o canhoto vai pra esquerda, o destro pra direita, os dois atacantes invertem. É só a organização do seu campinho: não muda a força do time nem o resultado.' },
  { data: '2026-08-24', emoji: '🅰️', titulo: 'Chegaram as assistências', texto: 'Todo gol agora mostra quem deu o passe — na liga e em QUALQUER copa (Copa Legends, Copa do Brasil, Supercopa e Copa do Mundo). Aparece embaixo do placar, no seu elenco (⚽ e 🅰️ lado a lado) e numa aba nova no Rank com os melhores garçons de cada série. Gol de jogada individual aparece assim mesmo, com todas as letras. Nenhum resultado das suas temporadas mudou.' },
  { data: '2026-08-24', emoji: '📼', titulo: 'O jornal ganhou memória', texto: 'No Modo Carreira: o jornal do fim de temporada agora guarda a história do seu clube e abre a página "O Jornal Lembra" quando ela merece manchete — 3º título seguido, dinastia, o jejum que acabou, a 10ª temporada seguida na Série A, a primeira vez na elite, a primeira Copa. Cada taça (ou seca) vira memória.' },
  { data: '2026-08-23', emoji: '📺', titulo: 'A TV agora paga cota extra pelo seu vídeo', texto: 'No Modo Carreira: a Rede Martelo TV ganhou casa fixa em Clube › Patrocínio — lá dá pra ver quanto o contrato da sua divisão paga por temporada e televisionar seu jogo: grava um vídeo (15s+) da tela jogando, posta no Instagram, TikTok ou YouTube marcando @leilaolegendscom, cola o link e ganha +15 moedas na caixa do clube. Um vídeo por temporada — e, como toda cota de TV, pode atrasar um pouquinho, mas cai.' },
  { data: '2026-08-23', emoji: '🦁', titulo: 'O Império Samambaia virou Leão da Estradinha', texto: 'O dono rebatizou o clube em homenagem ao time do coração dele, o Rio Branco-PR — o Leão da Estradinha de 1913. Escudo, mascote e manto novos (vermelho e branco), mesma vaga na Série A e mesmo elenco. Quem já tinha carreira com o Império Samambaia continua no mesmo time, só com a cara nova.' },
  { data: '2026-08-23', emoji: '🏅', titulo: 'A sala online ganhou estante de troféus', texto: 'No Rápido online: apareceu uma barrinha no rodapé, do jeito da carreira, com o histórico da sala — 🏆 Rank mostra quem lidera somando as temporadas, 🏅 Estante empilha os troféus de cada um (e o Troféu Mico do lanterna) e 📜 Temporadas guarda campeão, campeão da copa e artilheiro de cada partida. Só a galera pontua: bot não entra.' },
  { data: '2026-08-23', emoji: '🐺', titulo: 'Nasceu o Papão United Madrid', texto: 'Mais um clube batizado por apoiador: o Papão United Madrid entra na Série D no lugar do Santos Dumont, com escudo e mascote próprios — O Papão, um lobo chifrudo de faixa azul e branca que carimba a tela quando o time faz gol. O Alfacehh desceu pra Série B e segue com tudo dele. Quem já tinha carreira com o Santos Dumont continua no mesmo time, só com a cara nova.' },
  { data: '2026-08-21', emoji: '🐶', titulo: 'Nasceu o São Luiz FC', texto: 'Mais um clube batizado por apoiador: o São Luiz FC entra na Série D no lugar do Flamengo do Sertão, com escudo e mascote próprios — o Luizão, um pitbull que carimba a tela quando o time faz gol. Quem já tinha carreira com o Flamengo do Sertão continua no mesmo time, só com a cara nova.' },
  { data: '2026-08-21', emoji: '🦇', titulo: 'Nasceu o Theuzudo FC', texto: 'Mais um clube batizado por apoiador: o Theuzudo FC entra na Série B no lugar do Comercial do Norte, com escudo e mascote próprios — o Theuzinho, um morcego laranja e preto que carimba a tela quando o time faz gol. Quem já tinha carreira com o Comercial do Norte continua no mesmo time, só com a cara nova.' },
  { data: '2026-08-21', emoji: '🏆', titulo: 'O fim da temporada virou momento', texto: 'No Modo Carreira: quando a temporada fecha, uma tela conta o que aconteceu com o clube — subiu de divisão, caiu, foi campeão — com a divisão de onde saiu, pra onde vai e o que você levou de prêmio, caixa, patrocínio e torcida.' },
  { data: '2026-08-21', emoji: '🔨', titulo: 'Pregão mais direto', texto: 'No leilão de todos os modos: suas vagas e o dinheiro ficam sempre na barra de cima, as regras do pregão viraram um botão ❓ ali do lado — e quem está começando ganha a explicação inteira no primeiro pregão da partida.' },
  { data: '2026-08-21', emoji: '🧹', titulo: 'Virada de temporada mais limpa', texto: 'No Modo Carreira: a escolha que trava o jogo agora fica sozinha em cima, com o selo "sua vez" — e o que já aconteceu (fechamento do caixa, patrocínio pago) virou uma linha que leva direto pro lugar onde a coisa está inteira.' },
  { data: '2026-08-21', emoji: '🪜', titulo: 'Carreira com menu embaixo', texto: 'No Modo Carreira: Jogos, Tabelas, Elenco, Rank e Clube saíram do meio da página e viraram um menu fixo no rodapé — e dentro do Clube e do Elenco as abas de dentro também param de sumir quando você rola. Role até onde rolar, você troca de aba na hora e continua vendo rodada, posição e caixa numa faixa fina no topo.' },
  { data: '2026-08-21', emoji: '🤝', titulo: 'Patrocínio mais direto', texto: 'No Modo Carreira: a escolha do patrocínio virou dois toques — primeiro a meta da temporada, depois a marca que estampa a camisa — e a tabela de quanto cada divisão paga foi pra aba Clube › Patrocínio.' },
  { data: '2026-08-20', emoji: '🏠', titulo: 'Home nova, com menu embaixo', texto: 'A tela de abertura ficou mais limpa: um menu fixo no rodapé (Início, Regras, Álbum, Ranking, Apoiar) e o passo a passo de como funciona uma partida, pra quem está chegando agora entender o jogo sem precisar perguntar.' },
  { data: '2026-08-20', emoji: '🌎', titulo: 'Libertadores', texto: 'No Rápido (online e contra a CPU): escolha "Liga + Liberta" e, quando a liga acabar, os 8 primeiros entram numa Libertadores de 32 clubes — 8 grupos de 4, passam 2, e a final é jogo único.' },
  { data: '2026-08-17', emoji: '🏅', titulo: 'Ranking agora é por pontos', texto: 'No Modo Carreira: Copa do Mundo vale 200, Copa do Brasil 30, Série A 20, Supercopa 15, B 10, C 5, D 3 e Várzea 1 — quem tem mais título soma mais, e a coluna PTS mostra a conta.' },
  { data: '2026-08-17', emoji: '🌍', titulo: 'Copa do Mundo com 24 seleções', texto: 'No Modo Carreira: entraram Croácia, Dinamarca, Peru e Equador — agora são 4 grupos de 6, e o TOP 24 do ranking de clubes garante vaga.' },
  { data: '2026-08-16', emoji: '🏠', titulo: 'Home nova', texto: 'A tela de abertura mudou: quem já tem carreira continua de cara, e cada botão diz o que você ganha ali.' },
  { data: '2026-08-16', emoji: '🔓', titulo: 'Carreira sem cadastro', texto: 'Dá pra jogar a primeira temporada inteira sem criar conta — o time fica guardado no aparelho.' },
  { data: '2026-08-16', emoji: '🪜', titulo: 'Continuar com esse time', texto: 'No fim da partida rápida, o time que você montou pode virar uma carreira, com a liga inteira junto.' },
  { data: '2026-08-16', emoji: '🏆', titulo: 'Copa do Brasil e Supercopa', texto: 'No Modo Carreira: a Copa virou Copa do Brasil, e o campeão dela encara o campeão da Série A na Supercopa.' },
  { data: '2026-08-08', emoji: '🤝', titulo: 'Duplas (beta)', texto: 'No Rápido Online: chame um amigo pra dividir o comando do MESMO time — cada um manda em 3 das 6 posições.' },
  { data: '2026-08-05', emoji: '💰', titulo: 'Patrocínio virou aposta', texto: 'No Modo Carreira: escolha a meta da temporada (não cair, acesso ou título) e fature de acordo.' },
  { data: '2026-08-04', emoji: '🏥', titulo: 'Departamento Médico', texto: 'No Modo Carreira: a última obra do estádio acaba com as lesões do seu elenco pra sempre.' },
  { data: '2026-08-02', emoji: '🚀', titulo: 'Contratos em massa', texto: 'Venceram vários contratos de uma vez? Renove ou libere TODOS num botão só.' },
  { data: '2026-07-28', emoji: '💰', titulo: 'Finanças do clube', texto: 'No Modo Carreira: extrato de tudo que entra e sai, e o lucro de cada venda.' },
  { data: '2026-07-20', emoji: '💼', titulo: 'SAF', texto: 'No Modo Carreira: compre a SAF de um clube da Série D, leve metade dos lucros dele e empreste jogadores.' },
  { data: '2026-07-12', emoji: '🏟️', titulo: 'Estádio', texto: 'No Modo Carreira: construa arquibancada, refletor, telão e cobertura — o desenho cresce e a bilheteria rende.' },
]

/**
 * As novidades que a HOME mostra — e é isto que faz ela encolher sozinha:
 * só entra o que é recente, e nunca mais que `max`. Novidade velha some sem
 * ninguém precisar apagar nada (era o problema: 17 avisos empilhados pra
 * sempre). O piso de `min` existe só pra tela nunca ficar vazia numa semana
 * parada.
 */
export function novidadesDaVez(hoje = new Date(), dias = 45, max = 5, min = 3): Novidade[] {
  const corte = hoje.getTime() - dias * 86400000
  const recentes = NOVIDADES.filter(n => {
    const t = Date.parse(n.data)
    return Number.isFinite(t) && t >= corte
  })
  const lista = recentes.length >= min ? recentes : NOVIDADES.slice(0, min)
  return lista.slice(0, max)
}
