// ─── 📢 NOVIDADES DO JOGO — a lista ÚNICA (Diego 16/08) ──────────────────
//
// Regras que o Diego deu, em ordem de importância:
//
// 1. **TODA novidade do jogo entra aqui, sozinha.** Ligou uma coisa nova pro
//    pessoal? A mesma entrega que liga escreve a linha aqui. Não existe
//    "depois eu aviso" — o que não está aqui, ninguém fica sabendo.
// 2. **BUG NUNCA ENTRA.** *"Menos bugs q nunca lance"*. Conserto não é
//    novidade: quem joga não quer ler que alguma coisa estava quebrada. Se a
//    entrega é só conserto, ela NÃO ganha linha aqui — vai pro
//    `docs/pendencias.md` e pro commit, que é onde isso mora.
// 3. **Novidade não fica pra sempre.** A tela mostra só o que é RECENTE e some
//    sozinho com o tempo (ver `novidadesDaVez` embaixo). Antes eram 17 avisos
//    empilhados, alguns de meses atrás — virou um paredão que ninguém lia.
//
// Como escrever a linha: o QUE mudou pra quem joga, em uma frase, com o modo
// entre parênteses. Sem tecniquês, sem nome de arquivo, sem "implementamos".
export interface Novidade {
  /** dia em que ISSO ficou disponível pra galera (YYYY-MM-DD) — é o que faz a lista encolher sozinha */
  data: string
  emoji: string
  titulo: string
  /** uma frase. Se não couber numa frase, provavelmente são duas novidades. */
  texto: string
  /** 🌐 a MESMA novidade em inglês (12/09: o jogo é BR/EN). Toda linha nova nasce com `en`;
   *  se faltar, a tela em EN mostra o PT — não quebra, só fica em português. */
  en?: { titulo: string; texto: string }
}
// 🌐 o que a tela lê, no idioma da vez (PT é o padrão e sempre existe)
export const novTitulo = (n: Novidade): string => (getLang() === 'en' && n.en ? n.en.titulo : n.titulo)
export const novTexto = (n: Novidade): string => (getLang() === 'en' && n.en ? n.en.texto : n.texto)

import { getLang } from './lang'

// ⚠️ SEMPRE em ordem: a mais NOVA em cima.
export const NOVIDADES: Novidade[] = [
  { data: '2026-09-16', emoji: '🌴', titulo: 'Cara nova pro Marolados FC', texto: 'O Marolados FC está de cara nova: escudo novo de coqueiros e onda com o nome em letra de pincel, manto verde e creme listrado com a faixa rasta na gola e mascote redesenhada — o Marolado, o moleque de touca e dreads com o pé na bola, que carimba a tela quando o time faz gol. O clube é o mesmo, na mesma divisão; só a arte mudou. (Carreira e Rápido)', en: { titulo: 'A new look for Marolados FC', texto: 'Marolados FC has a new look: a new crest with palm trees and a wave and the name in brush lettering, a green and cream striped kit with rasta trim on the collar and a redesigned mascot — the Marolado, the kid in a beanie and dreads with his foot on the ball, stamping the screen when the team scores. Same club, same division; only the artwork changed. (Career and Quick match)' } },
  { data: '2026-09-16', emoji: '🐶', titulo: 'Escudo e manto novos no São Luiz FC', texto: 'O São Luiz FC trocou de escudo e de manto: o brasão agora é redondo, vermelho, preto e branco, com o SLFC e as estrelas, e o manto virou de argolas nas três cores em vez de listras em pé. A mascote é a mesma de sempre — o pitbull continua carimbando a tela quando o time faz gol. (Carreira e Rápido)', en: { titulo: 'New crest and kit for São Luiz FC', texto: 'São Luiz FC has a new crest and kit: the badge is now round, in red, black and white, with the SLFC and the stars, and the kit became hooped in the three colours instead of vertical stripes. The mascot is the same as always — the pitbull still stamps the screen when the team scores. (Career and Quick match)' } },
  { data: '2026-09-16', emoji: '🦍', titulo: 'Cara nova pro Scorporila FC', texto: 'O Scorporila FC está de cara nova: escudo alvinegro novo com o gorila-escorpião, cauda dourada e as pinças abraçando o brasão, manto preto e branco listrado com detalhe dourado e mascote redesenhada — o Scorporila, de corpo inteiro com a cauda erguida, que carimba a tela quando o time faz gol. O clube é o mesmo, na mesma divisão; só a arte mudou. (Carreira e Rápido)', en: { titulo: 'A new look for Scorporila FC', texto: 'Scorporila FC has a new look: a new black-and-white crest with the scorpion-gorilla, its golden tail and pincers wrapped around the badge, a black and white striped kit with gold trim and a redesigned mascot — the Scorporila, full-body with its tail raised, stamping the screen when the team scores. Same club, same division; only the artwork changed. (Career and Quick match)' } },
  { data: '2026-09-16', emoji: '🐺', titulo: 'Escudo e manto novos no Papão United Madrid', texto: 'O Papão United Madrid trocou de escudo e de manto: o brasão agora é mais largo, coroado, com o lobo chifrudo, o tridente e a caravela, e o manto ficou azul-marinho e branco com detalhe dourado. A mascote é a mesma de sempre — o Papão continua carimbando a tela quando o time faz gol. (Carreira e Rápido)', en: { titulo: 'New crest and kit for Papão United Madrid', texto: 'Papão United Madrid has a new crest and kit: the badge is now wider and crowned, with the horned wolf, the trident and the caravel, and the kit became navy and white with gold trim. The mascot is the same as always — the Papão still stamps the screen when the team scores. (Career and Quick match)' } },
  { data: '2026-09-16', emoji: '🐈', titulo: 'Cara nova pro Barcenite FC', texto: 'O Barcenite FC está de cara nova: escudo novo azul e amarelo com o BFC dourado e a bola, manto listrado azul e amarelo e mascote redesenhada — o Gatão, o gato de braços cruzados e uniforme do clube, que carimba a tela quando o time faz gol. O clube é o mesmo, na mesma divisão; só a arte mudou. (Carreira e Rápido)', en: { titulo: 'A new look for Barcenite FC', texto: 'Barcenite FC has a new look: a new blue and yellow crest with the golden BFC and the ball, a blue and yellow striped kit and a redesigned mascot — the Gatão, the cat with folded arms in the club kit, stamping the screen when the team scores. Same club, same division; only the artwork changed. (Career and Quick match)' } },
  { data: '2026-09-16', emoji: '🐓', titulo: 'Cara nova pro Nightfull FC', texto: 'O Nightfull FC está de cara nova: escudo alvinegro novo de moldura dourada, com o galo coroado de crista vermelha e a lua, manto preto e branco listrado com detalhe dourado e mascote redesenhada — o Nightfull, o galo guerreiro de capa de penas, que carimba a tela quando o time faz gol. O clube é o mesmo, na mesma divisão; só a arte mudou. (Carreira e Rápido)', en: { titulo: 'A new look for Nightfull FC', texto: 'Nightfull FC has a new look: a new black-and-white crest with a gold frame, the crowned rooster with its red comb and the moon, a black and white striped kit with gold trim and a redesigned mascot — the Nightfull, the warrior rooster in a feather cape, stamping the screen when the team scores. Same club, same division; only the artwork changed. (Career and Quick match)' } },
  { data: '2026-09-16', emoji: '⚔️', titulo: 'Cara nova pro Murriz FC', texto: 'O Murriz FC está de cara nova: escudo rubro-negro novo com o guerreiro de barba ruiva e o letreiro MURRIZ FC, manto vermelho e preto de listras e mascote redesenhada — o Murriz, de armadura e machado-de-bola, que carimba a tela quando o time faz gol. O clube é o mesmo, na mesma divisão; só a arte mudou. (Carreira e Rápido)', en: { titulo: 'A new look for Murriz FC', texto: 'Murriz FC has a new look: a new red-and-black crest with the red-bearded warrior and the MURRIZ FC banner, a red and black hooped kit and a redesigned mascot — the Murriz, in armour with his ball-axe, stamping the screen when the team scores. Same club, same division; only the artwork changed. (Career and Quick match)' } },
  { data: '2026-09-16', emoji: '🧢', titulo: 'Cara nova pro Tôka10', texto: 'O Tôka10 está de cara nova: o escudo agora é a touca — amarela, verde e azul, com o 10 na frente e o TÔKA no punho —, o manto virou amarelo e verde com o azul da touca, e a mascote foi redesenhada: o menino de touca, oclinhos e bigode, dando joinha, que carimba a tela quando o time faz gol. O clube é o mesmo, na mesma divisão; só a arte mudou. (Carreira e Rápido)', en: { titulo: 'A new look for Tôka10', texto: 'Tôka10 has a new look: the crest is now the beanie itself — yellow, green and blue, with the 10 on the front and TÔKA on the cuff —, the kit became yellow and green with the beanie\'s blue, and the mascot was redrawn: the kid in a beanie, glasses and moustache, giving a thumbs up, stamping the screen when the team scores. Same club, same division; only the artwork changed. (Career and Quick match)' } },
  { data: '2026-09-16', emoji: '🦇', titulo: 'Cara nova pro Neymarzetti', texto: 'O Neymarzetti está de cara nova: escudo novo com o morcego-N cromado, manto branco com detalhe preto no lugar do preto e prata, e mascote redesenhada — o camisa 10 de óculos escuros, de joelhos comemorando, que carimba a tela quando o time faz gol. O clube é o mesmo, na mesma divisão; só a arte mudou. (Carreira e Rápido)', en: { titulo: 'A new look for Neymarzetti', texto: 'Neymarzetti has a new look: a new crest with the chrome bat-N, a white kit with black trim in place of the black and silver, and a redesigned mascot — the number 10 in sunglasses, on his knees celebrating, stamping the screen when the team scores. Same club, same division; only the artwork changed. (Career and Quick match)' } },
  { data: '2026-09-16', emoji: '🥊', titulo: 'Nasceu o Raiva Cajuri FC', texto: 'Mais um clube batizado por apoiador: o Raiva Cajuri FC chega na Série C, com o lutador mascarado no escudo, manto preto e vermelho de raios e mascote própria — o Raiva, que se joga da quina do ringue e carimba a tela quando o time faz gol. (Carreira e Rápido)', en: { titulo: 'Raiva Cajuri FC is born', texto: 'One more club named by a supporter: Raiva Cajuri FC arrives in Série C, with the masked wrestler on the crest, a black and red lightning kit and its own mascot — the Raiva, who dives off the ring corner and stamps the screen when the team scores. (Career and Quick match)' } },
  { data: '2026-09-16', emoji: '👑', titulo: 'Nasceu o Rei da Bola FC', texto: 'Mais um clube batizado por apoiador: o Rei da Bola FC chega na Série A, com o leão branco coroado no escudo, manto branco com faixa vermelha e preta e mascote própria — o Rei, o leão de coroa e manto que carimba a tela quando o time faz gol. O Sapekeiros FC segue no jogo, agora na Série B. (Carreira e Rápido)', en: { titulo: 'Rei da Bola FC is born', texto: 'One more club named by a supporter: Rei da Bola FC arrives in Série A, with the crowned white lion on the crest, a white kit with red and black bands and its own mascot — the King, the crowned lion in a cape that stamps the screen when the team scores. Sapekeiros FC stays in the game, now in Série B. (Career and Quick match)' } },
  { data: '2026-09-16', emoji: '🥇', titulo: 'A agência só comissiona artilheiro', texto: 'Na agência, a comissão por acontecimento passa a ser só do artilheiro: quem é artilheiro de qualquer série ou da Copa rende moeda pra você, e quem é negociado no leilão também, como sempre foi. Ser campeão não paga mais comissão — um time campeão tem onze titulares, então bastava um agenciado numa boa equipe pra render mais que uma carreira inteira de gols, sem mérito nenhum do jogador. As mensalidades dos seus agenciados continuam exatamente iguais. (Carreira)', en: { titulo: 'The agency only pays for top scorers', texto: 'At the agency, the per-event commission is now only for top scorers: a client who finishes top scorer of any division or of the Cup earns you coins, and so does one who gets traded at the auction, as always. Winning a title no longer pays a commission — a champion side has eleven starters, so a single client at a good team paid more than a whole career of goals, with no credit to the player at all. Your clients\' monthly fees are exactly the same. (Career)' } },
  { data: '2026-09-15', emoji: '📺', titulo: 'A Rede Martelo TV pagando MUITO mais', texto: 'A cota de TV que cai no caixa no fim de cada temporada subiu em todas as divisões, e virou uma escada redonda: Várzea 10, Série D 20, Série C 30, Série B 40 e Série A 50 moedas por temporada. Quem está começando foi quem mais ganhou — a Várzea saiu de 1 pra 10. Não precisa fazer nada: o contrato melhora sozinho quando você sobe de série, e o valor aparece em Clube › Patrocínio. (Carreira)', en: { titulo: 'Rede Martelo TV paying a LOT more', texto: 'The TV money that lands in your till at the end of each season went up in every division, and became a clean ladder: Várzea 10, Série D 20, Série C 30, Série B 40 and Série A 50 coins per season. Whoever is starting out gained the most — Várzea went from 1 to 10. Nothing to do: the deal improves by itself when you go up, and the amount shows in Club › Sponsorship. (Career)' } },
  { data: '2026-09-15', emoji: '⬇️', titulo: 'O placar te acompanha quando você rola', texto: 'Na carreira, quando você desce a tela pra ver o elenco, a tabela ou o clube, o placar do seu jogo não fica mais pra trás: ele encolhe pra uma faixinha fina grudada no topo, com o resultado ao vivo e o minuto. Toca nela e ele abre inteiro de novo; subiu a tela, ele abre sozinho. Nada saiu do lugar — o estádio, o placar e o campinho continuam onde sempre estiveram. (Carreira)', en: { titulo: 'The scoreboard follows you as you scroll', texto: 'In career mode, when you scroll down to check your squad, the table or your club, your match score no longer gets left behind: it shrinks into a thin strip pinned to the top, with the live score and the minute. Tap it and it opens up in full again; scroll back up and it opens on its own. Nothing moved — the stadium, the scoreboard and the pitch are all still where they always were. (Career)' } },
  { data: '2026-09-15', emoji: '🎛️', titulo: 'A tela da carreira ficou mais fácil de ler', texto: 'Antes eram quatro fileiras de botão iguais fazendo coisas bem diferentes. Agora cada coisa tem a cara do que ela faz: o ▶️ Próxima rodada é o único botão grande (o PULAR fica menor do lado), o ritmo continua na faixinha fina, Time e Agenciados viraram aba de texto e a tática virou pastilha redonda com o rótulo ⚔️ Tática do próximo jogo. E, quando tem gente no vermelho, aparece uma linha 🚑 colada na caixa do clube que leva direto pros titulares num toque — sem precisar rolar até lá embaixo. (Carreira)', en: { titulo: 'The career screen is easier to read', texto: 'It used to be four rows of identical buttons doing very different things. Now each one looks like what it does: ▶️ Next round is the only big button (SKIP sits smaller beside it), the pace controls stay on the thin strip, Team and Clients became text tabs and the tactics became rounded pills under a ⚔️ Tactics for the next match label. And when players are in the red, a 🚑 line appears right under the club box that jumps straight to your starters in one tap — no scrolling all the way down. (Career)' } },
  { data: '2026-09-15', emoji: '🕳️', titulo: 'O host vê as vagas vazias de cada time', texto: 'Quem criou a sala agora enxerga, no ⚙️ gerenciar técnicos, quantas vagas ainda estão vazias no time de cada um — e o número cai em tempo real conforme o pessoal vai fechando o elenco no leilão e no Monte Final. Serve pra bater o olho e saber quem está ficando pra trás antes de decidir qualquer coisa. (Partidas online)', en: { titulo: 'The host sees each team\'s empty slots', texto: 'Whoever created the room can now see, under ⚙️ manage managers, how many slots each team still has empty — and the number drops in real time as people fill their squads in the auction and the Final Pile. It is there so you can tell at a glance who is falling behind before deciding anything. (Online matches)' } },
  { data: '2026-09-15', emoji: '🛍️', titulo: 'A sua camisa agora vira dinheiro', texto: 'Quem tem a Loja do Clube construída no estádio passa a vender camisa toda temporada. A sua torcida cresce com as arquibancadas que você levanta, e cada obra do estádio leva mais gente pra loja. Antes da temporada começar você escolhe o preço — popular, normal ou cara —, e é uma aposta: camisa barata a torcida toda leva; camisa cara rende o dobro num ano de campeão. O balanço chega na abertura da temporada seguinte e cai direto no caixa. (Carreira)', en: { titulo: 'Your shirt now turns into money', texto: 'If you have built the Club Shop at your ground, you start selling shirts every season. Your fan base grows with the stands you build, and every upgrade at the ground brings more people into the shop. Before the season starts you pick the price — cheap, normal or premium — and it is a bet: a cheap shirt everyone buys; a premium one pays double in a title year. The balance arrives when the next season opens and goes straight into the till. (Career)' } },
  { data: '2026-09-15', emoji: '👟', titulo: 'Uma marca veste o seu time', texto: 'Chegou o fornecedor de material esportivo, e ele aparece na camisa, no peito direito. São quatro marcas na mesa — Pênalti do Bairro, Adibas, Pumba e Naique — com contrato de 1, 2, 3 ou 5 temporadas, igual ao Patrocinador Master. Além da moeda por temporada, cada uma aumenta tudo que a sua loja vender, e marca grande só bate na porta de quem subiu de divisão. O valor trava na divisão em que você assina: subiu ou caiu, o contrato não quebra. Precisa da Loja do Clube construída. (Carreira)', en: { titulo: 'A brand kits out your team', texto: 'The kit supplier has arrived, and it shows up on your shirt, on the right chest. Four brands on the desk — Pênalti do Bairro, Adibas, Pumba and Naique — with 1, 2, 3 or 5-season contracts, just like the Master Sponsor. Beyond the coins per season, each one boosts everything your shop sells, and the big brands only come knocking once you have gone up a division. The amount locks in at the division where you sign: up or down, the contract does not break. Requires the Club Shop to be built. (Career)' } },
  { data: '2026-09-15', emoji: '🪜', titulo: 'A virada da temporada virou passo a passo', texto: 'As decisões de antes de começar a temporada agora vêm em fila, uma de cada vez e com a mesma cara: Patrocinador Master, Patrocinador Pontual, fornecedor de material, preço da camisa e bico de folga — cada um com a etiqueta de qual passo é. Só aparece quem tem decisão pra tomar: o Pontual e a camisa caem toda temporada, o Master e o fornecedor só voltam quando o contrato acaba, e o bico volta quando você sobe ou cai de divisão (é quando o cargo muda de degrau). O bico ganhou carteira de trabalho, com cargo e salário anotados. E os contratos fechados — Master, fornecedor e bico — passaram a cair no caixa na hora em que você aperta Começar a temporada, em vez de no fim. (Carreira)', en: { titulo: 'The season turn is now step by step', texto: 'The decisions you take before the season starts now come in a queue, one at a time and all looking the same: Master Sponsor, One-Season Sponsor, kit supplier, shirt price and side job — each labelled with which step it is. Only the ones with a decision to make show up: the one-season sponsor and the shirt come round every season, the Master and the supplier only return when the contract ends, and the side job returns when you go up or down a division (that is when your job title changes rung). The side job got a work record book, with the role and pay written in. And the signed contracts — Master, supplier and side job — now land in your till the moment you tap Start the season, instead of at the end. (Career)' } },
  { data: '2026-09-15', emoji: '\u{1F3CB}\u{FE0F}', titulo: 'Chegou o preparador f\u00edsico', texto: 'O t\u00e9cnico e o preparador agora t\u00eam a \u00e1rea deles no Elenco, o \u{1F3DB}\u{FE0F} Departamento T\u00e9cnico, logo abaixo do campinho. E o preparador \u00e9 quem libera o bot\u00e3o \u{1F501} RODIZIAR, que troca o cansado pelo reserva de um toque: s\u00e3o quatro pra escolher \u2014 Rui Faria, Antonio Pintus, Paulo Paix\u00e3o e Paco Seirulo \u2014 e quanto melhor ele for, mais g\u00e1s cada rodada no banco devolve, ou seja, mais tempo o seu craque joga sem cansar. Tem sal\u00e1rio e contrato de 5 temporadas, igual ao t\u00e9cnico. O rod\u00edzio autom\u00e1tico passa a ser s\u00f3 de quem contrata o \u{1F451} Paco Seirulo. Sem preparador nada trava: voc\u00ea continua trocando na m\u00e3o, tocando no cansado e depois no reserva. (Carreira)', en: { titulo: 'The fitness coach has arrived', texto: 'Your head coach and your fitness coach now have their own area in the Squad tab, the \u{1F3DB}\u{FE0F} Technical Department, right below the pitch. And the fitness coach is who unlocks the \u{1F501} ROTATE button, swapping a tired starter for a backup in one tap: there are four to choose from \u2014 Rui Faria, Antonio Pintus, Paulo Paix\u00e3o and Paco Seirulo \u2014 and the better he is, the more energy each round on the bench gives back, so your star plays longer without getting tired. He has a salary and a 5-season contract, just like the head coach. Auto-rotation is now only for whoever hires \u{1F451} Paco Seirulo. Without a fitness coach nothing is blocked: you keep swapping by hand, tapping the tired player and then the backup. (Career)' } },
  { data: '2026-09-14', emoji: '🪩', titulo: 'Cara nova pro Inter de Bailão', texto: 'O clube que era Alfacehh agora se chama Inter de Bailão e entra em campo com arte de verdade: escudo redondo com as caixas de som e o monograma coroado, manto azul e preto listrado e mascote própria — o Bailão, a bola de espelho de chapéu e corrente de ouro, que carimba a tela quando o time faz gol. Ele joga a Série C, e o Fatality FC subiu pra Série B na troca. Quem tem carreira antiga com o nome velho continua no mesmo time, só com a cara nova. (Carreira e Rápido)', en: { titulo: 'A new look for Inter de Bailão', texto: 'The club formerly known as Alfacehh is now Inter de Bailão, and it takes the field with real artwork: a round crest with speakers and a crowned monogram, a blue and black striped kit and its own mascot — the Bailão, a mirror ball in a bucket hat and gold chain, stamping the screen when the team scores. It plays in Série C, and Fatality FC moved up to Série B in the swap. If you have an old career under the previous name, it is the same club, just with a new face. (Career and Quick match)' } },
  { data: '2026-09-14', emoji: '🏛️', titulo: 'Dá pra vender o 2º clube', texto: 'Quem comprou um segundo clube agora pode devolvê-lo: na aba Clube aparece o botão de vender. Você recebe 3.000 das 4.000 moedas que pagou — os outros 1.000 o elenco e a diretoria já torraram no churrasco de despedida, comemorando a sua saída, e deixaram na sua conta. O clube continua no jogo, na divisão dele, comandado pela máquina, e fica com o estádio, os títulos e o caixa dele. Os empréstimos se acertam sozinhos. Só o SEGUNDO clube pode ser vendido: o seu clube oficial, o que aparece no rank global, nunca. (Carreira)', en: { titulo: 'You can sell your 2nd club', texto: 'If you bought a second club you can now hand it back: the Club tab has a sell button. You get 3,000 of the 4,000 coins you paid — the squad and the board already blew the other 1,000 on the farewell barbecue, celebrating that you are leaving, and left it on your tab. The club stays in the game, in its division, run by the computer, and keeps its stadium, titles and till. Loans sort themselves out. Only the SECOND club can be sold: your official club, the one in the global ranking, never. (Career)' } },
  { data: '2026-09-14', emoji: '⏱️', titulo: 'Monte das sobras mais rápido: 15s', texto: 'No Monte das sobras dos modos online, cada vez agora tem 15 segundos (eram 20). A fila anda mais rápido e a sala não fica parada esperando quem saiu pra pegar água. O resto é igual: as sobras continuam de graça, quem tem mais buracos escolhe primeiro e, se o tempo estourar, o jogo pega a pior sobra pra você e passa a vez. Contra a máquina o Monte segue sem relógio. (Rápido online e Carreira online)', en: { titulo: 'Leftovers pile is quicker: 15s', texto: 'In the leftovers Pile in online modes, each turn now lasts 15 seconds (it was 20). The queue moves faster and the room no longer waits on whoever stepped away for a drink. Everything else is the same: leftovers are still free, whoever has more holes picks first and, if time runs out, the game takes the worst leftover for you and passes the turn. Against the computer the Pile still has no clock. (Quick online and Career online)' } },
  { data: '2026-09-13', emoji: '🤝', titulo: 'Patrocinador Pontual pagando mais', texto: 'A aposta de temporada ficou mais generosa em todas as divisões: Várzea 4/6/8, Série D 8/12/16, Série C 14/22/30, Série B 24/40/56 e Série A 42/74/106 moedas (não cair / subir / campeão). Já vale pra aposta desta temporada. O Master continua igual. (Carreira)', en: { titulo: 'The One-Season Sponsor pays more', texto: 'The season bet got more generous in every division: Várzea 4/6/8, Série D 8/12/16, Série C 14/22/30, Série B 24/40/56 and Série A 42/74/106 coins (stay up / go up / champion). It already counts for this season\'s bet. The Master stays the same. (Career)' } },
  { data: '2026-09-13', emoji: '😇', titulo: 'Nasceu o São Marcos Antônio FC', texto: 'Mais um clube batizado por apoiador: o São Marcos Antônio FC chega na Série A, com o goleiro de auréola no escudo, manto verde-garrafa e creme e mascote própria — o Marcos em pessoa, de auréola e com o porquinho do lado, que carimba a tela quando o time faz gol. O Marolados FC segue no jogo, agora na Série B. (Carreira e Rápido)', en: { titulo: 'São Marcos Antônio FC is born', texto: 'One more club named by a supporter: São Marcos Antônio FC arrives in Série A, with the haloed goalkeeper on the crest, a bottle-green and cream kit and its own mascot — Marcos himself, halo on, piglet by his side, stamping the screen when the team scores. Marolados FC stays in the game, now in Série B. (Career and Quick match)' } },
  { data: '2026-09-13', emoji: '📊', titulo: 'A barrinha de gás ficou mais fiel', texto: 'Na aba Elenco, a barra do jogador agora acompanha a regra de verdade: fica verde do 1º ao 50º jogo (cai devagar, de 100% a 50%), vira amarela a partir do 51º como aviso e só então cai mais rápido rumo ao cansaço. As regras do jogo não mudaram — só a leitura. (Carreira)', en: { titulo: 'The energy bar is now truer to the rules', texto: 'In the Squad tab the player bar now follows the real rule: it stays green from the 1st to the 50th match (dropping slowly from 100% to 50%), turns yellow from the 51st as a warning and only then drops faster towards fatigue. The game rules did not change — only the reading. (Career)' } },
  { data: '2026-09-13', emoji: '🌱', titulo: 'Sobe um guri da base quando quiser', texto: 'Na aba Elenco, sempre que houver vaga no elenco aparece a caixa da Base: escolha a posição e um dos três garotos do Sub-20 — cada um com a sua historinha — e ele sobe na hora, de graça e sem contrato. É fraquinho, mas enche o banco antes de alguém se machucar; quando chegar jogador de verdade na posição, ele volta pra base sozinho. (Carreira)', en: { titulo: 'Call a kid up from the academy whenever you want', texto: 'In the Squad tab, whenever there is an open spot in the squad the Academy box shows up: pick the position and one of three U-20 kids — each with his own little story — and he comes up right away, free and without a contract. He is weak, but he fills the bench before anyone gets hurt; when a real player arrives for that spot, he goes back to the academy on his own. (Career)' } },
  { data: '2026-09-13', emoji: '🏆', titulo: 'Chegou o Patrocinador Master', texto: 'No começo da temporada, quatro contratos na mesa: Max Joias (1 temporada), Rei das Tintas (2), ERO (3) e Vadico Veículos (5) — quanto mais longo, mais paga por temporada, e o valor trava na divisão em que você assina, suba ou caia. Nova proposta só quando o contrato acabar. O patrocínio de aposta continua, agora como Patrocinador Pontual. (Carreira)', en: { titulo: 'The Master Sponsor has arrived', texto: 'At the start of the season, four contracts on the desk: Max Joias (1 season), Rei das Tintas (2), ERO (3) and Vadico Veículos (5) — the longer, the more it pays per season, and the amount locks in at the division where you sign, up or down. New offers only when the contract ends. The bet sponsor stays, now as the One-Season Sponsor. (Career)' } },
  { data: '2026-09-13', emoji: '🔁', titulo: 'O preparador pode rodiziar sozinho', texto: 'Na aba Elenco, o preparador físico ganhou um interruptor: ligado, ele mesmo poupa quem está cansado antes de cada jogo, com o time já trocado na sua tela — e você pode desligar ou mexer na mão quando quiser. Ninguém machucado, suspenso ou voltando de lesão entra por ele. (Carreira)', en: { titulo: 'The fitness coach can rotate on his own', texto: 'In the Squad tab the fitness coach got a switch: turn it on and he rests tired players before each match himself, with the new XI already on your screen — and you can turn it off or change it by hand whenever you want. Nobody injured, suspended or coming back from injury is picked by him. (Career)' } },
  { data: '2026-09-13', emoji: '🏛️', titulo: 'O Salão dos Batismos ganhou casa própria', texto: 'Entre pela home, abaixo dos modos de jogo: conheça os escudos, mascotes e camisas disponíveis em folhas sobre a mesa e veja todas as torcidas dos donos de Batismo em uma lista com porcentagens. (Todos os modos)', en: { titulo: 'The Hall of Named Clubs has its own entrance', texto: 'Enter from the home screen below the game modes: explore available crests, mascots and shirts on paper sheets and see every named-club fanbase in a percentage list. (All modes)' } },
  { data: '2026-09-12', emoji: '💛', titulo: 'Conheça e compare os apoios', texto: 'Os planos ganharam uma apresentação mais clara, comparação lado a lado e um atalho compacto para conhecer os controles de acelerar e pular. (Apoios e Carreira)', en: { titulo: 'Explore and compare support plans', texto: 'Plans now have a clearer presentation, side-by-side comparison and a compact shortcut to explore speed and skip controls. (Support and Career)' } },
  { data: '2026-09-12', emoji: '🍀', titulo: 'Seven City de cara nova', texto: 'O Seven City, clube batizado por apoiador, está de cara nova: escudo com o trevo e o 7 dourado, manto verde-mata e creme com dourado e mascote própria — o Trevo, de terno e cartola, que carimba a tela quando o time faz gol. (Carreira e Rápido)', en: { titulo: 'Seven City has a new look', texto: 'Seven City, a club named by a supporter, has a new look: a crest with the clover and the golden 7, a forest-green and cream kit with gold and its own mascot — the Clover, in suit and top hat, which stamps the screen when the team scores. (Career and Quick)' } },
  { data: '2026-09-12', emoji: '😓', titulo: 'Seus jogadores agora cansam', texto: 'Ao chegar na Série C (quem já está em C, B ou A libera na próxima rodada), cada jogo como titular gasta gás e o banco recupera — e isso atravessa as temporadas, não zera na virada. Uns 54 jogos ele aguenta, depois rende menos e pode se machucar de desgaste, e lesão volta aos poucos. A barrinha aparece na aba Elenco, e o preparador sugere o rodízio — quem decide é você. (Carreira)', en: { titulo: 'Your players get tired now', texto: 'Once you reach Série C (already in C, B or A? it unlocks next round), every match as a starter burns energy and the bench recovers it — and it carries over between seasons, it doesn\'t reset. Around 54 matches he can take, then he performs worse and can break down, and injuries come back gradually. The bar shows in the Squad tab, and the fitness coach suggests the rotation — you decide. (Career)' } },
  { data: '2026-09-12', emoji: '🏥', titulo: 'O Departamento Médico saiu do estádio', texto: 'Ninguém mais fica imune a lesão: a obra saiu da árvore do estádio e a regra é igual pra todo mundo — quem rodizia o elenco se machuca menos. (Carreira)', en: { titulo: 'The Medical Department left the stadium', texto: 'Nobody is immune to injuries anymore: the build left the stadium tree and the rule is the same for everyone — rotate your squad and you get injured less. (Career)' } },
  { data: '2026-09-12', emoji: '⚡', titulo: 'O pênalti decisivo ficou de verdade', texto: 'Aquele pênalti no fim do jogo agora acontece num estádio de verdade: você escolhe o canto, trava a força na barra e vê o goleiro voar. Antes era só o resultado na tela. (Carreira)', en: { titulo: 'The decisive penalty got real', texto: 'That late penalty now happens in a real stadium: you pick the corner, lock the power on the bar and watch the keeper dive. Before it was just the result on screen. (Career)' } },
  { data: '2026-09-12', emoji: '📲', titulo: 'As imagens de compartilhar ficaram iguais ao jogo', texto: 'A figura do jornal O Martelo e a do seu elenco agora saem com a cara que o jogo tem hoje: escudo, manto, mascote e os rostos das lendas. E saem no idioma que você escolheu. (Carreira)', en: { titulo: 'The share images now look like the game', texto: 'The O Martelo newspaper image and your squad image now come out with the look the game has today: crest, kit, mascot and the legends\' faces. And they come out in the language you picked. (Career)' } },
  { data: '2026-09-11', emoji: '🌍', titulo: 'A Copa do Mundo é do clube principal', texto: 'Quem tem um segundo clube comprado: agora só o seu clube principal disputa a Copa do Mundo — é ele que conta no ranking global, e é ele que vai. O segundo clube segue normal em tudo o mais: liga, copas, mercado e patrimônio. (Carreira)', en: { titulo: 'The World Cup belongs to your main club', texto: 'If you bought a second club: now only your main club plays the World Cup — it\'s the one that counts in the global ranking, and it\'s the one that goes. The second club carries on as usual in everything else: league, cups, market and assets. (Career)' } },
  { data: '2026-09-10', emoji: '⚽', titulo: 'As lendas ganharam rosto', texto: 'Avatares das lendas no campinho, nas cartas e na revelação do leilão, junto do novo visual da carreira: patrocínios, estádio, placares, ligas, copas e jornal. (Carreira, Rápido e Minhas Ligas)', en: { titulo: 'The legends got a face', texto: 'Legend avatars on the pitch, on the cards and at the auction reveal, together with the new career look: sponsorships, stadium, scoreboards, leagues, cups and newspaper. (Career, Quick and My Leagues)' } },
  { data: '2026-09-10', emoji: '🐮', titulo: 'Nasceu o Leite de Verdade FC', texto: 'Mais um clube batizado por apoiador: o Leite de Verdade FC chega na Série A, com escudo do curral, manto creme e preto malhado com dourado e mascote própria — a Mimosa, a vaca de chapéu de palha que carimba a tela quando o time faz gol. O Barcenite FC segue no jogo, agora na Série B. (Carreira e Rápido)', en: { titulo: 'Leite de Verdade FC is born', texto: 'One more club named by a supporter: Leite de Verdade FC arrives in Série A, with a barnyard crest, a cream and black spotted kit with gold and its own mascot — Mimosa, the straw-hat cow that stamps the screen when the team scores. Barcenite FC stays in the game, now in Série B. (Career and Quick)' } },
  { data: '2026-09-09', emoji: '🐍', titulo: 'Tricolor do Arruda FC de cara nova', texto: 'O Tricolor do Arruda FC, clube batizado por apoiador, está de cara nova: o estádio do Arruda no escudo, manto tricolor com as cores medidas na camisa e a Cobra Coral de punhos fechados, que carimba a tela quando o time faz gol. (Carreira e Rápido)', en: { titulo: 'Tricolor do Arruda FC has a new look', texto: 'Tricolor do Arruda FC, a club named by a supporter, has a new look: the Arruda stadium on the crest, a tricolor kit with the colors measured on the shirt and the Coral Snake with clenched fists, which stamps the screen when the team scores. (Career and Quick)' } },
  { data: '2026-09-09', emoji: '🟢', titulo: 'Xurupitas FC de cara nova', texto: 'O Xurupitas FC, clube batizado por apoiador, está de cara nova: escudo novo, manto verde-escuro e creme com a gosma escorrendo e mascote própria — o Xurupita, a gosma verde de sorriso maroto, que carimba a tela quando o time faz gol. (Carreira e Rápido)', en: { titulo: 'Xurupitas FC has a new look', texto: 'Xurupitas FC, a club named by a supporter, has a new look: new crest, dark green and cream kit with dripping slime and its own mascot — Xurupita, the green slime with a cheeky grin, which stamps the screen when the team scores. (Career and Quick)' } },
  { data: '2026-09-09', emoji: '🐛', titulo: 'Bicho da Seda de cara nova', texto: 'O Bicho da Seda, clube batizado por apoiador, está de cara nova: escudo novo, manto alvinegro com os fios de seda e mascote própria — o Bicho da Seda de óculos escuros, que carimba a tela quando o time faz gol. (Carreira e Rápido)', en: { titulo: 'Bicho da Seda has a new look', texto: 'Bicho da Seda, a club named by a supporter, has a new look: new crest, black-and-white kit with silk threads and its own mascot — the Silkworm in sunglasses, which stamps the screen when the team scores. (Career and Quick)' } },
  { data: '2026-09-09', emoji: '🐟', titulo: 'Nasceu o Bagres de Wall Street FC', texto: 'Mais um clube batizado por apoiador: o Bagres de Wall Street FC chega na Série A, com escudo de bolsa de valores, manto preto e dourado com listras brancas e mascote própria — o Bagre Investidor, de terno, coroa e charuto, que carimba a tela quando o time faz gol. O Manfré FC segue no jogo, agora na Série B. (Carreira e Rápido)', en: { titulo: 'Bagres de Wall Street FC is born', texto: 'One more club named by a supporter: Bagres de Wall Street FC arrives in Série A, with a stock-exchange crest, a black and gold kit with white stripes and its own mascot — the Investor Catfish, in suit, crown and cigar, which stamps the screen when the team scores. Manfré FC stays in the game, now in Série B. (Career and Quick)' } },
  { data: '2026-09-08', emoji: '🏆', titulo: 'Acompanhe a sala inteira', texto: 'Placares animados, Jogos + Tabela juntos e Copas organizadas por fase, com gols dos outros jogos e pênaltis compactos, no celular e no computador. (Online)', en: { titulo: 'Follow the whole room', texto: 'Animated scoreboards, Matches + Table together and Cups organized by stage, with goals from the other matches and compact penalties, on phone and computer. (Online)' } },
  { data: '2026-09-09', emoji: '🙏', titulo: 'Nasceu o Só Deus Sabe FC', texto: 'Mais um clube batizado por apoiador: o Só Deus Sabe FC chega na Série A, com escudo das mãos em prece, manto preto e dourado com nuvens brancas e mascote própria — o Anjo, que cai de joelhos no gramado e carimba a tela quando o time faz gol. O Nightfull FC segue no jogo, agora na Série B. (Carreira e Rápido)', en: { titulo: 'Só Deus Sabe FC is born', texto: 'One more club named by a supporter: Só Deus Sabe FC arrives in Série A, with a praying-hands crest, a black and gold kit with white clouds and its own mascot — the Angel, who drops to his knees on the pitch and stamps the screen when the team scores. Nightfull FC stays in the game, now in Série B. (Career and Quick)' } },
  { data: '2026-09-09', emoji: '🎙️', titulo: 'Nasceu o Fala D10', texto: 'Mais um clube batizado por apoiador: o Fala D10 chega na Série A, com escudo preto e dourado, manto preto com detalhes dourados e mascote própria — o D10, de megafone na mão, que carimba a tela quando o time faz gol. O Skyy FC segue no jogo, agora na Série D. (Carreira e Rápido)', en: { titulo: 'Fala D10 is born', texto: 'One more club named by a supporter: Fala D10 arrives in Série A, with a black and gold crest, a black kit with gold details and its own mascot — D10, megaphone in hand, who stamps the screen when the team scores. Skyy FC stays in the game, now in Série D. (Career and Quick)' } },
  { data: '2026-09-09', emoji: '🔊', titulo: 'Nasceu o Bonança SSFC', texto: 'Mais um clube batizado por apoiador: o Bonança SSFC chega na Série C, com escudo do paredão de caixas de som, manto preto e amarelo com listra vermelha e mascote própria — o Selecta, o paredão de camisa 10 que carimba a tela quando o time faz gol. (Carreira e Rápido)', en: { titulo: 'Bonança SSFC is born', texto: 'One more club named by a supporter: Bonança SSFC arrives in Série C, with a speaker-wall crest, a black and yellow kit with a red stripe and its own mascot — Selecta, the speaker wall in the number 10 shirt that stamps the screen when the team scores. (Career and Quick)' } },
  { data: '2026-09-08', emoji: '🐓', titulo: 'Nasceu o Briga de Galo FC', texto: 'Mais um clube batizado por apoiador: o Briga de Galo FC chega na Série A, com escudo dos dois galos, manto preto e branco listrado com dourado e mascote própria — o Galo de punhos fechados, que carimba a tela quando o time faz gol. O Vasco da Grana segue no jogo, agora na Série D. (Carreira e Rápido)', en: { titulo: 'Briga de Galo FC is born', texto: 'One more club named by a supporter: Briga de Galo FC arrives in Série A, with a two-roosters crest, a black and white striped kit with gold and its own mascot — the Rooster with clenched fists, who stamps the screen when the team scores. Vasco da Grana stays in the game, now in Série D. (Career and Quick)' } },
  { data: '2026-09-08', emoji: '🎁', titulo: 'Dono de batismo leva o escudo pra qualquer nome', texto: 'Quem tem clube batizado agora carrega escudo, mascote e manto no time que estiver usando, mesmo que troque o nome. É pelo e-mail do dono — o clube batizado continua no baralho com o nome fixo de sempre. (Carreira, Rápido e Online)', en: { titulo: 'Club founders keep their crest under any name', texto: 'Whoever owns a named club now carries crest, mascot and kit on whatever team they are using, even after renaming it. It follows the owner\'s e-mail — the named club stays in the deck with its usual fixed name. (Career, Quick and Online)' } },
  { data: '2026-09-08', emoji: '⏱️', titulo: 'Convocação da Copa do Mundo: 80 segundos', texto: 'Na Copa do Mundo online (sala de Copa, Liga + Mundo e ligas), o tempo pra convocar os 11 da seleção passou a ser 80 segundos — antes eram 135. Continua avançando na hora em que todo mundo fecha o time; o relógio é só o teto pra quem dorme. (Online)', en: { titulo: 'World Cup call-up: 80 seconds', texto: 'In the online World Cup (Cup room, League + World and leagues), the time to call up the national team\'s 11 is now 80 seconds — it used to be 135. It still moves on the moment everyone closes their team; the clock is just the ceiling for whoever dozes off. (Online)' } },
  { data: '2026-09-07', emoji: '📰', titulo: 'O online de cara nova', texto: 'Salas ilustradas, O Martelo com as notas da redação e um novo visual para o pacote do campeão e a decisão da próxima partida, no celular e no computador. (Online)' },
  { data: '2026-09-07', emoji: '🎮', titulo: 'Nasceu o Sistematizados FC', texto: 'Mais um clube batizado por apoiador: o Sistematizados FC entra na Série D no lugar do Coliseu United, com escudo roxo e prata, manto preto e roxo e mascote próprio — o Sistematizado, o streamer de headset que carimba a tela quando o time faz gol. Quem já tinha carreira com o Coliseu United continua no mesmo time, só com a cara nova. (Carreira e Rápido)' },
  { data: '2026-09-07', emoji: '🌑', titulo: 'Nasceu o Nova Eclipse FC', texto: 'Mais um clube batizado por apoiador: o Nova Eclipse FC entra na Série C no lugar do Zequinha SAF, com escudo prata, manto preto com pinceladas brancas e mascote próprio — o Eclipse, um jogador encapuzado que carimba a tela quando o time faz gol. Quem já tinha carreira com o Zequinha SAF continua no mesmo time, só com a cara nova. (Carreira e Rápido)' },
  { data: '2026-09-07', emoji: '🕵️', titulo: 'Chegou o OLHEIRO: sondar jogador voltou', texto: 'Na janela antes do leilão, a aba 🕵️ Sondar agora deixa marcar um JOGADOR de outro clube além do técnico — o sondado vai pro pregão e você briga por ele (1 jogador e 1 técnico por leilão, só quem está sem contrato). Todo mundo sonda foi profissional, bom jogador e promessa; com o Olheiro ⭐ Craque você sonda os craques (e vê o nível deles no elenco), e o 👑 Lenda sonda tudo, lenda inclusive. E o grupo VIP do WhatsApp abriu pro Craque também. (Carreira)' },
  { data: '2026-09-04', emoji: '📰', titulo: 'O Martelo agora sai no jogo rápido offline', texto: 'Quando o torneio contra a máquina acaba, sai a edição do jornal O Martelo — manchete do campeão, os donos do torneio, o artilheiro e uma nota de redação pros cinco primeiros, pra você e pro lanterna. Dá pra mandar a capa no grupo. Antes isso só existia nas salas online. (Jogo Rápido)' },
  { data: '2026-09-06', emoji: '🐟', titulo: 'Nasceu o Bagres 1993', texto: 'Mais um clube batizado por apoiador: o Bagres 1993 entra direto na Série A. Escudo, manto verde e branco e mascote próprios — o Bagre, um bagre de boné que carimba a tela quando o time faz gol. (Carreira e Rápido)' },
  { data: '2026-09-05', emoji: '🪟', titulo: 'Nasceu o Vidraceiro FC', texto: 'Mais um clube batizado por apoiador: o Vidraceiro FC entra direto na Série A. Escudo, manto azul-vidro e preto e mascote próprios — o Cristal, uma chapa de vidro que carimba a tela quando o time faz gol. (Carreira e Rápido)' },
  { data: '2026-09-05', emoji: '🐂', titulo: 'Nasceu o Final Boss FC', texto: 'Mais um clube batizado por apoiador: o Final Boss FC entra na Série C no lugar do Ponte Branca, com escudo, manto branco com faixa vermelha e preta e mascote próprio — o Boss, um touro que carimba a tela quando o time faz gol. Quem já tinha carreira com o Ponte Branca continua no mesmo time, só com a cara nova. (Carreira e Rápido)' },
  { data: '2026-09-04', emoji: '⚡', titulo: 'Nasceu o Stocco FC', texto: 'Mais um clube batizado por apoiador: o Stocco FC entra na Série C no lugar do Semervilha, com escudo, manto roxo e preto e mascote próprios — o Relâmpago, um lobo que carimba a tela quando o time faz gol. Quem já tinha carreira com o Semervilha continua no mesmo time, só com a cara nova. (Carreira e Rápido)' },
  { data: '2026-09-03', emoji: '🐉', titulo: 'Nasceu a Corporação Capsule FC', texto: 'Mais um clube batizado por apoiador: a Corporação Capsule FC entra na Série B no lugar do Real Tabuleiro, com escudo, manto preto e azul e mascote próprios — o DragonBola, um dragão que carimba a tela quando o time faz gol. Quem já tinha carreira com o Real Tabuleiro continua no mesmo time, só com a cara nova. (Carreira e Rápido)' },
  { data: '2026-09-03', emoji: '🇫🇷', titulo: 'O Zidane agora é o da Juventus', texto: 'No baralho do mundo, a carta do Zinedine Zidane deixou de ser a do Real Madrid de 2002 e passou a ser a da Juventus de 1998 — o ano da Bola de Ouro dele. Mesmo nível de lenda, mesmo preço no pregão: muda o clube e o ano na carta. Quem já tem a carta velha guardada no álbum ou no elenco continua com ela do jeito que estava. (Todos os modos)' },
  { data: '2026-09-02', emoji: '⏱️', titulo: 'Mais tempo pra convocar, Monte mais ágil', texto: 'Na Copa do Mundo online depois da liga, a convocação dos 11 agora tem 135 segundos (eram 65) — e segue avançando na hora em que todo mundo fecha o time. E no Monte das sobras do online cada vez passou de 45 pra 30 segundos, pra sala não ficar esperando. (Rápido online)' },
  { data: '2026-09-02', emoji: '🧦', titulo: 'Nasceu o Jurubeba FC', texto: 'Mais um clube batizado por apoiador: o Jurubeba FC entra na Série B no lugar do Ferroviário do Sul, com escudo, manto amarelo e verde-petróleo e mascote próprios — a Meia na Canela, uma meia de óculos escuros que carimba a tela quando o time faz gol. Quem já tinha carreira com o Ferroviário do Sul continua no mesmo time, só com a cara nova. (Carreira e Rápido)' },
  { data: '2026-09-01', emoji: '🌐', titulo: 'LIGA + COPA DO MUNDO na mesma noite', texto: 'Ao criar a sala tem uma opção nova em "depois da liga": 🌐 Liga + Mundo. A liga roda igual sempre e, quando ela acaba, os 20 times viram seleções e rola a Copa do Mundo — com mais 4 seleções da máquina pra fechar 24. Quem terminou a liga em 1º escolhe a seleção primeiro, o 2º escolhe depois, e assim por diante; os bots ficam com as sobras. Campeão do mundo leva título no Rank, a carta do campeão e o troféu na estante da sala. (Online)' },
  { data: '2026-08-31', emoji: '🌍', titulo: 'COPA DO MUNDO com a sua turma', texto: 'Modo novo ao criar sala: cada um pega UMA seleção e convoca 11 jogadores do país — sem leilão. Aí rola a Copa inteira na tela de todo mundo ao mesmo tempo: 4 grupos, mata-mata ida e volta e final única. Campeão do mundo leva título no Rank, a carta do campeão e o troféu na estante da sala. (Online)' },
  { data: '2026-08-31', emoji: '👑', titulo: 'A elite do jogo agora se chama SÉRIE A', texto: 'Os clubes batizados que jogam o rápido online e são os rivais da carreira estavam numa divisão chamada Série D — e era justamente a mais forte e a mais cara. Trocamos a letra: essa turma agora é a SÉRIE A, e os clubes que estavam na A passam pra D. Quem já tem carreira em andamento não muda NADA: seu time, sua divisão e sua tabela continuam exatamente como você deixou — a troca só vale pra carreira nova. (Carreira e Rápido)' },
  { data: '2026-08-30', emoji: '🐦‍⬛', titulo: 'O Manfré FC ganhou cara nova', texto: 'O dono mandou a arte dele e o clube trocou de pele: escudo, mascote e manto novos — a Gralha agora carimba a tela quando o time faz gol, e o manto virou vermelho e azul. Mesma vaga, mesmo elenco, mesmo tudo: quem já tinha carreira com o Manfré FC (ou com o antigo Livre-pool) continua no mesmo time, só com a cara nova.' },
  { data: '2026-08-29', emoji: '⚖️', titulo: 'O Rank agora é por pontos', texto: 'Na barrinha de troféus da sala (Rápido e Minhas Ligas), a aba 🏆 Rank passou a somar pontos em vez de comparar títulos: título da liga vale +30, a copa vale +20 e cair pra zona de rebaixamento tira 10 — mas ninguém fica negativo, o pior caso é zero. Artilheiro continua ganhando troféu na Estante, só não conta ponto. As regras ficam escritas ali embaixo do Rank, e na sua liga o dono pode mudar tudo isso em ⚙️ Ajustes.' },
  { data: '2026-08-29', emoji: '🔨', titulo: 'Criar sala ficou simples', texto: 'A tela de criar sala foi refeita: agora começa perguntando UMA coisa — o que vocês vão jogar — em cartões grandes que explicam cada modo. Escolheu, as configurações daquele modo abrem embaixo já no ponto, e o botão de criar fica no fim. Nenhuma opção sumiu: baralho, formação, duplas, chat, tempo do leilão e o resto continuam lá, só na ordem certa.' },
  { data: '2026-08-29', emoji: '🏆', titulo: 'MINHAS LIGAS — a sala da sua turma que NÃO acaba', texto: 'Sala rápida some quando a galera sai. A Liga não: é sempre a MESMA sala, com dia e hora combinados, e a estante guardando campeão, artilheiro e rebaixado temporada após temporada — com o ranking somando tudo pela regra que o dono escolher. Ela é só da sua turma: entra com o código + a senha, e não aparece em lista nenhuma. Criar é benefício do 👑 Lenda (até 5 ligas); pra JOGAR não precisa de nada — é só alguém te passar o código.' },
  { data: '2026-08-28', emoji: '🧢', titulo: 'CHEGARAM OS TÉCNICOS!', texto: 'No Modo Carreira agora seu clube tem TÉCNICO: 105 comandantes com categoria igual à das cartas (👑 Lenda a 🤎 Foi profissional), cada um com o nível dele — que soma no time em toda partida da liga — e com os esquemas que ele usa de verdade. Pra contratar: na janela antes do leilão, aba 🕵️ SONDAR, você marca o técnico que quer e briga por ele no pregão, no envelope, igual jogador. Contrato de 5 temporadas, com salário na folha.' },
  { data: '2026-08-28', emoji: '🎽', titulo: '15 formações — mas quem abre elas é o técnico', texto: 'O jogo passou de 5 pra 15 esquemas (4-2-4, 5-4-1, losango, árvore de Natal, 3-5-2 com alas, líbero e mais) e o campinho ficou maior, com goleiro, zaga e ataque sempre no mesmo lugar. Atenção, que é a parte nova: SEM técnico o time só joga o esquema que ele já treina — quem abre as outras formações é o técnico que você contratar, e quanto maior a categoria dele, mais esquemas ele traz (👑 Lenda traz 5).' },
  { data: '2026-08-27', emoji: '📰', titulo: 'O MARTELO agora sai no Rápido Online', texto: 'Quando a liga (e a Copa) acabam numa sala online, o jornal do jogo fecha a noite: manchete com quem levou a liga e quem levou a Copa, os donos da noite, e uma linha escrita pra CADA técnico da sala — do campeão ao lanterna, passando por quem ficou a uma posição de se classificar. Tem botão pra mandar a capa no grupo como imagem.' },
  { data: '2026-08-27', emoji: '🎁', titulo: 'O pacote do campeão espera você', texto: 'No Rápido, o pacote de carta do campeão não abre mais sozinho quando o tempo acaba: ele fica lacrado até você tocar, pra ninguém perder a hora de ver qual carta saiu. A carta continua sendo sua de qualquer jeito, mesmo se você fechar a tela.' },
  { data: '2026-08-24', emoji: '🅰️', titulo: 'Gols e assistências também no Rápido', texto: 'No Rápido (online e contra a CPU): o campinho do seu time agora mostra os selos de ⚽ gols e 🅰️ assistências em cada jogador — antes o campinho vinha sem número nenhum — e do lado da artilharia nasceu a lista dos 🅰️ Garçons, com quem mais dá passe pro gol na liga.' },
  { data: '2026-08-24', emoji: '🔁', titulo: 'Dá pra trocar os jogadores de lado', texto: 'No Modo Carreira, no campinho do Elenco: toque em dois titulares da mesma posição e eles trocam de lugar — o canhoto vai pra esquerda, o destro pra direita, os dois atacantes invertem. É só a organização do seu campinho: não muda a força do time nem o resultado.' },
  { data: '2026-08-24', emoji: '🅰️', titulo: 'Chegaram as assistências', texto: 'Todo gol agora mostra quem deu o passe — na liga e em QUALQUER copa (Copa Legends, Copa do Brasil, Supercopa e Copa do Mundo). Aparece embaixo do placar, no seu elenco (⚽ e 🅰️ lado a lado) e numa aba nova no Rank com os melhores garçons de cada série. Gol de jogada individual aparece assim mesmo, com todas as letras. Nenhum resultado das suas temporadas mudou.' },
  { data: '2026-08-24', emoji: '📼', titulo: 'O jornal ganhou memória', texto: 'No Modo Carreira: o jornal do fim de temporada agora guarda a história do seu clube e abre a página "O Jornal Lembra" quando ela merece manchete — 3º título seguido, dinastia, o jejum que acabou, a 10ª temporada seguida na Série A, a primeira vez na elite, a primeira Copa. Cada taça (ou seca) vira memória.' },
  { data: '2026-08-23', emoji: '📺', titulo: 'A TV agora paga cota extra pelo seu vídeo', texto: 'No Modo Carreira: a Rede Martelo TV ganhou casa fixa em Clube › Patrocínio — lá dá pra ver quanto o contrato da sua divisão paga por temporada e televisionar seu jogo: grava um vídeo (15s+) da tela jogando, posta no Instagram, TikTok ou YouTube marcando @leilaolegendscom, cola o link e ganha +15 moedas na caixa do clube. Um vídeo por temporada — e, como toda cota de TV, pode atrasar um pouquinho, mas cai.' },
  { data: '2026-08-23', emoji: '🦁', titulo: 'O Império Samambaia virou Leão da Estradinha', texto: 'O dono rebatizou o clube em homenagem ao time do coração dele, o Rio Branco-PR — o Leão da Estradinha de 1913. Escudo, mascote e manto novos (vermelho e branco), mesma vaga na Série A e mesmo elenco. Quem já tinha carreira com o Império Samambaia continua no mesmo time, só com a cara nova.' },
  { data: '2026-08-23', emoji: '🏅', titulo: 'A sala online ganhou estante de troféus', texto: 'No Rápido online: apareceu uma barrinha no rodapé, do jeito da carreira, com o histórico da sala — 🏆 Rank mostra quem lidera somando as temporadas, 🏅 Estante empilha os troféus de cada um (e o Troféu Mico do lanterna) e 📜 Temporadas guarda campeão, campeão da copa e artilheiro de cada partida. Só a galera pontua: bot não entra.' },
  { data: '2026-08-23', emoji: '🐺', titulo: 'Nasceu o Papão United Madrid', texto: 'Mais um clube batizado por apoiador: o Papão United Madrid entra na Série D no lugar do Santos Dumont, com escudo e mascote próprios — O Papão, um lobo chifrudo de faixa azul e branca que carimba a tela quando o time faz gol. O Alfacehh desceu pra Série B e segue com tudo dele. Quem já tinha carreira com o Santos Dumont continua no mesmo time, só com a cara nova.' },
  { data: '2026-08-21', emoji: '🐶', titulo: 'Nasceu o São Luiz FC', texto: 'Mais um clube batizado por apoiador: o São Luiz FC entra na Série D no lugar do Flamengo do Sertão, com escudo e mascote próprios — o Luizão, um pitbull que carimba a tela quando o time faz gol. Quem já tinha carreira com o Flamengo do Sertão continua no mesmo time, só com a cara nova.' },
  { data: '2026-08-21', emoji: '🦇', titulo: 'Nasceu o Theuzudo FC', texto: 'Mais um clube batizado por apoiador: o Theuzudo FC entra na Série B no lugar do Comercial do Norte, com escudo e mascote próprios — o Theuzinho, um morcego laranja e preto que carimba a tela quando o time faz gol. Quem já tinha carreira com o Comercial do Norte continua no mesmo time, só com a cara nova.' },
  { data: '2026-08-21', emoji: '🏆', titulo: 'O fim da temporada virou momento', texto: 'No Modo Carreira: quando a temporada fecha, uma tela conta o que aconteceu com o clube — subiu de divisão, caiu, foi campeão — com a divisão de onde saiu, pra onde vai e o que você levou de prêmio, caixa, patrocínio e torcida.' },
  { data: '2026-08-21', emoji: '🔨', titulo: 'Pregão mais direto', texto: 'No leilão de todos os modos: suas vagas e o dinheiro ficam sempre na barra de cima, as regras do pregão viraram um botão ❓ ali do lado — e quem está começando ganha a explicação inteira no primeiro pregão da partida.' },
  { data: '2026-08-21', emoji: '🧹', titulo: 'Virada de temporada mais limpa', texto: 'No Modo Carreira: a escolha que trava o jogo agora fica sozinha em cima, com o selo "sua vez" — e o que já aconteceu (fechamento do caixa, patrocínio pago) virou uma linha que leva direto pro lugar onde a coisa está inteira.' },
  { data: '2026-08-21', emoji: '🪜', titulo: 'Carreira com menu embaixo', texto: 'No Modo Carreira: Jogos, Tabelas, Elenco, Rank e Clube saíram do meio da página e viraram um menu fixo no rodapé — e dentro do Clube e do Elenco as abas de dentro também param de sumir quando você rola. Role até onde rolar, você troca de aba na hora e continua vendo rodada, posição e caixa numa faixa fina no topo.' },
  { data: '2026-08-21', emoji: '🤝', titulo: 'Patrocínio mais direto', texto: 'No Modo Carreira: a escolha do patrocínio virou dois toques — primeiro a meta da temporada, depois a marca que estampa a camisa — e a tabela de quanto cada divisão paga foi pra aba Clube › Patrocínio.' },
  { data: '2026-08-20', emoji: '🏠', titulo: 'Home nova, com menu embaixo', texto: 'A tela de abertura ficou mais limpa: um menu fixo no rodapé (Início, Regras, Álbum, Ranking, Apoiar) e o passo a passo de como funciona uma partida, pra quem está chegando agora entender o jogo sem precisar perguntar.' },
  { data: '2026-08-20', emoji: '🌎', titulo: 'Libertadores', texto: 'No Rápido (online e contra a CPU): escolha "Liga + Liberta" e, quando a liga acabar, os 8 primeiros entram numa Libertadores de 32 clubes — 8 grupos de 4, passam 2, e a final é jogo único.' },
  { data: '2026-08-17', emoji: '🏅', titulo: 'Ranking agora é por pontos', texto: 'No Modo Carreira: Copa do Mundo vale 200, Copa do Brasil 30, Série A 20, Supercopa 15, B 10, C 5, D 3 e Várzea 1 — quem tem mais título soma mais, e a coluna PTS mostra a conta.' },
  { data: '2026-08-17', emoji: '🌍', titulo: 'Copa do Mundo com 24 seleções', texto: 'No Modo Carreira: entraram Croácia, Dinamarca, Peru e Equador — agora são 4 grupos de 6, e o TOP 24 do ranking de clubes garante vaga.' },
  { data: '2026-08-16', emoji: '🏠', titulo: 'Home nova', texto: 'A tela de abertura mudou: quem já tem carreira continua de cara, e cada botão diz o que você ganha ali.' },
  { data: '2026-08-16', emoji: '🔓', titulo: 'Carreira sem cadastro', texto: 'Dá pra jogar a primeira temporada inteira sem criar conta — o time fica guardado no aparelho.' },
  { data: '2026-08-16', emoji: '🪜', titulo: 'Continuar com esse time', texto: 'No fim da partida rápida, o time que você montou pode virar uma carreira, com a liga inteira junto.' },
  { data: '2026-08-16', emoji: '🏆', titulo: 'Copa do Brasil e Supercopa', texto: 'No Modo Carreira: a Copa virou Copa do Brasil, e o campeão dela encara o campeão da Série A na Supercopa.' },
  { data: '2026-08-08', emoji: '🤝', titulo: 'Duplas (beta)', texto: 'No Rápido Online: chame um amigo pra dividir o comando do MESMO time — cada um manda em 3 das 6 posições.' },
  { data: '2026-08-05', emoji: '💰', titulo: 'Patrocínio virou aposta', texto: 'No Modo Carreira: escolha a meta da temporada (não cair, acesso ou título) e fature de acordo.' },
  { data: '2026-08-04', emoji: '🏥', titulo: 'Departamento Médico', texto: 'No Modo Carreira: a última obra do estádio acaba com as lesões do seu elenco pra sempre.' },
  { data: '2026-08-02', emoji: '🚀', titulo: 'Contratos em massa', texto: 'Venceram vários contratos de uma vez? Renove ou libere TODOS num botão só.' },
  { data: '2026-07-28', emoji: '💰', titulo: 'Finanças do clube', texto: 'No Modo Carreira: extrato de tudo que entra e sai, e o lucro de cada venda.' },
  { data: '2026-07-20', emoji: '💼', titulo: 'SAF', texto: 'No Modo Carreira: compre a SAF de um clube da Série D, leve metade dos lucros dele e empreste jogadores.' },
  { data: '2026-07-12', emoji: '🏟️', titulo: 'Estádio', texto: 'No Modo Carreira: construa arquibancada, refletor, telão e cobertura — o desenho cresce e a bilheteria rende.' },
]

/**
 * As novidades que a HOME mostra — e é isto que faz ela encolher sozinha:
 * só entra o que é recente, e nunca mais que `max`. Novidade velha some sem
 * ninguém precisar apagar nada (era o problema: 17 avisos empilhados pra
 * sempre). O piso de `min` existe só pra tela nunca ficar vazia numa semana
 * parada.
 */
export function novidadesDaVez(hoje = new Date(), dias = 45, max = 5, min = 3): Novidade[] {
  const corte = hoje.getTime() - dias * 86400000
  const recentes = NOVIDADES.filter(n => {
    const t = Date.parse(n.data)
    return Number.isFinite(t) && t >= corte
  })
  const lista = recentes.length >= min ? recentes : NOVIDADES.slice(0, min)
  return lista.slice(0, max)
}
