import type { HistCardData, QuestionKey } from './types'

const GP: QuestionKey[] = ['gols', 'jogos']
const GTA: QuestionKey[] = ['gols', 'titulos', 'assists']
const GT: QuestionKey[] = ['gols', 'titulos']
const TA: QuestionKey[] = ['titulos', 'assists']
const GJ: QuestionKey[] = ['gols', 'jogos']
const GAT: QuestionKey[] = ['gols', 'assists', 'titulos']
const GJT: QuestionKey[] = ['gols', 'jogos', 'titulos']
const TAJ: QuestionKey[] = ['titulos', 'altura', 'jogos']

export const HIST_CARDS: HistCardData[] = [
  // ── MÍTICA (ouro) ──────────────────────────────────────────────
  {
    id: 'pele-1970', nome: 'Pelé', apelido: 'O Rei', ano: 1970, nascimento: 1940,
    flag: '🇧🇷', raridade: 'mitica', posicao: 'Atacante', clube: 'Santos / Brasil',
    cor: '#FFB800',
    atributos: { gols: 8, titulos: 3, altura: 173, assists: 6, jogos: 6 },
    perguntas: ['gols', 'titulos', 'assists'],
    wikiTitle: 'Pelé',
  },
  {
    id: 'maradona-1986', nome: 'Diego Maradona', apelido: 'El Pibe de Oro', ano: 1986, nascimento: 1960,
    flag: '🇦🇷', raridade: 'mitica', posicao: 'Meia', clube: 'Napoli / Argentina',
    cor: '#FFB800',
    atributos: { gols: 5, titulos: 2, altura: 165, assists: 5, jogos: 7 },
    perguntas: ['gols', 'titulos', 'assists'],
    wikiTitle: 'Diego Maradona',
  },
  {
    id: 'r9-1998', nome: 'Ronaldo Nazário', apelido: 'O Fenômeno', ano: 1998, nascimento: 1976,
    flag: '🇧🇷', raridade: 'mitica', posicao: 'Atacante', clube: 'Inter / Brasil',
    cor: '#FFB800',
    atributos: { gols: 4, titulos: 2, altura: 183, assists: 3, jogos: 7 },
    perguntas: GTA,
    wikiTitle: 'Ronaldo (Brazilian footballer)',
  },
  {
    id: 'zidane-1998', nome: 'Zinedine Zidane', apelido: 'Zizou', ano: 1998, nascimento: 1972,
    flag: '🇫🇷', raridade: 'mitica', posicao: 'Meia', clube: 'Juventus / França',
    cor: '#FFB800',
    atributos: { gols: 2, titulos: 6, altura: 185, assists: 4, jogos: 7 },
    perguntas: ['gols', 'titulos', 'assists'],
    wikiTitle: 'Zinedine Zidane',
  },
  {
    id: 'ronaldinho-2005', nome: 'Ronaldinho', apelido: 'Dinho', ano: 2005, nascimento: 1980,
    flag: '🇧🇷', raridade: 'mitica', posicao: 'Meia', clube: 'Barcelona',
    cor: '#FFB800',
    atributos: { gols: 17, titulos: 11, assists: 13, jogos: 45 },
    perguntas: GAT,
    wikiTitle: 'Ronaldinho',
  },
  {
    id: 'messi-2012', nome: 'Lionel Messi', apelido: 'La Pulga', ano: 2012, nascimento: 1987,
    flag: '🇦🇷', raridade: 'mitica', posicao: 'Atacante', clube: 'Barcelona',
    cor: '#FFB800',
    atributos: { gols: 91, titulos: 15, altura: 170, assists: 29, jogos: 69 },
    perguntas: GAT,
    wikiTitle: 'Lionel Messi',
  },
  {
    id: 'cr7-2013', nome: 'Cristiano Ronaldo', apelido: 'CR7', ano: 2013, nascimento: 1985,
    flag: '🇵🇹', raridade: 'mitica', posicao: 'Atacante', clube: 'Real Madrid',
    cor: '#FFB800',
    atributos: { gols: 55, titulos: 10, altura: 187, assists: 13, jogos: 57 },
    perguntas: GTA,
    wikiTitle: 'Cristiano Ronaldo',
  },

  // ── ÉPICA (azul/roxo) ──────────────────────────────────────────
  {
    id: 'romario-1994', nome: 'Romário', apelido: 'Baixinho', ano: 1994, nascimento: 1966,
    flag: '🇧🇷', raridade: 'epica', posicao: 'Atacante', clube: 'Barcelona / Brasil',
    cor: '#7C3AED',
    atributos: { gols: 5, titulos: 8, altura: 169, assists: 2, jogos: 7 },
    perguntas: GT,
    wikiTitle: 'Romário',
  },
  {
    id: 'bebeto-1994', nome: 'Bebeto', apelido: 'Bebeto', ano: 1994, nascimento: 1964,
    flag: '🇧🇷', raridade: 'epica', posicao: 'Atacante', clube: 'Deportivo / Brasil',
    cor: '#7C3AED',
    atributos: { gols: 3, titulos: 5, altura: 176, assists: 5, jogos: 7 },
    perguntas: GTA,
    wikiTitle: 'Bebeto',
  },
  {
    id: 'henry-2003', nome: 'Thierry Henry', apelido: 'Titi', ano: 2003, nascimento: 1977,
    flag: '🇫🇷', raridade: 'epica', posicao: 'Atacante', clube: 'Arsenal',
    cor: '#7C3AED',
    atributos: { gols: 32, titulos: 6, altura: 188, assists: 23, jogos: 52 },
    perguntas: GTA,
    wikiTitle: 'Thierry Henry',
  },
  {
    id: 'totti-2001', nome: 'Francesco Totti', apelido: 'Il Capitano', ano: 2001, nascimento: 1976,
    flag: '🇮🇹', raridade: 'epica', posicao: 'Meia', clube: 'Roma',
    cor: '#7C3AED',
    atributos: { gols: 18, titulos: 3, altura: 180, assists: 10, jogos: 40 },
    perguntas: GP,
    wikiTitle: 'Francesco Totti',
  },
  {
    id: 'kaka-2007', nome: 'Kaká', apelido: 'Kaká', ano: 2007, nascimento: 1982,
    flag: '🇧🇷', raridade: 'epica', posicao: 'Meia', clube: 'AC Milan',
    cor: '#7C3AED',
    atributos: { gols: 16, titulos: 7, altura: 186, assists: 10, jogos: 43 },
    perguntas: GTA,
    wikiTitle: 'Kaká',
  },
  {
    id: 'adriano-2004', nome: 'Adriano', apelido: 'Imperador', ano: 2004, nascimento: 1982,
    flag: '🇧🇷', raridade: 'epica', posicao: 'Atacante', clube: 'Inter',
    cor: '#7C3AED',
    atributos: { gols: 28, titulos: 4, altura: 188, assists: 7, jogos: 48 },
    perguntas: GP,
    wikiTitle: 'Adriano (footballer, born 1982)',
  },
  {
    id: 'ibra-2012', nome: 'Zlatan Ibrahimović', apelido: 'Ibra', ano: 2012, nascimento: 1981,
    flag: '🇸🇪', raridade: 'epica', posicao: 'Atacante', clube: 'PSG',
    cor: '#7C3AED',
    atributos: { gols: 35, titulos: 16, altura: 195, assists: 16, jogos: 51 },
    perguntas: ['gols', 'titulos', 'altura'],
    wikiTitle: 'Zlatan Ibrahimović',
  },
  {
    id: 'van-basten-1988', nome: 'Marco van Basten', apelido: 'Il Cigno', ano: 1988, nascimento: 1964,
    flag: '🇳🇱', raridade: 'epica', posicao: 'Atacante', clube: 'AC Milan / Holanda',
    cor: '#7C3AED',
    atributos: { gols: 9, titulos: 3, altura: 188, assists: 3, jogos: 11 },
    perguntas: GJ,
    wikiTitle: 'Marco van Basten',
  },
  {
    id: 'stoichkov-1994', nome: 'Hristo Stoichkov', apelido: 'Stoichkov', ano: 1994, nascimento: 1966,
    flag: '🇧🇬', raridade: 'epica', posicao: 'Atacante', clube: 'Barcelona / Bulgária',
    cor: '#7C3AED',
    atributos: { gols: 6, titulos: 9, altura: 176, jogos: 7 },
    perguntas: GJ,
    wikiTitle: 'Hristo Stoichkov',
  },
  {
    id: 'rivaldo-2002', nome: 'Rivaldo', apelido: 'Rivaldo', ano: 2002, nascimento: 1972,
    flag: '🇧🇷', raridade: 'epica', posicao: 'Meia', clube: 'Barcelona / Brasil',
    cor: '#7C3AED',
    atributos: { gols: 5, titulos: 9, altura: 181, assists: 4, jogos: 7 },
    perguntas: GT,
    wikiTitle: 'Rivaldo',
  },
  {
    id: 'drogba-2010', nome: 'Didier Drogba', apelido: 'Drogba', ano: 2010, nascimento: 1978,
    flag: '🇨🇮', raridade: 'epica', posicao: 'Atacante', clube: 'Chelsea',
    cor: '#7C3AED',
    atributos: { gols: 29, titulos: 6, altura: 189, assists: 8, jogos: 40 },
    perguntas: GP,
    wikiTitle: 'Didier Drogba',
  },
  {
    id: 'beckham-1999', nome: 'David Beckham', apelido: 'Beckham', ano: 1999, nascimento: 1975,
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', raridade: 'epica', posicao: 'Meia', clube: 'Man. United',
    cor: '#7C3AED',
    atributos: { gols: 6, titulos: 8, altura: 183, assists: 15, jogos: 56 },
    perguntas: TA,
    wikiTitle: 'David Beckham',
  },
  {
    id: 'roberto-carlos-1997', nome: 'Roberto Carlos', apelido: 'Roberto Carlos', ano: 1997, nascimento: 1973,
    flag: '🇧🇷', raridade: 'epica', posicao: 'Lateral', clube: 'Real Madrid',
    cor: '#7C3AED',
    atributos: { gols: 7, titulos: 4, altura: 168, assists: 9, jogos: 54 },
    perguntas: ['gols', 'altura', 'assists'],
    wikiTitle: 'Roberto Carlos',
  },

  // ── COMUM (branca) ──────────────────────────────────────────────
  {
    id: 'zico-1982', nome: 'Zico', apelido: 'Zico', ano: 1982, nascimento: 1953,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Meia', clube: 'Flamengo / Brasil',
    cor: '#16B89A',
    atributos: { gols: 4, titulos: 13, altura: 177, assists: 4, jogos: 5 },
    perguntas: GJ,
    wikiTitle: 'Zico',
  },
  {
    id: 'socrates-1982', nome: 'Sócrates', apelido: 'Doutor', ano: 1982, nascimento: 1954,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Meia', clube: 'Corinthians / Brasil',
    cor: '#16B89A',
    atributos: { gols: 4, titulos: 5, altura: 192, assists: 3, jogos: 5 },
    perguntas: ['gols', 'altura'],
    wikiTitle: 'Sócrates (footballer)',
  },
  {
    id: 'falcao-1982', nome: 'Paulo Roberto Falcão', apelido: 'Falcão', ano: 1982, nascimento: 1953,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Meia', clube: 'Roma / Brasil',
    cor: '#16B89A',
    atributos: { gols: 2, titulos: 4, altura: 178, assists: 5, jogos: 5 },
    perguntas: GP,
    wikiTitle: 'Paulo Roberto Falcão',
  },
  {
    id: 'jardel-2001', nome: 'Mário Jardel', apelido: 'Jardel', ano: 2001, nascimento: 1973,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Porto / Galatasaray',
    cor: '#16B89A',
    atributos: { gols: 42, titulos: 3, altura: 190, jogos: 51 },
    perguntas: GP,
    wikiTitle: 'Mário Jardel',
  },
  {
    id: 'edmundo-1997', nome: 'Edmundo', apelido: 'Animal', ano: 1997, nascimento: 1971,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Vasco',
    cor: '#16B89A',
    atributos: { gols: 29, titulos: 3, altura: 180, jogos: 48 },
    perguntas: GP,
    wikiTitle: 'Edmundo (footballer)',
  },
  {
    id: 'robinho-2005', nome: 'Robinho', apelido: 'Robinho', ano: 2005, nascimento: 1984,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Real Madrid',
    cor: '#16B89A',
    atributos: { gols: 14, titulos: 2, altura: 172, assists: 10, jogos: 47 },
    perguntas: GP,
    wikiTitle: 'Robinho',
  },
  {
    id: 'denilson-1998', nome: 'Denílson', apelido: 'Denílson', ano: 1998, nascimento: 1977,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Meia', clube: 'Betis / Brasil',
    cor: '#16B89A',
    atributos: { gols: 1, titulos: 1, altura: 173, jogos: 6 },
    perguntas: ['titulos', 'jogos'],
    wikiTitle: 'Denílson (Brazilian footballer)',
  },
  {
    id: 'cafu-2002', nome: 'Marcos Cafu', apelido: 'Cafu', ano: 2002, nascimento: 1970,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Lateral', clube: 'Roma / Brasil',
    cor: '#16B89A',
    atributos: { gols: 2, titulos: 3, altura: 176, assists: 6, jogos: 54 },
    perguntas: ['titulos', 'jogos'],
    wikiTitle: 'Cafu',
  },
  {
    id: 'roberto-baggio-1994', nome: 'Roberto Baggio', apelido: 'Il Codino', ano: 1994, nascimento: 1967,
    flag: '🇮🇹', raridade: 'comum', posicao: 'Meia', clube: 'Juventus / Itália',
    cor: '#16B89A',
    atributos: { gols: 5, titulos: 5, altura: 174, assists: 2, jogos: 7 },
    perguntas: GJ,
    wikiTitle: 'Roberto Baggio',
  },

  // ── MÍTICA — era clássica ──────────────────────────────────────
  {
    id: 'garrincha-1962', nome: 'Garrincha', apelido: 'A Alegria do Povo', ano: 1962, nascimento: 1933,
    flag: '🇧🇷', raridade: 'mitica', posicao: 'Ponta Direita', clube: 'Botafogo / Brasil',
    cor: '#FFB800',
    atributos: { gols: 4, titulos: 2, altura: 169, assists: 5, jogos: 6 },
    perguntas: GJ,
    wikiTitle: 'Garrincha',
  },
  {
    id: 'cruyff-1974', nome: 'Johan Cruyff', apelido: 'De Totale Voetballer', ano: 1974, nascimento: 1947,
    flag: '🇳🇱', raridade: 'mitica', posicao: 'Atacante', clube: 'Ajax / Holanda',
    cor: '#FFB800',
    atributos: { gols: 3, titulos: 9, altura: 180, jogos: 7 },
    perguntas: ['gols', 'titulos', 'altura'],
    wikiTitle: 'Johan Cruyff',
  },
  {
    id: 'beckenbauer-1974', nome: 'Franz Beckenbauer', apelido: 'Der Kaiser', ano: 1974, nascimento: 1945,
    flag: '🇩🇪', raridade: 'mitica', posicao: 'Líbero', clube: 'Bayern / Alemanha',
    cor: '#FFB800',
    atributos: { gols: 4, titulos: 9, altura: 181, jogos: 7 },
    perguntas: TAJ,
    wikiTitle: 'Franz Beckenbauer',
  },
  {
    id: 'eusebio-1966', nome: 'Eusébio', apelido: 'A Pantera Negra', ano: 1966, nascimento: 1942,
    flag: '🇵🇹', raridade: 'mitica', posicao: 'Atacante', clube: 'Benfica / Portugal',
    cor: '#FFB800',
    atributos: { gols: 9, titulos: 5, altura: 175, jogos: 6 },
    perguntas: GJT,
    wikiTitle: 'Eusébio',
  },
  {
    id: 'platini-1984', nome: 'Michel Platini', apelido: 'Le Roi Michel', ano: 1984, nascimento: 1955,
    flag: '🇫🇷', raridade: 'mitica', posicao: 'Meia', clube: 'Juventus / França',
    cor: '#FFB800',
    atributos: { gols: 20, titulos: 11, altura: 179, assists: 11, jogos: 46 },
    perguntas: GTA,
    wikiTitle: 'Michel Platini',
  },
  {
    id: 'best-1968', nome: 'George Best', apelido: 'O Quinto Beatle', ano: 1968, nascimento: 1946,
    flag: '🏴󠁧󠁢󠁮󠁩󠁲󠁿', raridade: 'mitica', posicao: 'Atacante', clube: 'Man. United / Irlanda do N.',
    cor: '#FFB800',
    atributos: { gols: 28, titulos: 4, altura: 175, jogos: 41 },
    perguntas: GP,
    wikiTitle: 'George Best',
  },
  {
    id: 'jairzinho-1970', nome: 'Jairzinho', apelido: 'O Furacão da Copa', ano: 1970, nascimento: 1944,
    flag: '🇧🇷', raridade: 'mitica', posicao: 'Ponta Direita', clube: 'Botafogo / Brasil',
    cor: '#FFB800',
    atributos: { gols: 7, titulos: 2, altura: 180, jogos: 6 },
    perguntas: GJ,
    wikiTitle: 'Jairzinho',
  },

  // ── ÉPICA — grandes estrelas ───────────────────────────────────
  {
    id: 'neymar-2015', nome: 'Neymar Jr.', apelido: 'Ney', ano: 2015, nascimento: 1992,
    flag: '🇧🇷', raridade: 'epica', posicao: 'Atacante', clube: 'Barcelona / Brasil',
    cor: '#7C3AED',
    atributos: { gols: 22, titulos: 16, altura: 175, assists: 16, jogos: 51 },
    perguntas: GTA,
    wikiTitle: 'Neymar',
  },
  {
    id: 'mbappe-2022', nome: 'Kylian Mbappé', apelido: 'K.M.10', ano: 2022, nascimento: 2000,
    flag: '🇫🇷', raridade: 'epica', posicao: 'Atacante', clube: 'PSG / França',
    cor: '#7C3AED',
    atributos: { gols: 8, titulos: 6, altura: 178, jogos: 7 },
    perguntas: GJT,
    wikiTitle: 'Kylian Mbappé',
  },
  {
    id: 'xavi-2011', nome: 'Xavi Hernández', apelido: 'Xavi', ano: 2011, nascimento: 1980,
    flag: '🇪🇸', raridade: 'epica', posicao: 'Meia', clube: 'Barcelona / Espanha',
    cor: '#7C3AED',
    atributos: { gols: 5, titulos: 15, altura: 170, assists: 18, jogos: 55 },
    perguntas: TA,
    wikiTitle: 'Xavi Hernández',
  },
  {
    id: 'iniesta-2010', nome: 'Andrés Iniesta', apelido: 'El Ilusionista', ano: 2010, nascimento: 1984,
    flag: '🇪🇸', raridade: 'epica', posicao: 'Meia', clube: 'Barcelona / Espanha',
    cor: '#7C3AED',
    atributos: { gols: 8, titulos: 13, altura: 171, assists: 12, jogos: 49 },
    perguntas: TA,
    wikiTitle: 'Andrés Iniesta',
  },
  {
    id: 'gullit-1988', nome: 'Ruud Gullit', apelido: 'Tulipa Negra', ano: 1988, nascimento: 1962,
    flag: '🇳🇱', raridade: 'epica', posicao: 'Atacante', clube: 'AC Milan / Holanda',
    cor: '#7C3AED',
    atributos: { gols: 11, titulos: 8, altura: 188, assists: 9, jogos: 34 },
    perguntas: ['gols', 'titulos', 'altura'],
    wikiTitle: 'Ruud Gullit',
  },
  {
    id: 'figo-2001', nome: 'Luís Figo', apelido: 'O Boa', ano: 2001, nascimento: 1972,
    flag: '🇵🇹', raridade: 'epica', posicao: 'Meia', clube: 'Real Madrid / Portugal',
    cor: '#7C3AED',
    atributos: { gols: 16, titulos: 9, altura: 181, assists: 13, jogos: 44 },
    perguntas: GTA,
    wikiTitle: 'Luís Figo',
  },
  {
    id: 'pirlo-2012', nome: 'Andrea Pirlo', apelido: 'Il Professore', ano: 2012, nascimento: 1979,
    flag: '🇮🇹', raridade: 'epica', posicao: 'Meia', clube: 'Juventus / Itália',
    cor: '#7C3AED',
    atributos: { gols: 8, titulos: 14, altura: 177, assists: 16, jogos: 41 },
    perguntas: ['titulos', 'assists', 'jogos'],
    wikiTitle: 'Andrea Pirlo',
  },
  {
    id: 'shevchenko-2004', nome: 'Andriy Shevchenko', apelido: 'Sheva', ano: 2004, nascimento: 1976,
    flag: '🇺🇦', raridade: 'epica', posicao: 'Atacante', clube: 'AC Milan / Ucrânia',
    cor: '#7C3AED',
    atributos: { gols: 24, titulos: 8, altura: 183, assists: 9, jogos: 46 },
    perguntas: GJ,
    wikiTitle: 'Andriy Shevchenko',
  },
  {
    id: 'r9-2002', nome: 'Ronaldo Nazário', apelido: 'O Fenômeno', ano: 2002, nascimento: 1976,
    flag: '🇧🇷', raridade: 'epica', posicao: 'Atacante', clube: 'Real Madrid / Brasil',
    cor: '#7C3AED',
    atributos: { gols: 8, titulos: 6, altura: 183, jogos: 7 },
    perguntas: GJ,
    wikiTitle: 'Ronaldo (Brazilian footballer)',
  },
  {
    id: 'batistuta-1998', nome: 'Gabriel Batistuta', apelido: 'Batigol', ano: 1998, nascimento: 1969,
    flag: '🇦🇷', raridade: 'epica', posicao: 'Atacante', clube: 'Fiorentina / Argentina',
    cor: '#7C3AED',
    atributos: { gols: 22, titulos: 4, altura: 184, jogos: 42 },
    perguntas: GP,
    wikiTitle: 'Gabriel Batistuta',
  },
  {
    id: 'riquelme-2004', nome: 'Juan Román Riquelme', apelido: 'El Último 10', ano: 2004, nascimento: 1978,
    flag: '🇦🇷', raridade: 'epica', posicao: 'Meia', clube: 'Villarreal / Argentina',
    cor: '#7C3AED',
    atributos: { gols: 4, titulos: 5, altura: 181, assists: 14, jogos: 34 },
    perguntas: TA,
    wikiTitle: 'Juan Román Riquelme',
  },
  {
    id: 'maldini-1995', nome: 'Paolo Maldini', apelido: 'Il Capitano', ano: 1995, nascimento: 1968,
    flag: '🇮🇹', raridade: 'epica', posicao: 'Zagueiro', clube: 'AC Milan / Itália',
    cor: '#7C3AED',
    atributos: { gols: 1, titulos: 12, altura: 186, jogos: 38 },
    perguntas: TAJ,
    wikiTitle: 'Paolo Maldini',
  },
  {
    id: 'raul-2000', nome: 'Raúl González', apelido: 'El Ángel', ano: 2000, nascimento: 1977,
    flag: '🇪🇸', raridade: 'epica', posicao: 'Atacante', clube: 'Real Madrid / Espanha',
    cor: '#7C3AED',
    atributos: { gols: 16, titulos: 10, altura: 180, assists: 12, jogos: 44 },
    perguntas: GTA,
    wikiTitle: 'Raúl González Blanco',
  },
  {
    id: 'bergkamp-1998', nome: 'Dennis Bergkamp', apelido: 'Non-Flying Dutchman', ano: 1998, nascimento: 1969,
    flag: '🇳🇱', raridade: 'epica', posicao: 'Atacante', clube: 'Arsenal / Holanda',
    cor: '#7C3AED',
    atributos: { gols: 16, titulos: 9, altura: 188, assists: 8, jogos: 40 },
    perguntas: GJ,
    wikiTitle: 'Dennis Bergkamp',
  },
  {
    id: 'robben-2014', nome: 'Arjen Robben', apelido: 'O Homem da Curva', ano: 2014, nascimento: 1984,
    flag: '🇳🇱', raridade: 'epica', posicao: 'Atacante', clube: 'Bayern / Holanda',
    cor: '#7C3AED',
    atributos: { gols: 21, titulos: 11, altura: 181, assists: 8, jogos: 35 },
    perguntas: GTA,
    wikiTitle: 'Arjen Robben',
  },
  {
    id: 'matthaus-1990', nome: 'Lothar Matthäus', apelido: 'Mäuse', ano: 1990, nascimento: 1961,
    flag: '🇩🇪', raridade: 'epica', posicao: 'Meia', clube: 'Inter / Alemanha',
    cor: '#7C3AED',
    atributos: { gols: 4, titulos: 6, altura: 181, jogos: 7 },
    perguntas: GJT,
    wikiTitle: 'Lothar Matthäus',
  },
  {
    id: 'etoo-2006', nome: "Samuel Eto'o", apelido: "Le Lion Indomptable", ano: 2006, nascimento: 1981,
    flag: '🇨🇲', raridade: 'epica', posicao: 'Atacante', clube: 'Barcelona / Camarões',
    cor: '#7C3AED',
    atributos: { gols: 26, titulos: 8, altura: 180, assists: 6, jogos: 48 },
    perguntas: GJ,
    wikiTitle: "Samuel Eto'o",
  },
  {
    id: 'torres-2008', nome: 'Fernando Torres', apelido: 'El Niño', ano: 2008, nascimento: 1984,
    flag: '🇪🇸', raridade: 'epica', posicao: 'Atacante', clube: 'Liverpool / Espanha',
    cor: '#7C3AED',
    atributos: { gols: 33, titulos: 3, altura: 185, jogos: 46 },
    perguntas: GP,
    wikiTitle: 'Fernando Torres',
  },
  {
    id: 'tevez-2006', nome: 'Carlos Tevez', apelido: 'Apache', ano: 2006, nascimento: 1984,
    flag: '🇦🇷', raridade: 'epica', posicao: 'Atacante', clube: 'Corinthians / Argentina',
    cor: '#7C3AED',
    atributos: { gols: 22, titulos: 3, altura: 173, jogos: 38 },
    perguntas: GP,
    wikiTitle: 'Carlos Tevez',
  },
  {
    id: 'modric-2018', nome: 'Luka Modrić', apelido: 'El Mago', ano: 2018, nascimento: 1985,
    flag: '🇭🇷', raridade: 'epica', posicao: 'Meia', clube: 'Real Madrid / Croácia',
    cor: '#7C3AED',
    atributos: { gols: 6, titulos: 15, altura: 172, assists: 14, jogos: 36 },
    perguntas: TA,
    wikiTitle: 'Luka Modrić',
  },
  {
    id: 'lewandowski-2021', nome: 'Robert Lewandowski', apelido: 'Lewy', ano: 2021, nascimento: 1988,
    flag: '🇵🇱', raridade: 'epica', posicao: 'Atacante', clube: 'Bayern / Polônia',
    cor: '#7C3AED',
    atributos: { gols: 41, titulos: 10, altura: 184, assists: 8, jogos: 29 },
    perguntas: GJT,
    wikiTitle: 'Robert Lewandowski',
  },
  {
    id: 'vieira-2001', nome: 'Patrick Vieira', apelido: 'Le Capitaine', ano: 2001, nascimento: 1976,
    flag: '🇫🇷', raridade: 'epica', posicao: 'Meia', clube: 'Arsenal / França',
    cor: '#7C3AED',
    atributos: { gols: 5, titulos: 8, altura: 193, jogos: 42 },
    perguntas: ['titulos', 'altura', 'jogos'],
    wikiTitle: 'Patrick Vieira',
  },
  {
    id: 'aguero-2015', nome: 'Sergio Agüero', apelido: 'Kun', ano: 2015, nascimento: 1988,
    flag: '🇦🇷', raridade: 'epica', posicao: 'Atacante', clube: 'Man. City / Argentina',
    cor: '#7C3AED',
    atributos: { gols: 26, titulos: 9, altura: 173, assists: 9, jogos: 33 },
    perguntas: GJ,
    wikiTitle: 'Sergio Agüero',
  },
  {
    id: 'rooney-2005', nome: 'Wayne Rooney', apelido: 'Shrek', ano: 2005, nascimento: 1985,
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', raridade: 'epica', posicao: 'Atacante', clube: 'Man. United / Inglaterra',
    cor: '#7C3AED',
    atributos: { gols: 17, titulos: 2, altura: 176, assists: 7, jogos: 43 },
    perguntas: GP,
    wikiTitle: 'Wayne Rooney',
  },
  {
    id: 'di-maria-2014', nome: 'Ángel Di María', apelido: 'El Fideo', ano: 2014, nascimento: 1988,
    flag: '🇦🇷', raridade: 'epica', posicao: 'Meia', clube: 'Real Madrid / Argentina',
    cor: '#7C3AED',
    atributos: { gols: 13, titulos: 8, altura: 178, assists: 17, jogos: 44 },
    perguntas: TA,
    wikiTitle: 'Ángel Di María',
  },
  {
    id: 'puskas-1960', nome: 'Ferenc Puskás', apelido: 'O Canhão Galáctico', ano: 1960, nascimento: 1927,
    flag: '🇭🇺', raridade: 'epica', posicao: 'Atacante', clube: 'Real Madrid / Hungria',
    cor: '#7C3AED',
    atributos: { gols: 26, titulos: 8, altura: 172, jogos: 39 },
    perguntas: GT,
    wikiTitle: 'Ferenc Puskás',
  },
  {
    id: 'gerd-muller-1972', nome: 'Gerd Müller', apelido: 'Bomba', ano: 1972, nascimento: 1945,
    flag: '🇩🇪', raridade: 'epica', posicao: 'Atacante', clube: 'Bayern / Alemanha',
    cor: '#7C3AED',
    atributos: { gols: 40, titulos: 7, altura: 176, jogos: 34 },
    perguntas: GP,
    wikiTitle: 'Gerd Müller',
  },

  // ── COMUM — memórias & quase-lendas ───────────────────────────
  {
    id: 'vampeta-1999', nome: 'Vampeta', apelido: 'Vampeta', ano: 1999, nascimento: 1974,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Meia', clube: 'Galatasaray / Brasil',
    cor: '#16B89A',
    atributos: { gols: 5, titulos: 4, altura: 176, jogos: 38 },
    perguntas: GP,
    wikiTitle: 'Vampeta',
  },
  {
    id: 'dembele-2023', nome: 'Ousmane Dembélé', apelido: 'Dembélé', ano: 2023, nascimento: 1997,
    flag: '🇫🇷', raridade: 'epica', posicao: 'Atacante', clube: 'Barcelona / França',
    cor: '#7C3AED',
    atributos: { gols: 16, titulos: 2, altura: 178, assists: 11, jogos: 31 },
    perguntas: GTA,
    wikiTitle: 'Ousmane Dembélé',
  },
  {
    id: 'dani-alves-2011', nome: 'Dani Alves', apelido: 'Dani Alves', ano: 2011, nascimento: 1983,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Lateral', clube: 'Barcelona / Brasil',
    cor: '#16B89A',
    atributos: { gols: 7, titulos: 15, altura: 171, assists: 16, jogos: 46 },
    perguntas: TA,
    wikiTitle: 'Dani Alves',
  },
  {
    id: 'thiago-silva-2013', nome: 'Thiago Silva', apelido: 'O Monstro', ano: 2013, nascimento: 1984,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Zagueiro', clube: 'PSG / Brasil',
    cor: '#16B89A',
    atributos: { gols: 3, titulos: 9, altura: 183, jogos: 37 },
    perguntas: TAJ,
    wikiTitle: 'Thiago Silva',
  },
  {
    id: 'oscar-2012', nome: 'Oscar', apelido: 'Oscar', ano: 2012, nascimento: 1991,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Meia', clube: 'Chelsea / Brasil',
    cor: '#16B89A',
    atributos: { gols: 13, titulos: 3, altura: 179, assists: 8, jogos: 47 },
    perguntas: GJ,
    wikiTitle: 'Oscar (footballer, born 1991)',
  },
  {
    id: 'hulk-2012', nome: 'Hulk', apelido: 'Hulk', ano: 2012, nascimento: 1986,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Zenit / Brasil',
    cor: '#16B89A',
    atributos: { gols: 14, titulos: 3, altura: 181, jogos: 40 },
    perguntas: GP,
    wikiTitle: 'Hulk (footballer)',
  },
  {
    id: 'fred-2014', nome: 'Fred', apelido: 'Fred', ano: 2014, nascimento: 1983,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Fluminense / Brasil',
    cor: '#16B89A',
    atributos: { gols: 1, titulos: 3, altura: 189, jogos: 5 },
    perguntas: GP,
    wikiTitle: 'Fred (footballer, born 1983)',
  },
  {
    id: 'gilberto-silva-2002', nome: 'Gilberto Silva', apelido: 'G. Silva', ano: 2002, nascimento: 1976,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Meia', clube: 'Atlético MG / Brasil',
    cor: '#16B89A',
    atributos: { gols: 1, titulos: 3, altura: 188, jogos: 7 },
    perguntas: TAJ,
    wikiTitle: 'Gilberto Silva',
  },
  {
    id: 'emerson-2002', nome: 'Emerson', apelido: 'Emerson', ano: 2002, nascimento: 1976,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Meia', clube: 'Roma / Brasil',
    cor: '#16B89A',
    atributos: { gols: 3, titulos: 4, altura: 180, jogos: 38 },
    perguntas: ['titulos', 'jogos'],
    wikiTitle: 'Emerson Ferreira da Rosa',
  },
  {
    id: 'careca-1990', nome: 'Careca', apelido: 'Careca', ano: 1990, nascimento: 1960,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Napoli / Brasil',
    cor: '#16B89A',
    atributos: { gols: 16, titulos: 5, altura: 175, jogos: 38 },
    perguntas: GP,
    wikiTitle: 'Careca',
  },
  {
    id: 'muller-br-1989', nome: 'Müller', apelido: 'Müller', ano: 1989, nascimento: 1966,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Atacante', clube: 'São Paulo / Brasil',
    cor: '#16B89A',
    atributos: { gols: 18, titulos: 4, altura: 170, jogos: 28 },
    perguntas: GP,
    wikiTitle: 'Müller (footballer, born 1966)',
  },
  {
    id: 'dunga-1994', nome: 'Dunga', apelido: 'Dunga', ano: 1994, nascimento: 1963,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Meia', clube: 'Stuttgart / Brasil',
    cor: '#16B89A',
    atributos: { gols: 3, titulos: 5, altura: 176, jogos: 7 },
    perguntas: ['titulos', 'jogos'],
    wikiTitle: 'Dunga',
  },
  {
    id: 'aldair-1994', nome: 'Aldair', apelido: 'Aldair', ano: 1994, nascimento: 1963,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Zagueiro', clube: 'Roma / Brasil',
    cor: '#16B89A',
    atributos: { gols: 2, titulos: 3, altura: 184, jogos: 7 },
    perguntas: TAJ,
    wikiTitle: 'Aldair',
  },
  {
    id: 'junior-1982', nome: 'Júnior', apelido: 'Júnior', ano: 1982, nascimento: 1954,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Lateral', clube: 'Flamengo / Brasil',
    cor: '#16B89A',
    atributos: { gols: 2, titulos: 6, altura: 178, assists: 5, jogos: 5 },
    perguntas: GJ,
    wikiTitle: 'Júnior (footballer, born 1954)',
  },
  {
    id: 'renato-gaucho-1989', nome: 'Renato Gaúcho', apelido: 'Renato', ano: 1989, nascimento: 1962,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Fluminense / Brasil',
    cor: '#16B89A',
    atributos: { gols: 15, titulos: 4, altura: 181, jogos: 35 },
    perguntas: GP,
    wikiTitle: 'Renato Gaúcho',
  },
  {
    id: 'buffon-2006', nome: 'Gianluigi Buffon', apelido: 'Gigi', ano: 2006, nascimento: 1978,
    flag: '🇮🇹', raridade: 'comum', posicao: 'Goleiro', clube: 'Juventus / Itália',
    cor: '#16B89A',
    atributos: { titulos: 9, altura: 191, jogos: 7 },
    perguntas: TAJ,
    wikiTitle: 'Gianluigi Buffon',
  },
  {
    id: 'gattuso-2006', nome: 'Gennaro Gattuso', apelido: 'Rino', ano: 2006, nascimento: 1978,
    flag: '🇮🇹', raridade: 'comum', posicao: 'Meia', clube: 'AC Milan / Itália',
    cor: '#16B89A',
    atributos: { gols: 2, titulos: 8, altura: 177, jogos: 7 },
    perguntas: TAJ,
    wikiTitle: 'Gennaro Gattuso',
  },
  {
    id: 'inzaghi-2003', nome: 'Filippo Inzaghi', apelido: 'Pippo', ano: 2003, nascimento: 1973,
    flag: '🇮🇹', raridade: 'comum', posicao: 'Atacante', clube: 'AC Milan / Itália',
    cor: '#16B89A',
    atributos: { gols: 14, titulos: 8, altura: 181, jogos: 39 },
    perguntas: GP,
    wikiTitle: 'Filippo Inzaghi',
  },
  {
    id: 'del-piero-1997', nome: 'Alessandro Del Piero', apelido: 'Alex', ano: 1997, nascimento: 1974,
    flag: '🇮🇹', raridade: 'comum', posicao: 'Atacante', clube: 'Juventus / Itália',
    cor: '#16B89A',
    atributos: { gols: 23, titulos: 7, altura: 174, assists: 8, jogos: 44 },
    perguntas: GJ,
    wikiTitle: 'Alessandro Del Piero',
  },
  {
    id: 'crespo-2002', nome: 'Hernán Crespo', apelido: 'Valdanito', ano: 2002, nascimento: 1975,
    flag: '🇦🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Lazio / Argentina',
    cor: '#16B89A',
    atributos: { gols: 23, titulos: 4, altura: 186, jogos: 38 },
    perguntas: GP,
    wikiTitle: 'Hernán Crespo',
  },
  {
    id: 'vieri-2002', nome: 'Christian Vieri', apelido: 'Bobo', ano: 2002, nascimento: 1973,
    flag: '🇮🇹', raridade: 'comum', posicao: 'Atacante', clube: 'Inter / Itália',
    cor: '#16B89A',
    atributos: { gols: 22, titulos: 4, altura: 188, jogos: 39 },
    perguntas: GP,
    wikiTitle: 'Christian Vieri',
  },
  {
    id: 'saviola-2002', nome: 'Javier Saviola', apelido: 'El Conejo', ano: 2002, nascimento: 1981,
    flag: '🇦🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Barcelona / Argentina',
    cor: '#16B89A',
    atributos: { gols: 17, titulos: 3, altura: 168, jogos: 34 },
    perguntas: ['gols', 'altura'],
    wikiTitle: 'Javier Saviola',
  },
  {
    id: 'ballack-2004', nome: 'Michael Ballack', apelido: 'Das Tier', ano: 2004, nascimento: 1976,
    flag: '🇩🇪', raridade: 'comum', posicao: 'Meia', clube: 'Bayern / Alemanha',
    cor: '#16B89A',
    atributos: { gols: 13, titulos: 8, altura: 188, assists: 10, jogos: 32 },
    perguntas: GTA,
    wikiTitle: 'Michael Ballack',
  },
  {
    id: 'klose-2014', nome: 'Miroslav Klose', apelido: 'Klose', ano: 2014, nascimento: 1978,
    flag: '🇩🇪', raridade: 'comum', posicao: 'Atacante', clube: 'Lazio / Alemanha',
    cor: '#16B89A',
    atributos: { gols: 3, titulos: 5, altura: 183, jogos: 7 },
    perguntas: GJ,
    wikiTitle: 'Miroslav Klose',
  },
  {
    id: 'nedved-2003', nome: 'Pavel Nedvěd', apelido: 'Fúria Checa', ano: 2003, nascimento: 1972,
    flag: '🇨🇿', raridade: 'comum', posicao: 'Meia', clube: 'Juventus / Rep. Checa',
    cor: '#16B89A',
    atributos: { gols: 9, titulos: 9, altura: 177, assists: 11, jogos: 47 },
    perguntas: GTA,
    wikiTitle: 'Pavel Nedvěd',
  },
  {
    id: 'keane-1999', nome: 'Roy Keane', apelido: 'Keane', ano: 1999, nascimento: 1971,
    flag: '🇮🇪', raridade: 'comum', posicao: 'Meia', clube: 'Man. United / Irlanda',
    cor: '#16B89A',
    atributos: { gols: 5, titulos: 9, altura: 178, jogos: 38 },
    perguntas: ['titulos', 'jogos'],
    wikiTitle: 'Roy Keane',
  },
  {
    id: 'cantona-1996', nome: 'Eric Cantona', apelido: 'Le Roi', ano: 1996, nascimento: 1966,
    flag: '🇫🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Man. United / França',
    cor: '#16B89A',
    atributos: { gols: 19, titulos: 7, altura: 188, jogos: 38 },
    perguntas: GT,
    wikiTitle: 'Eric Cantona',
  },
  {
    id: 'vinicius-2022', nome: 'Vinícius Jr.', apelido: 'Vini Jr.', ano: 2022, nascimento: 2000,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Real Madrid / Brasil',
    cor: '#16B89A',
    atributos: { gols: 22, titulos: 5, altura: 176, assists: 12, jogos: 52 },
    perguntas: GTA,
    wikiTitle: 'Vinícius Júnior',
  },
  {
    id: 'haaland-2023', nome: 'Erling Haaland', apelido: 'O Exterminador', ano: 2023, nascimento: 2000,
    flag: '🇳🇴', raridade: 'epica', posicao: 'Atacante', clube: 'Man. City / Noruega',
    cor: '#7C3AED',
    atributos: { gols: 36, titulos: 4, altura: 194, assists: 8, jogos: 35 },
    perguntas: ['gols', 'jogos', 'altura'],
    wikiTitle: 'Erling Haaland',
  },
  {
    id: 'pedri-2021', nome: 'Pedri', apelido: 'Pedri', ano: 2021, nascimento: 2002,
    flag: '🇪🇸', raridade: 'comum', posicao: 'Meia', clube: 'Barcelona / Espanha',
    cor: '#16B89A',
    atributos: { gols: 4, titulos: 2, altura: 174, assists: 7, jogos: 52 },
    perguntas: ['jogos', 'assists', 'titulos'],
    wikiTitle: 'Pedri',
  },
  {
    id: 'bellingham-2024', nome: 'Jude Bellingham', apelido: 'Bellingham', ano: 2024, nascimento: 2003,
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', raridade: 'comum', posicao: 'Meia', clube: 'Real Madrid / Inglaterra',
    cor: '#16B89A',
    atributos: { gols: 23, titulos: 3, altura: 186, assists: 12, jogos: 42 },
    perguntas: GTA,
    wikiTitle: 'Jude Bellingham',
  },
  {
    id: 'di-stefano-1960', nome: 'Alfredo Di Stéfano', apelido: 'La Saeta Rubia', ano: 1960, nascimento: 1926,
    flag: '🇦🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Real Madrid / Argentina',
    cor: '#16B89A',
    atributos: { gols: 25, titulos: 10, altura: 178, jogos: 39 },
    perguntas: GT,
    wikiTitle: 'Alfredo Di Stéfano',
  },
  {
    id: 'kempes-1978', nome: 'Mario Kempes', apelido: 'El Matador', ano: 1978, nascimento: 1954,
    flag: '🇦🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Valencia / Argentina',
    cor: '#16B89A',
    atributos: { gols: 6, titulos: 2, altura: 178, jogos: 7 },
    perguntas: GJ,
    wikiTitle: 'Mario Kempes',
  },
  {
    id: 'rivelino-1970', nome: 'Rivellino', apelido: 'Rivellino', ano: 1970, nascimento: 1946,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Meia', clube: 'Corinthians / Brasil',
    cor: '#16B89A',
    atributos: { gols: 3, titulos: 2, altura: 175, assists: 4, jogos: 6 },
    perguntas: GJ,
    wikiTitle: 'Rivellino',
  },
  {
    id: 'tostao-1970', nome: 'Tostão', apelido: 'O Menino de Ouro', ano: 1970, nascimento: 1947,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Cruzeiro / Brasil',
    cor: '#16B89A',
    atributos: { gols: 2, titulos: 2, altura: 168, assists: 5, jogos: 6 },
    perguntas: ['gols', 'assists', 'jogos'],
    wikiTitle: 'Tostão',
  },
  {
    id: 'didi-1958', nome: 'Didi', apelido: 'O Príncipe Etíope', ano: 1958, nascimento: 1928,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Meia', clube: 'Botafogo / Brasil',
    cor: '#16B89A',
    atributos: { gols: 3, titulos: 2, altura: 176, assists: 4, jogos: 6 },
    perguntas: GJ,
    wikiTitle: 'Didi (footballer)',
  },
]

export function getCard(id: string): HistCardData | undefined {
  return HIST_CARDS.find(c => c.id === id)
}

export function getRaridadeLabel(r: HistCardData['raridade']): string {
  return r === 'mitica' ? 'MÍTICA' : r === 'epica' ? 'ÉPICA' : 'COMUM'
}

export function getRaridadeColor(r: HistCardData['raridade']): { bg: string; text: string; glow: string } {
  if (r === 'mitica') return { bg: 'linear-gradient(135deg, #78350f, #b45309, #d97706, #fbbf24)', text: '#fef3c7', glow: '#f59e0b' }
  if (r === 'epica') return { bg: 'linear-gradient(135deg, #1e1b4b, #4338ca, #7c3aed)', text: '#ede9fe', glow: '#818cf8' }
  return { bg: '#fff', text: '#000', glow: 'transparent' }
}

export const QUESTION_LABELS: Record<string, (ano: number) => string> = {
  gols:    (ano) => `Quantos gols marcou em ${ano}?`,
  titulos: (ano) => `Quantos títulos tinha conquistado até ${ano}?`,
  altura:  (_)   => 'Qual era sua altura em cm?',
  assists: (ano) => `Quantas assistências deu em ${ano}?`,
  jogos:   (ano) => `Quantos jogos fez em ${ano}?`,
}
