import type { HistCardData } from './types'


export const HIST_CARDS: HistCardData[] = [
  // ── MÍTICA (ouro) ──────────────────────────────────────────────
  {
    id: 'pele-1970', nome: 'Pelé', apelido: 'O Rei', ano: 1970, nascimento: 1940,
    flag: '🇧🇷', raridade: 'mitica', posicao: 'Atacante', clube: 'Santos / Brasil',
    cor: '#FFB800',
    atributos: { copa_gols: 12, copa_jogos: 14, gols_carreira: 767, copas: 4, titulos: 26, selecao_gols: 77, selecao_jogos: 92, altura: 173 },
    perguntas: ['copa_gols', 'gols_carreira', 'copas'],
    wikiTitle: 'Pelé',
  },
  {
    id: 'maradona-1986', nome: 'Diego Maradona', apelido: 'El Pibe de Oro', ano: 1986, nascimento: 1960,
    flag: '🇦🇷', raridade: 'mitica', posicao: 'Meia', clube: 'Napoli / Argentina',
    cor: '#FFB800',
    atributos: { copa_gols: 8, copa_jogos: 21, gols_carreira: 312, copas: 4, titulos: 14, ballon_dor: 1, selecao_gols: 34, selecao_jogos: 91, altura: 165 },
    perguntas: ['copa_gols', 'copa_jogos', 'gols_carreira'],
    wikiTitle: 'Diego Maradona',
  },
  {
    id: 'r9-1998', nome: 'Ronaldo Nazário', apelido: 'O Fenômeno', ano: 1998, nascimento: 1976,
    flag: '🇧🇷', raridade: 'mitica', posicao: 'Atacante', clube: 'Inter / Brasil',
    cor: '#FFB800',
    atributos: { copa_gols: 15, copa_jogos: 19, gols_carreira: 415, copas: 3, titulos: 14, ballon_dor: 2, selecao_gols: 62, selecao_jogos: 98, altura: 183 },
    perguntas: ['copa_gols', 'ballon_dor', 'gols_carreira'],
    wikiTitle: 'Ronaldo (Brazilian footballer)',
  },
  {
    id: 'zidane-1998', nome: 'Zinedine Zidane', apelido: 'Zizou', ano: 1998, nascimento: 1972,
    flag: '🇫🇷', raridade: 'mitica', posicao: 'Meia', clube: 'Juventus / França',
    cor: '#FFB800',
    atributos: { copa_jogos: 17, gols_carreira: 156, copas: 3, titulos: 14, ballon_dor: 3, cl_titulos: 1, selecao_gols: 31, selecao_jogos: 108, altura: 185 },
    perguntas: ['ballon_dor', 'copa_jogos', 'cl_titulos'],
    wikiTitle: 'Zinedine Zidane',
  },
  {
    id: 'ronaldinho-2005', nome: 'Ronaldinho', apelido: 'Dinho', ano: 2005, nascimento: 1980,
    flag: '🇧🇷', raridade: 'mitica', posicao: 'Meia', clube: 'Barcelona',
    cor: '#FFB800',
    atributos: { copa_gols: 4, copa_jogos: 13, gols_carreira: 297, copas: 3, titulos: 26, ballon_dor: 2, cl_titulos: 1, selecao_gols: 33, selecao_jogos: 97, altura: 180 },
    perguntas: ['ballon_dor', 'gols_carreira', 'cl_titulos'],
    wikiTitle: 'Ronaldinho',
  },
  {
    id: 'messi-2012', nome: 'Lionel Messi', apelido: 'La Pulga', ano: 2012, nascimento: 1987,
    flag: '🇦🇷', raridade: 'mitica', posicao: 'Atacante', clube: 'Barcelona',
    cor: '#FFB800',
    atributos: { copa_gols: 13, copa_jogos: 26, gols_carreira: 838, copas: 5, titulos: 44, ballon_dor: 8, cl_titulos: 4, selecao_gols: 112, selecao_jogos: 191, altura: 170 },
    perguntas: ['ballon_dor', 'copa_jogos', 'cl_titulos'],
    wikiTitle: 'Lionel Messi',
  },
  {
    id: 'cr7-2013', nome: 'Cristiano Ronaldo', apelido: 'CR7', ano: 2013, nascimento: 1985,
    flag: '🇵🇹', raridade: 'mitica', posicao: 'Atacante', clube: 'Real Madrid',
    cor: '#FFB800',
    atributos: { copa_gols: 8, copa_jogos: 22, gols_carreira: 900, copas: 5, titulos: 34, ballon_dor: 5, cl_titulos: 5, selecao_gols: 135, selecao_jogos: 217, altura: 187 },
    perguntas: ['ballon_dor', 'selecao_gols', 'cl_titulos'],
    wikiTitle: 'Cristiano Ronaldo',
  },

  // ── ÉPICA (azul/roxo) ──────────────────────────────────────────
  {
    id: 'romario-1994', nome: 'Romário', apelido: 'Baixinho', ano: 1994, nascimento: 1966,
    flag: '🇧🇷', raridade: 'epica', posicao: 'Atacante', clube: 'Barcelona / Brasil',
    cor: '#7C3AED',
    atributos: { copa_gols: 8, copa_jogos: 16, gols_carreira: 772, copas: 3, titulos: 18, selecao_gols: 55, selecao_jogos: 70, altura: 169 },
    perguntas: ['copa_gols', 'gols_carreira', 'copas'],
    wikiTitle: 'Romário',
  },
  {
    id: 'bebeto-1994', nome: 'Bebeto', apelido: 'Bebeto', ano: 1994, nascimento: 1964,
    flag: '🇧🇷', raridade: 'epica', posicao: 'Atacante', clube: 'Deportivo / Brasil',
    cor: '#7C3AED',
    atributos: { copa_gols: 8, copa_jogos: 16, gols_carreira: 210, copas: 3, titulos: 12, selecao_gols: 39, selecao_jogos: 75, altura: 176 },
    perguntas: ['copa_gols', 'copa_jogos', 'selecao_jogos'],
    wikiTitle: 'Bebeto',
  },
  {
    id: 'henry-2003', nome: 'Thierry Henry', apelido: 'Titi', ano: 2003, nascimento: 1977,
    flag: '🇫🇷', raridade: 'epica', posicao: 'Atacante', clube: 'Arsenal',
    cor: '#7C3AED',
    atributos: { copa_gols: 6, copa_jogos: 17, gols_carreira: 415, copas: 3, titulos: 22, selecao_gols: 51, selecao_jogos: 123, cl_titulos: 0, altura: 188 },
    perguntas: ['gols_carreira', 'selecao_jogos', 'copa_gols'],
    wikiTitle: 'Thierry Henry',
  },
  {
    id: 'totti-2001', nome: 'Francesco Totti', apelido: 'Il Capitano', ano: 2001, nascimento: 1976,
    flag: '🇮🇹', raridade: 'epica', posicao: 'Meia', clube: 'Roma',
    cor: '#7C3AED',
    atributos: { copa_gols: 0, copa_jogos: 7, gols_carreira: 307, copas: 3, titulos: 7, selecao_gols: 9, selecao_jogos: 58, altura: 180 },
    perguntas: ['gols_carreira', 'titulos', 'selecao_jogos'],
    wikiTitle: 'Francesco Totti',
  },
  {
    id: 'kaka-2007', nome: 'Kaká', apelido: 'Kaká', ano: 2007, nascimento: 1982,
    flag: '🇧🇷', raridade: 'epica', posicao: 'Meia', clube: 'AC Milan',
    cor: '#7C3AED',
    atributos: { copa_gols: 0, copa_jogos: 11, gols_carreira: 204, copas: 2, titulos: 13, ballon_dor: 1, cl_titulos: 1, selecao_gols: 29, selecao_jogos: 92, altura: 186 },
    perguntas: ['ballon_dor', 'cl_titulos', 'gols_carreira'],
    wikiTitle: 'Kaká',
  },
  {
    id: 'adriano-2004', nome: 'Adriano', apelido: 'Imperador', ano: 2004, nascimento: 1982,
    flag: '🇧🇷', raridade: 'epica', posicao: 'Atacante', clube: 'Inter',
    cor: '#7C3AED',
    atributos: { copa_gols: 0, copa_jogos: 6, gols_carreira: 210, copas: 1, titulos: 10, selecao_gols: 27, selecao_jogos: 48, altura: 188 },
    perguntas: ['gols_carreira', 'selecao_gols', 'altura'],
    wikiTitle: 'Adriano (footballer, born 1982)',
  },
  {
    id: 'ibra-2012', nome: 'Zlatan Ibrahimović', apelido: 'Ibra', ano: 2012, nascimento: 1981,
    flag: '🇸🇪', raridade: 'epica', posicao: 'Atacante', clube: 'PSG',
    cor: '#7C3AED',
    atributos: { copa_gols: 0, copa_jogos: 0, gols_carreira: 570, copas: 0, titulos: 32, selecao_gols: 62, selecao_jogos: 120, altura: 195 },
    perguntas: ['gols_carreira', 'titulos', 'altura'],
    wikiTitle: 'Zlatan Ibrahimović',
  },
  {
    id: 'van-basten-1988', nome: 'Marco van Basten', apelido: 'Il Cigno', ano: 1988, nascimento: 1964,
    flag: '🇳🇱', raridade: 'epica', posicao: 'Atacante', clube: 'AC Milan / Holanda',
    cor: '#7C3AED',
    atributos: { copa_gols: 5, copa_jogos: 8, gols_carreira: 277, copas: 2, titulos: 9, ballon_dor: 3, cl_titulos: 2, selecao_gols: 24, selecao_jogos: 58, altura: 188 },
    perguntas: ['ballon_dor', 'cl_titulos', 'copa_gols'],
    wikiTitle: 'Marco van Basten',
  },
  {
    id: 'stoichkov-1994', nome: 'Hristo Stoichkov', apelido: 'Stoichkov', ano: 1994, nascimento: 1966,
    flag: '🇧🇬', raridade: 'epica', posicao: 'Atacante', clube: 'Barcelona / Bulgária',
    cor: '#7C3AED',
    atributos: { copa_gols: 6, copa_jogos: 13, gols_carreira: 255, copas: 3, titulos: 15, ballon_dor: 1, selecao_gols: 37, selecao_jogos: 83, altura: 176 },
    perguntas: ['copa_gols', 'ballon_dor', 'selecao_jogos'],
    wikiTitle: 'Hristo Stoichkov',
  },
  {
    id: 'rivaldo-2002', nome: 'Rivaldo', apelido: 'Rivaldo', ano: 2002, nascimento: 1972,
    flag: '🇧🇷', raridade: 'epica', posicao: 'Meia', clube: 'Barcelona / Brasil',
    cor: '#7C3AED',
    atributos: { copa_gols: 8, copa_jogos: 14, gols_carreira: 370, copas: 2, titulos: 20, ballon_dor: 1, selecao_gols: 35, selecao_jogos: 74, altura: 181 },
    perguntas: ['copa_gols', 'ballon_dor', 'gols_carreira'],
    wikiTitle: 'Rivaldo',
  },
  {
    id: 'drogba-2010', nome: 'Didier Drogba', apelido: 'Drogba', ano: 2010, nascimento: 1978,
    flag: '🇨🇮', raridade: 'epica', posicao: 'Atacante', clube: 'Chelsea',
    cor: '#7C3AED',
    atributos: { copa_gols: 0, copa_jogos: 8, gols_carreira: 300, copas: 2, titulos: 19, cl_titulos: 1, selecao_gols: 65, selecao_jogos: 105, altura: 189 },
    perguntas: ['cl_titulos', 'selecao_gols', 'gols_carreira'],
    wikiTitle: 'Didier Drogba',
  },
  {
    id: 'beckham-1999', nome: 'David Beckham', apelido: 'Beckham', ano: 1999, nascimento: 1975,
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', raridade: 'epica', posicao: 'Meia', clube: 'Man. United',
    cor: '#7C3AED',
    atributos: { copa_gols: 1, copa_jogos: 9, gols_carreira: 131, copas: 3, titulos: 19, selecao_gols: 17, selecao_jogos: 115, altura: 183 },
    perguntas: ['titulos', 'selecao_jogos', 'copa_jogos'],
    wikiTitle: 'David Beckham',
  },
  {
    id: 'roberto-carlos-1997', nome: 'Roberto Carlos', apelido: 'Roberto Carlos', ano: 1997, nascimento: 1973,
    flag: '🇧🇷', raridade: 'epica', posicao: 'Lateral', clube: 'Real Madrid',
    cor: '#7C3AED',
    atributos: { copa_gols: 4, copa_jogos: 11, gols_carreira: 113, copas: 3, titulos: 20, cl_titulos: 3, selecao_gols: 11, selecao_jogos: 125, altura: 168 },
    perguntas: ['cl_titulos', 'selecao_jogos', 'altura'],
    wikiTitle: 'Roberto Carlos',
  },

  // ── COMUM (verde) ──────────────────────────────────────────────
  {
    id: 'zico-1982', nome: 'Zico', apelido: 'Zico', ano: 1982, nascimento: 1953,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Meia', clube: 'Flamengo / Brasil',
    cor: '#16B89A',
    atributos: { copa_gols: 5, copa_jogos: 11, gols_carreira: 508, copas: 3, titulos: 18, selecao_gols: 48, selecao_jogos: 71, altura: 177 },
    perguntas: ['copa_gols', 'gols_carreira', 'selecao_jogos'],
    wikiTitle: 'Zico',
  },
  {
    id: 'socrates-1982', nome: 'Sócrates', apelido: 'Doutor', ano: 1982, nascimento: 1954,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Meia', clube: 'Corinthians / Brasil',
    cor: '#16B89A',
    atributos: { copa_jogos: 9, gols_carreira: 230, copas: 2, titulos: 8, selecao_gols: 22, selecao_jogos: 60, altura: 192 },
    perguntas: ['altura', 'gols_carreira', 'selecao_jogos'],
    wikiTitle: 'Sócrates (footballer)',
  },
  {
    id: 'falcao-1982', nome: 'Paulo Roberto Falcão', apelido: 'Falcão', ano: 1982, nascimento: 1953,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Meia', clube: 'Roma / Brasil',
    cor: '#16B89A',
    atributos: { copa_jogos: 9, gols_carreira: 70, copas: 2, titulos: 10, selecao_gols: 12, selecao_jogos: 34, altura: 178 },
    perguntas: ['copa_jogos', 'selecao_jogos', 'titulos'],
    wikiTitle: 'Paulo Roberto Falcão',
  },
  {
    id: 'jardel-2001', nome: 'Mário Jardel', apelido: 'Jardel', ano: 2001, nascimento: 1973,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Porto / Galatasaray',
    cor: '#16B89A',
    atributos: { gols_carreira: 392, copas: 1, titulos: 8, selecao_gols: 15, selecao_jogos: 40, altura: 190 },
    perguntas: ['gols_carreira', 'titulos', 'altura'],
    wikiTitle: 'Mário Jardel',
  },
  {
    id: 'edmundo-1997', nome: 'Edmundo', apelido: 'Animal', ano: 1997, nascimento: 1971,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Vasco',
    cor: '#16B89A',
    atributos: { copa_gols: 1, copa_jogos: 3, gols_carreira: 232, copas: 1, titulos: 9, selecao_gols: 10, selecao_jogos: 39, altura: 180 },
    perguntas: ['gols_carreira', 'selecao_gols', 'copa_jogos'],
    wikiTitle: 'Edmundo (footballer)',
  },
  {
    id: 'robinho-2005', nome: 'Robinho', apelido: 'Robinho', ano: 2005, nascimento: 1984,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Real Madrid',
    cor: '#16B89A',
    atributos: { copa_gols: 1, copa_jogos: 6, gols_carreira: 194, copas: 2, titulos: 9, selecao_gols: 28, selecao_jogos: 100, altura: 172 },
    perguntas: ['selecao_jogos', 'gols_carreira', 'altura'],
    wikiTitle: 'Robinho',
  },
  {
    id: 'denilson-1998', nome: 'Denílson', apelido: 'Denílson', ano: 1998, nascimento: 1977,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Meia', clube: 'Betis / Brasil',
    cor: '#16B89A',
    atributos: { copa_jogos: 7, gols_carreira: 28, copas: 2, titulos: 4, selecao_gols: 1, selecao_jogos: 60, altura: 173 },
    perguntas: ['copa_jogos', 'selecao_jogos', 'titulos'],
    wikiTitle: 'Denílson (Brazilian footballer)',
  },
  {
    id: 'cafu-2002', nome: 'Marcos Cafu', apelido: 'Cafu', ano: 2002, nascimento: 1970,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Lateral', clube: 'Roma / Brasil',
    cor: '#16B89A',
    atributos: { copa_gols: 0, copa_jogos: 20, gols_carreira: 44, copas: 4, titulos: 10, selecao_gols: 5, selecao_jogos: 142, altura: 176 },
    perguntas: ['copa_jogos', 'copas', 'selecao_jogos'],
    wikiTitle: 'Cafu',
  },
  {
    id: 'roberto-baggio-1994', nome: 'Roberto Baggio', apelido: 'Il Codino', ano: 1994, nascimento: 1967,
    flag: '🇮🇹', raridade: 'comum', posicao: 'Meia', clube: 'Juventus / Itália',
    cor: '#16B89A',
    atributos: { copa_gols: 9, copa_jogos: 16, gols_carreira: 318, copas: 3, titulos: 9, ballon_dor: 1, selecao_gols: 27, selecao_jogos: 56, altura: 174 },
    perguntas: ['copa_gols', 'ballon_dor', 'gols_carreira'],
    wikiTitle: 'Roberto Baggio',
  },

  // ── MÍTICA — era clássica ──────────────────────────────────────
  {
    id: 'garrincha-1962', nome: 'Garrincha', apelido: 'A Alegria do Povo', ano: 1962, nascimento: 1933,
    flag: '🇧🇷', raridade: 'mitica', posicao: 'Ponta Direita', clube: 'Botafogo / Brasil',
    cor: '#FFB800',
    atributos: { copa_gols: 7, copa_jogos: 12, gols_carreira: 232, copas: 3, titulos: 5, selecao_gols: 12, selecao_jogos: 50, altura: 169 },
    perguntas: ['copa_gols', 'copa_jogos', 'copas'],
    wikiTitle: 'Garrincha',
  },
  {
    id: 'cruyff-1974', nome: 'Johan Cruyff', apelido: 'De Totale Voetballer', ano: 1974, nascimento: 1947,
    flag: '🇳🇱', raridade: 'mitica', posicao: 'Atacante', clube: 'Ajax / Holanda',
    cor: '#FFB800',
    atributos: { copa_gols: 3, copa_jogos: 14, gols_carreira: 392, copas: 1, titulos: 14, ballon_dor: 3, cl_titulos: 3, selecao_gols: 33, selecao_jogos: 48, altura: 180 },
    perguntas: ['ballon_dor', 'cl_titulos', 'gols_carreira'],
    wikiTitle: 'Johan Cruyff',
  },
  {
    id: 'beckenbauer-1974', nome: 'Franz Beckenbauer', apelido: 'Der Kaiser', ano: 1974, nascimento: 1945,
    flag: '🇩🇪', raridade: 'mitica', posicao: 'Líbero', clube: 'Bayern / Alemanha',
    cor: '#FFB800',
    atributos: { copa_gols: 5, copa_jogos: 18, gols_carreira: 111, copas: 4, titulos: 16, ballon_dor: 2, cl_titulos: 3, selecao_gols: 14, selecao_jogos: 103, altura: 181 },
    perguntas: ['copas', 'ballon_dor', 'cl_titulos'],
    wikiTitle: 'Franz Beckenbauer',
  },
  {
    id: 'eusebio-1966', nome: 'Eusébio', apelido: 'A Pantera Negra', ano: 1966, nascimento: 1942,
    flag: '🇵🇹', raridade: 'mitica', posicao: 'Atacante', clube: 'Benfica / Portugal',
    cor: '#FFB800',
    atributos: { copa_gols: 9, copa_jogos: 6, gols_carreira: 733, copas: 1, titulos: 19, ballon_dor: 1, cl_titulos: 1, selecao_gols: 41, selecao_jogos: 64, altura: 175 },
    perguntas: ['copa_gols', 'gols_carreira', 'ballon_dor'],
    wikiTitle: 'Eusébio',
  },
  {
    id: 'platini-1984', nome: 'Michel Platini', apelido: 'Le Roi Michel', ano: 1984, nascimento: 1955,
    flag: '🇫🇷', raridade: 'mitica', posicao: 'Meia', clube: 'Juventus / França',
    cor: '#FFB800',
    atributos: { copa_gols: 5, copa_jogos: 14, gols_carreira: 312, copas: 3, titulos: 18, ballon_dor: 3, cl_titulos: 1, selecao_gols: 41, selecao_jogos: 72, altura: 179 },
    perguntas: ['ballon_dor', 'copa_gols', 'gols_carreira'],
    wikiTitle: 'Michel Platini',
  },
  {
    id: 'best-1968', nome: 'George Best', apelido: 'O Quinto Beatle', ano: 1968, nascimento: 1946,
    flag: '🏴󠁧󠁢󠁮󠁩󠁲󠁿', raridade: 'mitica', posicao: 'Atacante', clube: 'Man. United / Irlanda do N.',
    cor: '#FFB800',
    atributos: { gols_carreira: 473, copas: 0, titulos: 9, ballon_dor: 1, cl_titulos: 1, selecao_gols: 9, selecao_jogos: 37, altura: 175 },
    perguntas: ['gols_carreira', 'ballon_dor', 'titulos'],
    wikiTitle: 'George Best',
  },
  {
    id: 'jairzinho-1970', nome: 'Jairzinho', apelido: 'O Furacão da Copa', ano: 1970, nascimento: 1944,
    flag: '🇧🇷', raridade: 'mitica', posicao: 'Ponta Direita', clube: 'Botafogo / Brasil',
    cor: '#FFB800',
    atributos: { copa_gols: 9, copa_jogos: 16, gols_carreira: 199, copas: 3, titulos: 8, selecao_gols: 33, selecao_jogos: 81, altura: 180 },
    perguntas: ['copa_gols', 'copa_jogos', 'copas'],
    wikiTitle: 'Jairzinho',
  },

  // ── ÉPICA — grandes estrelas ───────────────────────────────────
  {
    id: 'neymar-2015', nome: 'Neymar Jr.', apelido: 'Ney', ano: 2015, nascimento: 1992,
    flag: '🇧🇷', raridade: 'epica', posicao: 'Atacante', clube: 'Barcelona / Brasil',
    cor: '#7C3AED',
    atributos: { copa_gols: 8, copa_jogos: 14, gols_carreira: 440, copas: 3, titulos: 33, cl_titulos: 1, selecao_gols: 79, selecao_jogos: 128, altura: 175 },
    perguntas: ['selecao_gols', 'gols_carreira', 'cl_titulos'],
    wikiTitle: 'Neymar',
  },
  {
    id: 'mbappe-2022', nome: 'Kylian Mbappé', apelido: 'K.M.10', ano: 2022, nascimento: 2000,
    flag: '🇫🇷', raridade: 'epica', posicao: 'Atacante', clube: 'PSG / França',
    cor: '#7C3AED',
    atributos: { copa_gols: 12, copa_jogos: 14, gols_carreira: 351, copas: 2, titulos: 17, selecao_gols: 53, selecao_jogos: 90, altura: 178 },
    perguntas: ['copa_gols', 'gols_carreira', 'selecao_gols'],
    wikiTitle: 'Kylian Mbappé',
  },
  {
    id: 'xavi-2011', nome: 'Xavi Hernández', apelido: 'Xavi', ano: 2011, nascimento: 1980,
    flag: '🇪🇸', raridade: 'epica', posicao: 'Meia', clube: 'Barcelona / Espanha',
    cor: '#7C3AED',
    atributos: { copa_jogos: 16, gols_carreira: 100, copas: 2, titulos: 25, cl_titulos: 4, selecao_gols: 13, selecao_jogos: 133, altura: 170 },
    perguntas: ['cl_titulos', 'selecao_jogos', 'titulos'],
    wikiTitle: 'Xavi Hernández',
  },
  {
    id: 'iniesta-2010', nome: 'Andrés Iniesta', apelido: 'El Ilusionista', ano: 2010, nascimento: 1984,
    flag: '🇪🇸', raridade: 'epica', posicao: 'Meia', clube: 'Barcelona / Espanha',
    cor: '#7C3AED',
    atributos: { copa_jogos: 12, gols_carreira: 90, copas: 2, titulos: 32, cl_titulos: 4, selecao_gols: 13, selecao_jogos: 131, altura: 171 },
    perguntas: ['cl_titulos', 'titulos', 'selecao_jogos'],
    wikiTitle: 'Andrés Iniesta',
  },
  {
    id: 'gullit-1988', nome: 'Ruud Gullit', apelido: 'Tulipa Negra', ano: 1988, nascimento: 1962,
    flag: '🇳🇱', raridade: 'epica', posicao: 'Atacante', clube: 'AC Milan / Holanda',
    cor: '#7C3AED',
    atributos: { copa_jogos: 9, gols_carreira: 268, copas: 2, titulos: 15, ballon_dor: 1, cl_titulos: 2, selecao_gols: 17, selecao_jogos: 66, altura: 188 },
    perguntas: ['ballon_dor', 'cl_titulos', 'gols_carreira'],
    wikiTitle: 'Ruud Gullit',
  },
  {
    id: 'figo-2001', nome: 'Luís Figo', apelido: 'O Boa', ano: 2001, nascimento: 1972,
    flag: '🇵🇹', raridade: 'epica', posicao: 'Meia', clube: 'Real Madrid / Portugal',
    cor: '#7C3AED',
    atributos: { copa_jogos: 7, gols_carreira: 171, copas: 1, titulos: 19, ballon_dor: 1, cl_titulos: 1, selecao_gols: 32, selecao_jogos: 127, altura: 181 },
    perguntas: ['ballon_dor', 'selecao_jogos', 'titulos'],
    wikiTitle: 'Luís Figo',
  },
  {
    id: 'pirlo-2012', nome: 'Andrea Pirlo', apelido: 'Il Professore', ano: 2012, nascimento: 1979,
    flag: '🇮🇹', raridade: 'epica', posicao: 'Meia', clube: 'Juventus / Itália',
    cor: '#7C3AED',
    atributos: { copa_jogos: 13, gols_carreira: 83, copas: 3, titulos: 24, cl_titulos: 2, selecao_gols: 13, selecao_jogos: 116, altura: 177 },
    perguntas: ['titulos', 'selecao_jogos', 'copa_jogos'],
    wikiTitle: 'Andrea Pirlo',
  },
  {
    id: 'shevchenko-2004', nome: 'Andriy Shevchenko', apelido: 'Sheva', ano: 2004, nascimento: 1976,
    flag: '🇺🇦', raridade: 'epica', posicao: 'Atacante', clube: 'AC Milan / Ucrânia',
    cor: '#7C3AED',
    atributos: { copa_gols: 0, copa_jogos: 3, gols_carreira: 356, copas: 1, titulos: 12, ballon_dor: 1, cl_titulos: 1, selecao_gols: 48, selecao_jogos: 111, altura: 183 },
    perguntas: ['ballon_dor', 'gols_carreira', 'selecao_gols'],
    wikiTitle: 'Andriy Shevchenko',
  },
  {
    id: 'r9-2002', nome: 'Ronaldo Nazário', apelido: 'O Fenômeno', ano: 2002, nascimento: 1976,
    flag: '🇧🇷', raridade: 'epica', posicao: 'Atacante', clube: 'Real Madrid / Brasil',
    cor: '#7C3AED',
    atributos: { copa_gols: 15, copa_jogos: 19, gols_carreira: 415, copas: 3, titulos: 14, ballon_dor: 2, cl_titulos: 0, selecao_gols: 62, selecao_jogos: 98, altura: 183 },
    perguntas: ['copa_gols', 'copa_jogos', 'gols_carreira'],
    wikiTitle: 'Ronaldo (Brazilian footballer)',
  },
  {
    id: 'batistuta-1998', nome: 'Gabriel Batistuta', apelido: 'Batigol', ano: 1998, nascimento: 1969,
    flag: '🇦🇷', raridade: 'epica', posicao: 'Atacante', clube: 'Fiorentina / Argentina',
    cor: '#7C3AED',
    atributos: { copa_gols: 10, copa_jogos: 12, gols_carreira: 336, copas: 3, titulos: 5, selecao_gols: 54, selecao_jogos: 78, altura: 184 },
    perguntas: ['copa_gols', 'gols_carreira', 'selecao_gols'],
    wikiTitle: 'Gabriel Batistuta',
  },
  {
    id: 'riquelme-2004', nome: 'Juan Román Riquelme', apelido: 'El Último 10', ano: 2004, nascimento: 1978,
    flag: '🇦🇷', raridade: 'epica', posicao: 'Meia', clube: 'Villarreal / Argentina',
    cor: '#7C3AED',
    atributos: { copa_jogos: 7, gols_carreira: 134, copas: 2, titulos: 9, selecao_gols: 17, selecao_jogos: 51, altura: 181 },
    perguntas: ['selecao_jogos', 'gols_carreira', 'copa_jogos'],
    wikiTitle: 'Juan Román Riquelme',
  },
  {
    id: 'maldini-1995', nome: 'Paolo Maldini', apelido: 'Il Capitano', ano: 1995, nascimento: 1968,
    flag: '🇮🇹', raridade: 'epica', posicao: 'Zagueiro', clube: 'AC Milan / Itália',
    cor: '#7C3AED',
    atributos: { copa_jogos: 23, gols_carreira: 33, copas: 4, titulos: 26, cl_titulos: 5, selecao_gols: 7, selecao_jogos: 126, altura: 186 },
    perguntas: ['cl_titulos', 'copas', 'selecao_jogos'],
    wikiTitle: 'Paolo Maldini',
  },
  {
    id: 'raul-2000', nome: 'Raúl González', apelido: 'El Ángel', ano: 2000, nascimento: 1977,
    flag: '🇪🇸', raridade: 'epica', posicao: 'Atacante', clube: 'Real Madrid / Espanha',
    cor: '#7C3AED',
    atributos: { copa_jogos: 0, gols_carreira: 444, copas: 0, titulos: 16, cl_titulos: 3, selecao_gols: 44, selecao_jogos: 102, altura: 180 },
    perguntas: ['gols_carreira', 'cl_titulos', 'titulos'],
    wikiTitle: 'Raúl González Blanco',
  },
  {
    id: 'bergkamp-1998', nome: 'Dennis Bergkamp', apelido: 'Non-Flying Dutchman', ano: 1998, nascimento: 1969,
    flag: '🇳🇱', raridade: 'epica', posicao: 'Atacante', clube: 'Arsenal / Holanda',
    cor: '#7C3AED',
    atributos: { copa_gols: 6, copa_jogos: 12, gols_carreira: 364, copas: 2, titulos: 12, selecao_gols: 37, selecao_jogos: 79, altura: 188 },
    perguntas: ['copa_gols', 'gols_carreira', 'selecao_gols'],
    wikiTitle: 'Dennis Bergkamp',
  },
  {
    id: 'robben-2014', nome: 'Arjen Robben', apelido: 'O Homem da Curva', ano: 2014, nascimento: 1984,
    flag: '🇳🇱', raridade: 'epica', posicao: 'Atacante', clube: 'Bayern / Holanda',
    cor: '#7C3AED',
    atributos: { copa_gols: 6, copa_jogos: 16, gols_carreira: 315, copas: 3, titulos: 22, cl_titulos: 1, selecao_gols: 37, selecao_jogos: 96, altura: 181 },
    perguntas: ['copa_gols', 'gols_carreira', 'titulos'],
    wikiTitle: 'Arjen Robben',
  },
  {
    id: 'matthaus-1990', nome: 'Lothar Matthäus', apelido: 'Mäuse', ano: 1990, nascimento: 1961,
    flag: '🇩🇪', raridade: 'epica', posicao: 'Meia', clube: 'Inter / Alemanha',
    cor: '#7C3AED',
    atributos: { copa_gols: 6, copa_jogos: 25, gols_carreira: 205, copas: 5, titulos: 18, ballon_dor: 1, cl_titulos: 1, selecao_gols: 23, selecao_jogos: 150, altura: 181 },
    perguntas: ['copa_jogos', 'copas', 'selecao_jogos'],
    wikiTitle: 'Lothar Matthäus',
  },
  {
    id: 'etoo-2006', nome: "Samuel Eto'o", apelido: "Le Lion Indomptable", ano: 2006, nascimento: 1981,
    flag: '🇨🇲', raridade: 'epica', posicao: 'Atacante', clube: 'Barcelona / Camarões',
    cor: '#7C3AED',
    atributos: { copa_gols: 4, copa_jogos: 11, gols_carreira: 399, copas: 3, titulos: 19, cl_titulos: 2, selecao_gols: 56, selecao_jogos: 118, altura: 180 },
    perguntas: ['cl_titulos', 'selecao_gols', 'gols_carreira'],
    wikiTitle: "Samuel Eto'o",
  },
  {
    id: 'torres-2008', nome: 'Fernando Torres', apelido: 'El Niño', ano: 2008, nascimento: 1984,
    flag: '🇪🇸', raridade: 'epica', posicao: 'Atacante', clube: 'Liverpool / Espanha',
    cor: '#7C3AED',
    atributos: { copa_gols: 3, copa_jogos: 10, gols_carreira: 278, copas: 2, titulos: 14, selecao_gols: 38, selecao_jogos: 110, altura: 185 },
    perguntas: ['gols_carreira', 'selecao_gols', 'copa_gols'],
    wikiTitle: 'Fernando Torres',
  },
  {
    id: 'tevez-2006', nome: 'Carlos Tevez', apelido: 'Apache', ano: 2006, nascimento: 1984,
    flag: '🇦🇷', raridade: 'epica', posicao: 'Atacante', clube: 'Corinthians / Argentina',
    cor: '#7C3AED',
    atributos: { copa_gols: 1, copa_jogos: 7, gols_carreira: 338, copas: 2, titulos: 20, selecao_gols: 13, selecao_jogos: 76, altura: 173 },
    perguntas: ['gols_carreira', 'titulos', 'copa_jogos'],
    wikiTitle: 'Carlos Tevez',
  },
  {
    id: 'modric-2018', nome: 'Luka Modrić', apelido: 'El Mago', ano: 2018, nascimento: 1985,
    flag: '🇭🇷', raridade: 'epica', posicao: 'Meia', clube: 'Real Madrid / Croácia',
    cor: '#7C3AED',
    atributos: { copa_jogos: 16, gols_carreira: 141, copas: 4, titulos: 29, ballon_dor: 1, cl_titulos: 5, selecao_gols: 23, selecao_jogos: 176, altura: 172 },
    perguntas: ['ballon_dor', 'cl_titulos', 'copa_jogos'],
    wikiTitle: 'Luka Modrić',
  },
  {
    id: 'lewandowski-2021', nome: 'Robert Lewandowski', apelido: 'Lewy', ano: 2021, nascimento: 1988,
    flag: '🇵🇱', raridade: 'epica', posicao: 'Atacante', clube: 'Bayern / Polônia',
    cor: '#7C3AED',
    atributos: { copa_gols: 0, copa_jogos: 4, gols_carreira: 630, copas: 1, titulos: 21, selecao_gols: 82, selecao_jogos: 148, altura: 184 },
    perguntas: ['gols_carreira', 'selecao_gols', 'selecao_jogos'],
    wikiTitle: 'Robert Lewandowski',
  },
  {
    id: 'vieira-2001', nome: 'Patrick Vieira', apelido: 'Le Capitaine', ano: 2001, nascimento: 1976,
    flag: '🇫🇷', raridade: 'epica', posicao: 'Meia', clube: 'Arsenal / França',
    cor: '#7C3AED',
    atributos: { copa_jogos: 9, gols_carreira: 80, copas: 2, titulos: 19, cl_titulos: 0, selecao_gols: 6, selecao_jogos: 107, altura: 193 },
    perguntas: ['titulos', 'selecao_jogos', 'altura'],
    wikiTitle: 'Patrick Vieira',
  },
  {
    id: 'aguero-2015', nome: 'Sergio Agüero', apelido: 'Kun', ano: 2015, nascimento: 1988,
    flag: '🇦🇷', raridade: 'epica', posicao: 'Atacante', clube: 'Man. City / Argentina',
    cor: '#7C3AED',
    atributos: { copa_gols: 2, copa_jogos: 9, gols_carreira: 426, copas: 3, titulos: 16, selecao_gols: 41, selecao_jogos: 101, altura: 173 },
    perguntas: ['gols_carreira', 'selecao_gols', 'titulos'],
    wikiTitle: 'Sergio Agüero',
  },
  {
    id: 'rooney-2005', nome: 'Wayne Rooney', apelido: 'Shrek', ano: 2005, nascimento: 1985,
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', raridade: 'epica', posicao: 'Atacante', clube: 'Man. United / Inglaterra',
    cor: '#7C3AED',
    atributos: { copa_gols: 0, copa_jogos: 9, gols_carreira: 253, copas: 3, titulos: 16, selecao_gols: 53, selecao_jogos: 120, altura: 176 },
    perguntas: ['gols_carreira', 'selecao_gols', 'selecao_jogos'],
    wikiTitle: 'Wayne Rooney',
  },
  {
    id: 'di-maria-2014', nome: 'Ángel Di María', apelido: 'El Fideo', ano: 2014, nascimento: 1988,
    flag: '🇦🇷', raridade: 'epica', posicao: 'Meia', clube: 'Real Madrid / Argentina',
    cor: '#7C3AED',
    atributos: { copa_gols: 3, copa_jogos: 15, gols_carreira: 257, copas: 4, titulos: 22, selecao_gols: 31, selecao_jogos: 145, altura: 178 },
    perguntas: ['copa_jogos', 'selecao_jogos', 'titulos'],
    wikiTitle: 'Ángel Di María',
  },
  {
    id: 'puskas-1960', nome: 'Ferenc Puskás', apelido: 'O Canhão Galáctico', ano: 1960, nascimento: 1927,
    flag: '🇭🇺', raridade: 'epica', posicao: 'Atacante', clube: 'Real Madrid / Hungria',
    cor: '#7C3AED',
    atributos: { copa_gols: 4, copa_jogos: 8, gols_carreira: 729, copas: 2, titulos: 18, cl_titulos: 3, selecao_gols: 84, selecao_jogos: 89, altura: 172 },
    perguntas: ['gols_carreira', 'selecao_gols', 'cl_titulos'],
    wikiTitle: 'Ferenc Puskás',
  },
  {
    id: 'gerd-muller-1972', nome: 'Gerd Müller', apelido: 'Bomba', ano: 1972, nascimento: 1945,
    flag: '🇩🇪', raridade: 'epica', posicao: 'Atacante', clube: 'Bayern / Alemanha',
    cor: '#7C3AED',
    atributos: { copa_gols: 14, copa_jogos: 13, gols_carreira: 735, copas: 2, titulos: 16, ballon_dor: 1, cl_titulos: 3, selecao_gols: 68, selecao_jogos: 62, altura: 176 },
    perguntas: ['copa_gols', 'gols_carreira', 'cl_titulos'],
    wikiTitle: 'Gerd Müller',
  },

  // ── COMUM — memórias & quase-lendas ───────────────────────────
  {
    id: 'vampeta-1999', nome: 'Vampeta', apelido: 'Vampeta', ano: 1999, nascimento: 1974,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Meia', clube: 'Galatasaray / Brasil',
    cor: '#16B89A',
    atributos: { copa_jogos: 6, gols_carreira: 53, copas: 1, titulos: 10, selecao_gols: 2, selecao_jogos: 35, altura: 176 },
    perguntas: ['copa_jogos', 'selecao_jogos', 'titulos'],
    wikiTitle: 'Vampeta',
  },
  {
    id: 'dembele-2023', nome: 'Ousmane Dembélé', apelido: 'Dembélé', ano: 2023, nascimento: 1997,
    flag: '🇫🇷', raridade: 'epica', posicao: 'Atacante', clube: 'Barcelona / França',
    cor: '#7C3AED',
    atributos: { copa_gols: 0, copa_jogos: 7, gols_carreira: 163, copas: 2, titulos: 12, selecao_gols: 14, selecao_jogos: 56, altura: 178 },
    perguntas: ['gols_carreira', 'selecao_jogos', 'copa_jogos'],
    wikiTitle: 'Ousmane Dembélé',
  },
  {
    id: 'dani-alves-2011', nome: 'Dani Alves', apelido: 'Dani Alves', ano: 2011, nascimento: 1983,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Lateral', clube: 'Barcelona / Brasil',
    cor: '#16B89A',
    atributos: { copa_gols: 3, copa_jogos: 10, gols_carreira: 91, copas: 2, titulos: 47, cl_titulos: 3, selecao_gols: 8, selecao_jogos: 118, altura: 171 },
    perguntas: ['titulos', 'cl_titulos', 'selecao_jogos'],
    wikiTitle: 'Dani Alves',
  },
  {
    id: 'thiago-silva-2013', nome: 'Thiago Silva', apelido: 'O Monstro', ano: 2013, nascimento: 1984,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Zagueiro', clube: 'PSG / Brasil',
    cor: '#16B89A',
    atributos: { copa_jogos: 9, gols_carreira: 41, copas: 2, titulos: 22, selecao_gols: 7, selecao_jogos: 107, altura: 183 },
    perguntas: ['selecao_jogos', 'titulos', 'copa_jogos'],
    wikiTitle: 'Thiago Silva',
  },
  {
    id: 'oscar-2012', nome: 'Oscar', apelido: 'Oscar', ano: 2012, nascimento: 1991,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Meia', clube: 'Chelsea / Brasil',
    cor: '#16B89A',
    atributos: { copa_jogos: 5, gols_carreira: 141, copas: 1, titulos: 8, selecao_gols: 13, selecao_jogos: 48, altura: 179 },
    perguntas: ['gols_carreira', 'selecao_jogos', 'copa_jogos'],
    wikiTitle: 'Oscar (footballer, born 1991)',
  },
  {
    id: 'hulk-2012', nome: 'Hulk', apelido: 'Hulk', ano: 2012, nascimento: 1986,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Zenit / Brasil',
    cor: '#16B89A',
    atributos: { copa_jogos: 3, gols_carreira: 290, copas: 1, titulos: 12, selecao_gols: 35, selecao_jogos: 79, altura: 181 },
    perguntas: ['gols_carreira', 'selecao_gols', 'altura'],
    wikiTitle: 'Hulk (footballer)',
  },
  {
    id: 'fred-2014', nome: 'Fred', apelido: 'Fred', ano: 2014, nascimento: 1983,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Fluminense / Brasil',
    cor: '#16B89A',
    atributos: { copa_jogos: 5, gols_carreira: 187, copas: 1, titulos: 7, selecao_gols: 17, selecao_jogos: 63, altura: 189 },
    perguntas: ['gols_carreira', 'selecao_gols', 'copa_jogos'],
    wikiTitle: 'Fred (footballer, born 1983)',
  },
  {
    id: 'gilberto-silva-2002', nome: 'Gilberto Silva', apelido: 'G. Silva', ano: 2002, nascimento: 1976,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Meia', clube: 'Atlético MG / Brasil',
    cor: '#16B89A',
    atributos: { copa_jogos: 10, gols_carreira: 17, copas: 2, titulos: 11, selecao_gols: 3, selecao_jogos: 93, altura: 188 },
    perguntas: ['copas', 'selecao_jogos', 'altura'],
    wikiTitle: 'Gilberto Silva',
  },
  {
    id: 'emerson-2002', nome: 'Emerson', apelido: 'Emerson', ano: 2002, nascimento: 1976,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Meia', clube: 'Roma / Brasil',
    cor: '#16B89A',
    atributos: { copa_jogos: 3, gols_carreira: 20, copas: 1, titulos: 8, selecao_gols: 1, selecao_jogos: 59, altura: 180 },
    perguntas: ['selecao_jogos', 'titulos', 'copa_jogos'],
    wikiTitle: 'Emerson Ferreira da Rosa',
  },
  {
    id: 'careca-1990', nome: 'Careca', apelido: 'Careca', ano: 1990, nascimento: 1960,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Napoli / Brasil',
    cor: '#16B89A',
    atributos: { copa_gols: 5, copa_jogos: 14, gols_carreira: 298, copas: 3, titulos: 8, selecao_gols: 29, selecao_jogos: 65, altura: 175 },
    perguntas: ['copa_gols', 'gols_carreira', 'selecao_jogos'],
    wikiTitle: 'Careca',
  },
  {
    id: 'muller-br-1989', nome: 'Müller', apelido: 'Müller', ano: 1989, nascimento: 1966,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Atacante', clube: 'São Paulo / Brasil',
    cor: '#16B89A',
    atributos: { copa_gols: 1, copa_jogos: 7, gols_carreira: 263, copas: 2, titulos: 8, selecao_gols: 16, selecao_jogos: 53, altura: 170 },
    perguntas: ['gols_carreira', 'copa_jogos', 'selecao_gols'],
    wikiTitle: 'Müller (footballer, born 1966)',
  },
  {
    id: 'dunga-1994', nome: 'Dunga', apelido: 'Dunga', ano: 1994, nascimento: 1963,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Meia', clube: 'Stuttgart / Brasil',
    cor: '#16B89A',
    atributos: { copa_jogos: 20, gols_carreira: 31, copas: 4, titulos: 9, selecao_gols: 6, selecao_jogos: 91, altura: 176 },
    perguntas: ['copa_jogos', 'copas', 'selecao_jogos'],
    wikiTitle: 'Dunga',
  },
  {
    id: 'aldair-1994', nome: 'Aldair', apelido: 'Aldair', ano: 1994, nascimento: 1963,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Zagueiro', clube: 'Roma / Brasil',
    cor: '#16B89A',
    atributos: { copa_jogos: 10, gols_carreira: 25, copas: 2, titulos: 8, selecao_gols: 2, selecao_jogos: 73, altura: 184 },
    perguntas: ['copa_jogos', 'selecao_jogos', 'titulos'],
    wikiTitle: 'Aldair',
  },
  {
    id: 'junior-1982', nome: 'Júnior', apelido: 'Júnior', ano: 1982, nascimento: 1954,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Lateral', clube: 'Flamengo / Brasil',
    cor: '#16B89A',
    atributos: { copa_jogos: 11, gols_carreira: 75, copas: 3, titulos: 11, selecao_gols: 10, selecao_jogos: 48, altura: 178 },
    perguntas: ['copa_jogos', 'copas', 'selecao_jogos'],
    wikiTitle: 'Júnior (footballer, born 1954)',
  },
  {
    id: 'renato-gaucho-1989', nome: 'Renato Gaúcho', apelido: 'Renato', ano: 1989, nascimento: 1962,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Fluminense / Brasil',
    cor: '#16B89A',
    atributos: { copa_gols: 0, copa_jogos: 3, gols_carreira: 211, copas: 1, titulos: 7, selecao_gols: 4, selecao_jogos: 39, altura: 181 },
    perguntas: ['gols_carreira', 'selecao_jogos', 'copa_jogos'],
    wikiTitle: 'Renato Gaúcho',
  },
  {
    id: 'buffon-2006', nome: 'Gianluigi Buffon', apelido: 'Gigi', ano: 2006, nascimento: 1978,
    flag: '🇮🇹', raridade: 'comum', posicao: 'Goleiro', clube: 'Juventus / Itália',
    cor: '#16B89A',
    atributos: { copa_jogos: 20, gols_carreira: 0, copas: 4, titulos: 22, selecao_gols: 0, selecao_jogos: 176, altura: 191 },
    perguntas: ['selecao_jogos', 'copas', 'titulos'],
    wikiTitle: 'Gianluigi Buffon',
  },
  {
    id: 'gattuso-2006', nome: 'Gennaro Gattuso', apelido: 'Rino', ano: 2006, nascimento: 1978,
    flag: '🇮🇹', raridade: 'comum', posicao: 'Meia', clube: 'AC Milan / Itália',
    cor: '#16B89A',
    atributos: { copa_jogos: 10, gols_carreira: 24, copas: 2, titulos: 16, cl_titulos: 2, selecao_gols: 1, selecao_jogos: 73, altura: 177 },
    perguntas: ['cl_titulos', 'selecao_jogos', 'copa_jogos'],
    wikiTitle: 'Gennaro Gattuso',
  },
  {
    id: 'inzaghi-2003', nome: 'Filippo Inzaghi', apelido: 'Pippo', ano: 2003, nascimento: 1973,
    flag: '🇮🇹', raridade: 'comum', posicao: 'Atacante', clube: 'AC Milan / Itália',
    cor: '#16B89A',
    atributos: { copa_gols: 0, copa_jogos: 6, gols_carreira: 313, copas: 2, titulos: 17, cl_titulos: 2, selecao_gols: 25, selecao_jogos: 57, altura: 181 },
    perguntas: ['gols_carreira', 'cl_titulos', 'titulos'],
    wikiTitle: 'Filippo Inzaghi',
  },
  {
    id: 'del-piero-1997', nome: 'Alessandro Del Piero', apelido: 'Alex', ano: 1997, nascimento: 1974,
    flag: '🇮🇹', raridade: 'comum', posicao: 'Atacante', clube: 'Juventus / Itália',
    cor: '#16B89A',
    atributos: { copa_gols: 1, copa_jogos: 9, gols_carreira: 346, copas: 3, titulos: 17, cl_titulos: 1, selecao_gols: 27, selecao_jogos: 91, altura: 174 },
    perguntas: ['gols_carreira', 'cl_titulos', 'selecao_jogos'],
    wikiTitle: 'Alessandro Del Piero',
  },
  {
    id: 'crespo-2002', nome: 'Hernán Crespo', apelido: 'Valdanito', ano: 2002, nascimento: 1975,
    flag: '🇦🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Lazio / Argentina',
    cor: '#16B89A',
    atributos: { copa_gols: 0, copa_jogos: 5, gols_carreira: 352, copas: 2, titulos: 10, selecao_gols: 35, selecao_jogos: 64, altura: 186 },
    perguntas: ['gols_carreira', 'selecao_gols', 'titulos'],
    wikiTitle: 'Hernán Crespo',
  },
  {
    id: 'vieri-2002', nome: 'Christian Vieri', apelido: 'Bobo', ano: 2002, nascimento: 1973,
    flag: '🇮🇹', raridade: 'comum', posicao: 'Atacante', clube: 'Inter / Itália',
    cor: '#16B89A',
    atributos: { copa_gols: 5, copa_jogos: 9, gols_carreira: 341, copas: 2, titulos: 8, selecao_gols: 23, selecao_jogos: 49, altura: 188 },
    perguntas: ['gols_carreira', 'copa_gols', 'selecao_gols'],
    wikiTitle: 'Christian Vieri',
  },
  {
    id: 'saviola-2002', nome: 'Javier Saviola', apelido: 'El Conejo', ano: 2002, nascimento: 1981,
    flag: '🇦🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Barcelona / Argentina',
    cor: '#16B89A',
    atributos: { copa_jogos: 3, gols_carreira: 174, copas: 1, titulos: 12, selecao_gols: 11, selecao_jogos: 40, altura: 168 },
    perguntas: ['gols_carreira', 'altura', 'selecao_jogos'],
    wikiTitle: 'Javier Saviola',
  },
  {
    id: 'ballack-2004', nome: 'Michael Ballack', apelido: 'Das Tier', ano: 2004, nascimento: 1976,
    flag: '🇩🇪', raridade: 'comum', posicao: 'Meia', clube: 'Bayern / Alemanha',
    cor: '#16B89A',
    atributos: { copa_gols: 5, copa_jogos: 13, gols_carreira: 206, copas: 3, titulos: 16, selecao_gols: 42, selecao_jogos: 98, altura: 188 },
    perguntas: ['copa_gols', 'selecao_gols', 'selecao_jogos'],
    wikiTitle: 'Michael Ballack',
  },
  {
    id: 'klose-2014', nome: 'Miroslav Klose', apelido: 'Klose', ano: 2014, nascimento: 1978,
    flag: '🇩🇪', raridade: 'comum', posicao: 'Atacante', clube: 'Lazio / Alemanha',
    cor: '#16B89A',
    atributos: { copa_gols: 16, copa_jogos: 24, gols_carreira: 276, copas: 4, titulos: 11, selecao_gols: 71, selecao_jogos: 137, altura: 183 },
    perguntas: ['copa_gols', 'copa_jogos', 'copas'],
    wikiTitle: 'Miroslav Klose',
  },
  {
    id: 'nedved-2003', nome: 'Pavel Nedvěd', apelido: 'Fúria Checa', ano: 2003, nascimento: 1972,
    flag: '🇨🇿', raridade: 'comum', posicao: 'Meia', clube: 'Juventus / Rep. Checa',
    cor: '#16B89A',
    atributos: { copa_jogos: 7, gols_carreira: 163, copas: 2, titulos: 18, ballon_dor: 1, selecao_gols: 18, selecao_jogos: 91, altura: 177 },
    perguntas: ['ballon_dor', 'titulos', 'selecao_jogos'],
    wikiTitle: 'Pavel Nedvěd',
  },
  {
    id: 'keane-1999', nome: 'Roy Keane', apelido: 'Keane', ano: 1999, nascimento: 1971,
    flag: '🇮🇪', raridade: 'comum', posicao: 'Meia', clube: 'Man. United / Irlanda',
    cor: '#16B89A',
    atributos: { copa_jogos: 0, gols_carreira: 55, copas: 0, titulos: 19, cl_titulos: 1, selecao_gols: 9, selecao_jogos: 67, altura: 178 },
    perguntas: ['titulos', 'cl_titulos', 'selecao_jogos'],
    wikiTitle: 'Roy Keane',
  },
  {
    id: 'cantona-1996', nome: 'Eric Cantona', apelido: 'Le Roi', ano: 1996, nascimento: 1966,
    flag: '🇫🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Man. United / França',
    cor: '#16B89A',
    atributos: { copa_gols: 0, copa_jogos: 0, gols_carreira: 225, copas: 0, titulos: 13, selecao_gols: 20, selecao_jogos: 45, altura: 188 },
    perguntas: ['gols_carreira', 'titulos', 'selecao_gols'],
    wikiTitle: 'Eric Cantona',
  },
  {
    id: 'vinicius-2022', nome: 'Vinícius Jr.', apelido: 'Vini Jr.', ano: 2022, nascimento: 2000,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Real Madrid / Brasil',
    cor: '#16B89A',
    atributos: { copa_gols: 0, copa_jogos: 7, gols_carreira: 185, copas: 1, titulos: 11, cl_titulos: 2, selecao_gols: 26, selecao_jogos: 56, altura: 176 },
    perguntas: ['cl_titulos', 'gols_carreira', 'selecao_gols'],
    wikiTitle: 'Vinícius Júnior',
  },
  {
    id: 'haaland-2023', nome: 'Erling Haaland', apelido: 'O Exterminador', ano: 2023, nascimento: 2000,
    flag: '🇳🇴', raridade: 'epica', posicao: 'Atacante', clube: 'Man. City / Noruega',
    cor: '#7C3AED',
    atributos: { copa_gols: 0, copa_jogos: 0, gols_carreira: 276, copas: 0, titulos: 6, selecao_gols: 40, selecao_jogos: 50, altura: 194 },
    perguntas: ['gols_carreira', 'altura', 'selecao_gols'],
    wikiTitle: 'Erling Haaland',
  },
  {
    id: 'pedri-2021', nome: 'Pedri', apelido: 'Pedri', ano: 2021, nascimento: 2002,
    flag: '🇪🇸', raridade: 'comum', posicao: 'Meia', clube: 'Barcelona / Espanha',
    cor: '#16B89A',
    atributos: { copa_jogos: 3, gols_carreira: 38, copas: 1, titulos: 9, selecao_gols: 8, selecao_jogos: 34, altura: 174 },
    perguntas: ['selecao_jogos', 'gols_carreira', 'copa_jogos'],
    wikiTitle: 'Pedri',
  },
  {
    id: 'bellingham-2024', nome: 'Jude Bellingham', apelido: 'Bellingham', ano: 2024, nascimento: 2003,
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', raridade: 'comum', posicao: 'Meia', clube: 'Real Madrid / Inglaterra',
    cor: '#16B89A',
    atributos: { copa_gols: 3, copa_jogos: 7, gols_carreira: 116, copas: 1, titulos: 9, cl_titulos: 1, selecao_gols: 24, selecao_jogos: 51, altura: 186 },
    perguntas: ['gols_carreira', 'cl_titulos', 'selecao_gols'],
    wikiTitle: 'Jude Bellingham',
  },
  {
    id: 'di-stefano-1960', nome: 'Alfredo Di Stéfano', apelido: 'La Saeta Rubia', ano: 1960, nascimento: 1926,
    flag: '🇦🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Real Madrid / Argentina',
    cor: '#16B89A',
    atributos: { copa_gols: 0, copa_jogos: 0, gols_carreira: 552, copas: 0, titulos: 18, cl_titulos: 5, selecao_gols: 29, selecao_jogos: 31, altura: 178 },
    perguntas: ['gols_carreira', 'cl_titulos', 'titulos'],
    wikiTitle: 'Alfredo Di Stéfano',
  },
  {
    id: 'kempes-1978', nome: 'Mario Kempes', apelido: 'El Matador', ano: 1978, nascimento: 1954,
    flag: '🇦🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Valencia / Argentina',
    cor: '#16B89A',
    atributos: { copa_gols: 9, copa_jogos: 18, gols_carreira: 306, copas: 3, titulos: 8, selecao_gols: 20, selecao_jogos: 43, altura: 178 },
    perguntas: ['copa_gols', 'copa_jogos', 'gols_carreira'],
    wikiTitle: 'Mario Kempes',
  },
  {
    id: 'rivelino-1970', nome: 'Rivellino', apelido: 'Rivellino', ano: 1970, nascimento: 1946,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Meia', clube: 'Corinthians / Brasil',
    cor: '#16B89A',
    atributos: { copa_gols: 3, copa_jogos: 14, gols_carreira: 134, copas: 3, titulos: 7, selecao_gols: 26, selecao_jogos: 94, altura: 175 },
    perguntas: ['copa_jogos', 'copas', 'selecao_jogos'],
    wikiTitle: 'Rivellino',
  },
  {
    id: 'tostao-1970', nome: 'Tostão', apelido: 'O Menino de Ouro', ano: 1970, nascimento: 1947,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Atacante', clube: 'Cruzeiro / Brasil',
    cor: '#16B89A',
    atributos: { copa_gols: 2, copa_jogos: 6, gols_carreira: 180, copas: 1, titulos: 6, selecao_gols: 30, selecao_jogos: 54, altura: 168 },
    perguntas: ['copa_gols', 'copa_jogos', 'altura'],
    wikiTitle: 'Tostão',
  },
  {
    id: 'didi-1958', nome: 'Didi', apelido: 'O Príncipe Etíope', ano: 1958, nascimento: 1928,
    flag: '🇧🇷', raridade: 'comum', posicao: 'Meia', clube: 'Botafogo / Brasil',
    cor: '#16B89A',
    atributos: { copa_gols: 3, copa_jogos: 13, gols_carreira: 151, copas: 2, titulos: 6, selecao_gols: 20, selecao_jogos: 68, altura: 176 },
    perguntas: ['copa_gols', 'copa_jogos', 'copas'],
    wikiTitle: 'Didi (footballer)',
  },
]

export function getCard(id: string): HistCardData | undefined {
  return HIST_CARDS.find(c => c.id === id)
}

export function getRaridadeLabel(r: HistCardData['raridade']): string {
  return r === 'mitica' ? 'MÍTICA' : r === 'epica' ? 'ÉPICA' : 'COMUM'
}

export function getRaridadeColor(r: HistCardData['raridade']): { bg: string; text: string; glow: string } {
  if (r === 'mitica') return { bg: 'linear-gradient(135deg, #78350f, #b45309, #d97706, #fbbf24)', text: '#fef3c7', glow: '#f59e0b' }
  if (r === 'epica') return { bg: 'linear-gradient(135deg, #1e1b4b, #4338ca, #7c3aed)', text: '#ede9fe', glow: '#818cf8' }
  return { bg: '#fff', text: '#000', glow: 'transparent' }
}

export const QUESTION_LABELS: Record<string, (_ano: number) => string> = {
  copa_gols:    (_) => 'Quantos gols marcou em Copas do Mundo ao longo da carreira?',
  copa_jogos:   (_) => 'Quantas partidas disputou em Copas do Mundo no total?',
  selecao_gols: (_) => 'Quantos gols marcou pela seleção nacional em toda a carreira?',
  selecao_jogos:(_) => 'Quantas partidas disputou pela seleção nacional na carreira?',
  ballon_dor:   (_) => 'Quantas Bolas de Ouro conquistou ao longo da carreira?',
  cl_titulos:   (_) => 'Quantas Champions League / Copa dos Campeões ganhou?',
  gols_carreira:(_) => 'Quantos gols marcou ao longo de toda a carreira profissional?',
  titulos:      (_) => 'Quantos títulos conquistou ao longo de toda a carreira?',
  copas:        (_) => 'Em quantas Copas do Mundo participou ao longo da carreira?',
  altura:       (_) => 'Qual era a sua altura em centímetros?',
}
